### ISSUE TITLE
Using stack_name with dependencies problem

### ISSUE THREAD

**Issue by padilo** [cloudreach/sceptre#101]
If I have two stacks that I launch on environment dev:

config/dev/cloud1.yaml
```
---
template_path: templates/infrastructure/cloud1.json
stack_name: my-cloud1-stack
```
and
```
config/dev/cloud2.yaml
---
template_path: templates/infrastructure/templates/cloud2.json
stack_name: my-cloud2-stack
parameters:
  param1: !stack_output cloud1::ZookeeperInstancesSecurityGroup

```

It gives me the following error when trying to launch all environment:
```
Traceback (most recent call last):
....
_get_stack_outputs
    raise StackDoesNotExistError(e.response["Error"]["Message"])
StackDoesNotExistError: Stack with id myconfig-dev-cloud1 does not exist
```

It seems it tries to guess the default stack_name instead of reading it from my config file.

I don't know if I did something wrong but that what I expect.

**Comment by padilo** [comment]
Sorry, I just realized there is a warning about this in the documentation. It will be solved in the future?
http://sceptre.cloudreach.com/docs/stack_config.html#stack-name
I can try to PR this if you want

**Comment by jamesroutley** [comment]
Hey @padilo - we looked at implementing this, but decided not to implement it for v1 because it would have required some major code rewrites. We'll definitely consider this issue when architecting v2 though!
