### ISSUE TITLE
Consume sceptre as a library

### ISSUE THREAD

**Issue by alex-harvey-z3q** [cloudreach/sceptre#1036]
I wish to consume Sceptre as a library in a Python project. I note however that comments in the code recommend not importing the `sceptre.cli` module. Is there documentation on how to import Sceptre as a library, is it even really possible given the existing code organisation, and are there any code examples?

**Comment by ykhalyavin** [comment]
We render all / some templates for later validation with cfn-lint / cfn_nag / etc with a simple custom script like:
`
from sceptre.context import SceptreContext
from sceptre.plan.plan import SceptrePlan
from sceptre.helpers import normalise_path

...

context = SceptreContext(
    project_path=project_path.as_posix(),
    command_path=sceptre_group,
    user_variables=user_variables,
    ignore_dependencies=True
)
plan = SceptrePlan(context)

...

for stack, template_body in plan.generate().items():
    ...
`

@alexharv074  hope it helps
