### ISSUE TITLE
MFA support for iam_role

### ISSUE THREAD

**Issue by mitom** [cloudreach/sceptre#104]
It would be great to be able to provide iam roles that require MFA authentication in the environment config for Sceptre to switch to.
If you are open for the option I'd be happy to help out with this.

As a proposal for the new behaviour for assuming the role:
1. Try to assume to role without providing MFA information. This will either work, in which case there is nothing to do, or it will error (sadly it doesn't tell us if it's an MFA related error or just lack of permissions).
2. If there was an AccessDenied error (which we get for lack of MFA), it will contain the arn of the current user, which contains the account id and the username. This is enough to construct the MFA device for the user since it's `arn:aws:iam::{account_id}:mfa/{username}`.
3. Prompt the user for an MFA code
4. Attempt to assume the role again, providing the MFA token and device from `2.` and `3.`
5. Either succeed or inform the user of the error.

What do you guys think?

**Comment by jamesroutley** [comment]
What's the current behaviour? I thought you could supply roles which require MFA, and boto just prompts for a token?

**Comment by mitom** [comment]
It throws an AccessDenied error. Awscli does the prompting, boto doesn't do it by itself as far as I know - the reason probably being if it did it would hang the application waiting for input.

**Comment by jamesroutley** [comment]
Interesting - I wonder if there's botocore code we can use for the MFA prompt?

**Comment by theseanything** [comment]
Wasn't sure if you knew the work around for now -  you can set up a role assume with MFA, by configuring a profile in the aws config file - [docs here]( http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html#cli-roles-mfa)

@mitom More than happy for you to put in a pull request! :) 

Another part of the MFA issue is that the session (sts token) doesn't persist between sceptre commands. Hence requiring you to input a new MFA token every time a sceptre command is run.

**Comment by mitom** [comment]
@jamesroutley From what I have seen[ boto prompts for MFA only if the profile has an 'mfa_serial' field in it](https://github.com/boto/botocore/blob/cb8d4b87fbe13b42653017b74c9a5f4097ae740c/botocore/credentials.py#L978-L981). This would probably not work for Sceptre as the result would be having to store the mfa_serial in the config as well which would make it impossible to share with other people. We could add a `use_mfa` field to signify the role requires an MFA prompt. A valid reason for that would be that in the process I described above if the person genuinely has no access to the role and not due to MFA, it would still prompt for an MFA and then say access is denied. Sadly the 2 errors are identical, boto doesn't say why the access was denied. Do you think this should be added or do you have some other idea to figure out if the role requires MFA?

@theseanything I know it's possible, it's the way I'm using it now. The reason why I'd prefer this functionality to be in Sceptre is that when there are multiple people interacting with a project that has several environments deployed into multiple AWS accounts this makes keeping track of which env is where effortless.

The persistence between commands is a good point. Maybe we could create a `.sceptre` directory in the project to use as a cache? Or a `~/.sceptre` to avoid accidentally committing them to version control? Is it worth adding the extra chore of maintaining the cache directory to avoid extra MFA prompts?

**Comment by mitom** [comment]
I've created a PR for this, we should continue the conversation there.
