### ISSUE TITLE
Estimate Template Cost Functionality 

### ISSUE THREAD

**Issue by johnculkin** [cloudreach/sceptre#106]
I'd like Sceptre to add the ability to provide estimated costs for a stack/template 

https://docs.aws.amazon.com/cli/latest/reference/cloudformation/estimate-template-cost.html

Step 1: 
Just provide the Simple Monthly Calculator URL that is returned.
Step 2: 
Scrape the value and provide the total cost directly, this could be useful when programmatically making decisions about when to launch a template/stack.

Bonus:
It would also be great to estimate the cost for an environment.

**Comment by jamesroutley** [comment]
Could you elaborate on "scrape the value"? What does the website look like? Is it an API or will we have to literally scrape HTML?

**Comment by theseanything** [comment]
Sadly it looks like the API call returns a URL to the AWS "Simple" Cost Calculator page.... Not just the estimated cost.

http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.estimate_template_cost

So yeah you'd parse the HTML of the page to pull the cost information - if you want sceptre just to give you a number. Could compromise and get sceptre to just open the browser at the url.

**Comment by theseanything** [comment]
As discussed with @jamesroutley - due to the effort to benefit ratio of this feature, we see this as a lower priority feature.

**Comment by johnculkin** [comment]
Ok :(

**Comment by stevear22** [comment]
I am running into the need to do this also - A link to the simple calculator would be good enough I think.
