### ISSUE TITLE
Add YAML document markers to template body 

### ISSUE THREAD

**Issue by mrowlingfox** [cloudreach/sceptre#1087]
# Proposal
Add Yaml start document markers to the template body.

Initially, I ran into this lack of markers when using the `generate` command. I was trying to process the output programmatically and ran into issues trying to separate the documents from multiple stacks.

This is 100% compliant with [YAML Ain’t Markup Language (YAML™) Version 1.2 Document Markers](https://yaml.org/spec/1.2/spec.html#id2800401)

Another addition that **_may be considered_**, is the use of `...` at the end of documents. This is YAMl compliant, however much less common in usage. Also would need to confirm if CloudFormation supports them or not.

### Expected behaviour
When the template body is generated:
- If the `---` marker is not present at the start of the template, insert it.
- If the `...` marker is not present at the end of the template, insert it. (potentially)

**Comment by mrowlingfox** [comment]
Doing some testing with Cloudformation. It happily accepts both `---` and `...` markers for YAML templates.
It _**also**_ accepts the same for JSON templates. 

This leads to the assumption that CFN uses YAML to parse the template, regardless of what file suffix is used. 
In the case of sceptre it's always .json [as seen here](https://github.com/mrowlingfox/sceptre/blob/master/sceptre/config/reader.py#L472). On a side note, this should potentially be updated to reflect the correct file type (I quickly tested it with .yaml, it works 🥳   🎉 ).

Do we want to add these markers to all templates, or limit it to only ones with yaml?

Personally, Yes.

I would lean towards adding them to all of the documents and accepting that they're all yaml compliant. 
_**If**_ anyone is already processing the output of generate and they're using json templates, then the chances are that they're already doing some manipulation of the data to accommodate handling multiple json blobs separated by new lines.

**Comment by craighurley** [comment]
I would be in favour of changing less - just adding --- for yaml.  IIRC, using `generate` with output json, you get an array of templates, so I'm not sure why you would want to add ---/... to those.

**Comment by mrowlingfox** [comment]
> I would be in favour of changing less - just adding --- for yaml. IIRC, using `generate` with output json, you get a json array of templates, so I'm not sure why you would want to add ---/... to those.

@craighurley  Thank you for mentioning the being able to set output as json, that may potentially help my use case a lot 😄 🤦‍♂️ 

For what it's worth, even after adding `---` and `...` in my fork, using `--output=json` still returns the same expected behaviour with the array of templates.
