### ISSUE TITLE
Version docs

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#113]
Currently, we push new docs to `<s3 bucket>/docs`. Switch to pushing docs to both `<s3 bucket>/<version_num>/docs` and `<s3 bucket>/latest/docs`

**Comment by amongil** [comment]
Does it refer to lines [24](https://github.com/cloudreach/sceptre/blob/master/circle.yml#L24) and [26](https://github.com/cloudreach/sceptre/blob/master/circle.yml#L26) on the ```circle.yml``` file?

If so, I can pick this one up.

**Comment by jamesroutley** [comment]
Yep - that sounds great

**Comment by theseanything** [comment]
#146

**Comment by jamesroutley** [comment]
v1.2.0
