### ISSUE TITLE
Deprecate project_variables resolver

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#116]
## Overview

I think we should deprecate the [`project_variables`](https://sceptre.cloudreach.com/docs/stack_config.html#project-variables) resolver for the following reasons:

1. It doesn't fulfil it's intended use. The resolver was originally added to allow Sceptre users a way to store configuration items shared by several stacks in a single place. The current implementation only allows for a single configuration item to be passed to each stack (#115), which isn't useful if you want to have more than one piece of common config. 
2. It's syntax is overly verbose. You have to namespace your environment and stack, leading to highly nested files.
3. It confuses users #48 . By introducing yet another way to dynamically add configuration to stack config files (alongside user variables and environment variables), it is unclear which the 'right' method is.

## Todo

Throw a deprecation warning when the `project_variables` resolver is used.

## Implementation

The warning should be done with the [`warnings`](https://docs.python.org/2/library/warnings.html) library. A [deprecation warning](https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning) should be raised. Because deprecation warnings are ignored by default, they will need to be [switched on](http://stackoverflow.com/a/20960427). The warning should print `The project_variables resolver is being deprecated, and will be removed in Sceptre version 2.0`. 

Bonus points for printing the warning in yellow - we use [`colorama`](https://pypi.python.org/pypi/colorama) for colouring text.

Code should be added to the beginning of the `resolve()` [function](https://github.com/cloudreach/sceptre/blob/master/sceptre/resolvers/project_variables.py#L27).

## Definition of done

- Using the `project_variables` resolver should print out a warning that it'll be deprecated in version 2.0
- A deprecation notice should be added to the relevant section of the documentation

**Comment by amongil** [comment]
I would like to take this one.

**Comment by jamesroutley** [comment]
@albertoal Nice one - thanks!
