### ISSUE TITLE
Access to environment config in stacks

### ISSUE THREAD

**Issue by mitom** [cloudreach/sceptre#119]
Is it possible to access the environment config in the stacks? For a concrete use-case: we need to follow tagging policies which require us to tag everything that can be tagged with a set of tags (e.g, owner, project, environment and such). It would be handy to be able to define these in the environment config and make them accessible to all of the stacks. An other example could be the region, it is useful to have for userdata scripts. Is there any reason why we shouldn't have access the environment config in a read-only manner? 

At the moment a workaround could be to write a hook that copies over the environment config to the stack config and add it as a before update/create hook but it's pretty hacky.

**Comment by dnedbaylo** [comment]
I ended up with variables file e.g. `vars.yaml` defined in environment directory and a custom resolver.

**Comment by ianburrell** [comment]
One solution to defaults for stack is to use Jinja2 include:

`
{% include 'defaults.yaml' %}
`
