### ISSUE TITLE
Stack config key `protect` raises exception when used

### ISSUE THREAD

**Issue by afdezl** [cloudreach/sceptre#120]
When using the `protect` key in a stack config, the exception `AttributeError: 'Stack' object has no attribute 'full_stack_name'` is raised.  The decorator method uses a deprecated version of the stack name attribute. Should be replaced with `self.name` in the helpers file.

**Comment by jamesroutley** [comment]
@afdezl - thanks for pointing that out - you got time to submit a PR? dw if not - let me know and I can put one in

**Comment by jamesroutley** [comment]
Haha looks like you just put one in - thanks!

**Comment by afdezl** [comment]
Done.
