### ISSUE TITLE
Add Ansible-style vault feature (code included)

### ISSUE THREAD

**Issue by dboitnot** [cloudreach/sceptre#126]
I've implemented an Ansible-style vault feature which allows you to store secrets in encrypted files. It has been implemented as a standalone tool but could easily be integrated into the sceptre CLI. Three commands are supported: encrypt, decrypt, and edit. All three accept a file as an argument and expect the ```SCEPTRE_VAULT_PASSWORD``` environment variable to contain the password to decrypt the file.

At present I've only implemented one resolver: ```vault_parameter```. It looks for the file ```config/secrets.yaml```, decrypts it, and returns the appropriate key:

**config/secrets.yaml:**
```
---
test:
  EngineDemo:
    DbPassword: somebigsecret
```

**Encrypt the file:**
```
$ ./sceptre-vault.py encrypt config/secrets.yaml
```

**config/test/EngineDemo.yaml:**
```
---
template_path: templates/Engine.yaml
parameters:
  DbPassword: !vault_parameter DbPassword
```

**Attached:** [SceptreVault.zip](https://github.com/cloudreach/sceptre/files/1016571/SceptreVault.zip)

**Comment by jamesroutley** [comment]
This is really cool! Our intention for custom resolvers like this is to have people publish them themselves on GitHub, and we can link to it in our docs. If you push the code to a new GH repo, we'll add a link to it if that's alright with you?

**Comment by dboitnot** [comment]
Makes sense. Do you guys have a recommended way to link to the resolver repository within your own repo? Ideally, our Sceptre configuration repo would work after a clone without having to take extra steps. Maybe something with Git subtrees?

**Comment by ngfgrant** [comment]
#205 Adds supports for pip installable resolvers. If this can be pip-installable then it can be included in a project.
