### ISSUE TITLE
Instantiate config and connection managers from stack name

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#135]
With the current implementation of `Config` and `Connection Manager`, instantiating them requires the caller to have access to specific information about the environment. 

For example, to instantiate a stack `Config` object, one must pass in:

- sceptre directory
- environment path
- base file name
- environment config
- connection manager

This makes instantiating a `Config` or `Connection Manager` difficult, unless you already have access to the `Environment` object. This leads to difficulty in implementing solutions to issues like #85, #89, #5. 

I think we should change the initialisers to take a single stack or environment name.

The initialiser function should cache the objects created, and return the cached object if it is requested again.

**Comment by jamesroutley** [comment]
Initial PR #136

**Comment by theseanything** [comment]
PR denied - may revisit this issue.
