### ISSUE TITLE
using the native CF stack exports doesn't resolve dependencies

### ISSUE THREAD

**Issue by rafcio19** [cloudreach/sceptre#139]
If native CF [stack exports](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) are being used for inter-stack dependencies then sceptre does not resolve these dependencies correctly. Launching stacks with that functionality will still result in a successful sceptre run, exit code 0.

**Comment by theseanything** [comment]
This is a duplicate of #93.
