### ISSUE TITLE
Nonscalar resolver and hook arguments

### ISSUE THREAD

**Issue by sftrabbit** [cloudreach/sceptre#140]
YAML's tag syntax supports nonscalar tag arguments, such as lists or mappings (or even other tags). For example:

    !sometag
      foo: bar
      baz: 123

However, Sceptre doesn't allow this for the arguments of resolvers and hooks. The resolver and hook constructors added to the YAML loader assume a scalar argument when calling `loader.construct_scalar(node)` (for both [resolvers](https://github.com/cloudreach/sceptre/blob/7ff56cd58f6885847d8577dade2524663958fb72/sceptre/config.py#L224) and [hooks](https://github.com/cloudreach/sceptre/blob/7ff56cd58f6885847d8577dade2524663958fb72/sceptre/config.py#L262)).

It would be useful to support nonscalar arguments for both resolvers and hooks for more configurable cases such as something like this:

    !s3_upload
      path: some/file/path
      s3_bucket: !stack_output another_stack::BucketName
      s3_object_key: some_key

(Note the nested resolver! That's a bonus!)

There's a few ways to work around this at the moment, such as by passing things through `sceptre_user_data` or by passing strings that you parse into multiple arguments, but they typically result in some shenanigans involving using sceptre internals. Nonscalar arguments would be very neat and tidy!

PR incoming...

**Comment by cboss24** [comment]
@theseanything any thoughts on this feature? Anything I can help implement?

**Comment by ngfgrant** [comment]
Hi @sftrabbit - great issue and nice PR. Unfortunately, Sceptre has changed quite a bit. If this is still something you would like to see then you may need to redo the implementation of this 🙏

**Comment by ngfgrant** [comment]
Resolved by 473
