### ISSUE TITLE
Ability to configure Template S3 Object ACL 

### ISSUE THREAD

**Issue by nmyster** [cloudreach/sceptre#142]
I want to be able to set the Object ACL of a template being uploaded to S3.

This would allow shared-services accounts or other central accounts to have all CFT templates and accessed by the central account.

**Comment by theseanything** [comment]
@nmyster Before you submit a PR  -  could you give information about how'd you'd implement?

**Comment by ngfgrant** [comment]
This is something that could be done. It is not entirely clear why or where this is needed. Closing for now.
