### ISSUE TITLE
Alternative method(s) for resolver/hook registration

### ISSUE THREAD

**Issue by sftrabbit** [cloudreach/sceptre#145]
Sceptre currently looks for resolvers and hooks (and everything else) within specific locations in the directory structure. In some cases, it would be useful to be able to register resolvers and hooks programatically or with some configuration. This will also help with the distribution of common resolvers and hooks for community use - the developer wanting to use the resolver/hook will just add the dependency to their `requirements.txt` as normal and then write some kind of registry file that gets executed before doing any work. Something like:

```
from myhook import MyHook
from sceptre import register_hook

register_hook(MyHook)
# or maybe register_hook('my_hook', MyHook)
```

Alternatively, this could be done with some kind of configuration file:

```
hooks:
  my_hook: myhook.MyHook
```

although listing python imports in a config file feels a bit wrong to me.

**Comment by jamesroutley** [comment]
Yep - this is a good idea, we'll have a think about a user-friendly way of using it.

**Comment by akdor1154** [comment]
`setuptools` has functionality specifically for this - http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins .
Would then be as simple as `pip install vault-resolver-my-custom-thingy`.

**Comment by theseanything** [comment]
Solved with PR #205 - will be available in version 2.0

**Comment by cboss24** [comment]
@theseanything it looks like that PR removed the ability to have a `hooks` folder at the sceptre root, and then have your hooks registered for `free`. What was the reasoning behind this, could we have best of both worlds where some hooks come from the setuptools entrypoint, while other come from the `hooks` folder?

**Comment by stolendog** [comment]
The same question as @cboss24 wrote, why we don't have a possibility to register hooks from `hooks` folder in v2?
