### ISSUE TITLE
Tutorial has a mistake in it. 

### ISSUE THREAD

**Issue by Kegley** [cloudreach/sceptre#15]
The tutorial says to point to templates/vpc.yaml but the template is templates/vpc.json

`vpc.yaml
Add the following config to vpc.yaml:

template_path: templates/vpc.yaml
parameters:
  CidrBlock: 10.0.0.0/16
template_path specifies the relative path to the CloudFormation or Troposphere template to use to launch the stack.`

**Comment by jamesroutley** [comment]
Thanks - good spot. #17
