### ISSUE TITLE
Rethink where --var's are stored

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#154]
Currently, users can template variables into config files by supplying them on the CLI, with the flags `--var` and `--var-file`. The variables to be templated are passed into the `Environment` via the `options` argument, before being passed to the `Config` object. For stack configs, we need to do the same.

This current pattern makes it difficult to instantiate Stacks or Configs without having already instantiated an Environment (which is a model we're trying to move towards). Ideally there should be some easier way of doing this.

**Comment by ngfgrant** [comment]
Closing as it relates to a previous issue.
