### ISSUE TITLE
Clarify windows support in documentation.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#156]
We should a note in the documentation about at what level we support windows.

**Comment by ngfgrant** [comment]
Sometimes there have been issues with \ / issues in file paths in windows. Some have suggested making docs explicit about windows setup. This issues should direct users having issues with Python in Windows they should consult those docs.

**Comment by Arlington1985** [comment]
any info? Does anybody know how to specify PATH for Windows?

**Comment by ngfgrant** [comment]
@Arlington1985 - any sceptre/windows path stuff should be fixed in upcoming 2.1.1 release.

**Comment by Arlington1985** [comment]
@ngfgrant , thanks for sharing. So current release (2.1.0) doesn't support windows path then? any workaround?

**Comment by ngfgrant** [comment]
use back slashes for 2.1.0
