### ISSUE TITLE
Add a Windows environment for unit/integration testing.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#157]
Currently our automatic testing occurs in a Ubuntu based environment, it would be going to have support for running tests in a Windows based env too. Even though Python is cross platform, we still would be good test cross platform as are we dependent on OS level functions. i.e. os.path

**Comment by jamesroutley** [comment]
Is there an easy way to do this? Circle, CodeShip, Travis all don't support Windows (which seems bizarre to me).

**Comment by theseanything** [comment]
Decided that Windows support will be untested, due our current CI tool not supporting Windows and onus of cross-platform support being with Python itself.
