### ISSUE TITLE
Stack names use"\" instead of"/" in Windows.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#158]
When executing a 'env' level command e.g. launch-env in a Windows based environment, stack names are generated with backslashes instead of forward slashes. This is due to the use of `os.path` in the [_get_available_stacks](https://github.com/cloudreach/sceptre/blob/master/sceptre/environment.py#L362) function within Environments. 

This causes bugs such as Sceptre not being able to see dependencies, because the stack_output resolver creates stack name using a "/" ([See here.](https://github.com/cloudreach/sceptre/blob/master/sceptre/resolvers/stack_output.py#L93)).

A nice fix maybe to have a common function for generating a full stack name. This then can be used both in Environment and stack_output resolver and ensure that they will be the same. 

(Where I mention stack name, I'm referring to the internal stack name used within Sceptre, not the name given to the stack within CloudFormation.)

**Comment by GouldSJ** [comment]
this is a priority for a public sectopr client using sceptre and your services. If you can prioritise this that would be great

**Comment by theseanything** [comment]
Should be fixed by #165

**Comment by jamesroutley** [comment]
v1.2.0
