### ISSUE TITLE
Confusing message given when deleting a change set that doesn't exist.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#160]
The following error is given when running the `delete-change-set` command to delete a change set that does not exist:
```
[2017-07-06 09:19:03] - sceptre.stack - default/A - Successfully deleted change set 'A'
```
This is confusing because it make it seem that the change set did exist previously. There seems to be a suppression of the Boto3 ChangeSetNotFound exception.

**Comment by trenigma** [comment]
Sorry if this is a dumb question (new guy here 🙂) but could someone direct me to the location of the sceptre code relating to the `delete-change-set` command? As a budding coder I’m guessing that might be a good place to start..

**Comment by m1keil** [comment]
I believe this issue can now be closed.
