### ISSUE TITLE
Allow default value for environment_variable resolver

### ISSUE THREAD

**Issue by Rukenshia** [cloudreach/sceptre#161]
It would be really helpful if the `environment_variable` resolver had the option to default to a specific value, so I could have something like `!environment_variable APP_PORT 8080` or `!environment_variable APP_PORT || 8080` in my yaml file.

**Comment by theseanything** [comment]
Hi @Rukenshia, I agree this would be a handy feature to have added to our in-built resolver! At the moment you can achieve, having a default by either using the jinja2 templating functionality - [docs here](https://sceptre.cloudreach.com/docs/environment_config.html#environment-variables). Just take advantage of jinja's ability to define a default:
```
e.g SomeValue: {{ environment_variable. APP_PORT | default(8080) }}
```
Alternatively you could write a[ custom resolver](https://sceptre.cloudreach.com/docs/advanced_patterns.html#custom-resolvers) to support the use of a default. Or even better if you put in PR for the current resolver, we'd happy to consider it! Hope that helps :)

**Comment by akdor1154** [comment]
Hi @theseanything, your workaround doesn't seem to work.
In your example, I would get the crash and exception
```
'os._Environ object' has no attribute 'APP_PORT'
```

**Comment by theseanything** [comment]
@akdor1154 Sorry for not getting back to you. Did you manage to get this working? I tested it on a linux/macOS and seem to be working fine. I'm going to close this for now - let me know if you are still having issues.

**Comment by sopeters** [comment]
I have these issues - doesn't seem to work for me.

I have the following entry in the config.yaml

build_number: {{ environment_variable.BITBUCKET_BUILD_NUMBER | default("no-build-number") }}

When running sceptre launch I get

'os._Environ object' has no attribute 'BITBUCKET_BUILD_NUMBER'

on MacOS
