### ISSUE TITLE
Allow Sceptre to call any function for the Boto3 CloudFormation Client.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#162]
Currently we have a few commands that are replicated in Sceptre, which do little more than just call the same function within Boto3 CloudFormation client. e.g. continue-update-rollback, describe resources, get-stack-policy, etc.. However it is helpful to call them through Sceptre, as we get the added bonus of IAM assume roles, and referencing stack using the Sceptre environment/stack notation e.g. base/networking vpc.

It may be more elegant if we reduced this common pattern to a single Sceptre function e.g. where by if the function is not a native Sceptre function i.e. launch-env, lock-stack etc... then check if command name is a boto3 client function and if we have enough information, call it, but if not say command not found. 

This extend Sceptres to being able to do more of what Boto3's CloudFormation Client can do, removes the need to manually support each command and reduces repeated code within Sceptre.

**Comment by ngfgrant** [comment]
Hi @theseanything 

Agree that we should be able to do 1:1 what Boto3 can offer. Have you had any more thoughts on this feature? Is it something that can be implemented pre v2?

**Comment by theseanything** [comment]
Would be good to cover functionality within boto, but would like to see the implementation of this to be higher-level/more meta, rather than implementing each individual functionality separately. 

Added it to the backlog, not a huge priority atm.

**Comment by ngfgrant** [comment]
Closing for now. Maybe better to be explicit about what functionality is covered by Sceptre.
