### ISSUE TITLE
Should Jinja rendering of Templates be opt in

### ISSUE THREAD

**Issue by georgealton** [cloudreach/sceptre#173]
Provisioned a few new stacks under the latest release and in some places where some of my in template Resource descriptions contained '{{', it triggered the new templating engine to error. 

Great feature, but could it be possible to opt in? by default it seems to have unexpected effects. a flag at the cli, or possibly a value in a stack?

**Comment by theseanything** [comment]
@georgealton yup agree, was an oversight! PR #174 should provide a simple solution for now.

**Comment by jamesroutley** [comment]
We've just merged this and we'll push out a release today
