### ISSUE TITLE
Redirects don't work for versioned docs

### ISSUE THREAD

**Issue by rdkr** [cloudreach/sceptre#176]
From Google: https://sceptre.cloudreach.com/docs/stack_config.html
301 to: https://sceptre.cloudreach.com/latest/stack_config.html
Instead of: https://sceptre.cloudreach.com/latest/docs/stack_config.html

**Comment by theseanything** [comment]
@rdkr thanks for that! Will fix :)

**Comment by theseanything** [comment]
Should be fixed now :)
