### ISSUE TITLE
Using environmental configs in multiple stacks. 

### ISSUE THREAD

**Issue by cboss24** [cloudreach/sceptre#182]
Hey Sceptre people!

I am trying to define one set of AWS resource tags which would be applied to all my stacks. 

It seems like the best place to define these tags would be in the environment config file. The documentation hints that custom environment configs are possible: 
> Sceptre only checks for and uses the above keys in environment config files, but any others added by the user are read in and are made available to the user via the sceptre.environment.Environment().config attribute

But how do I get the tags into my stack config file? There doesn't seem to be a resolver to handle this... How exactly does one use `sceptre.environment.Environment().config`?

It seems like `project_variables` were meant to handle this use case (sharing a single variable across multiple stacks), however, it seems this is being deprecated. Any thoughts on the best way to approach this problem?

Loving this tool! Thanks in advance!

**Comment by theseanything** [comment]
Hey @cboss24, so we currently don't have a place to specify stack tags once for the whole environment. It *might* be possible via jinja templating of the stack config - [docs](https://sceptre.cloudreach.com/latest/docs/environment_config.html#templating)

**Comment by cboss24** [comment]
Hey @theseanything! Thanks for your quick reply.

As far as I can tell, the only variables available to the stack config templating are:
- `environment_variable` (os.environ)
- `var` (anything passed in with the --var flag)
- `environment_path`

I don't see a way to access any environment config values from within the stack config templating. 

Is this something worth adding? Either that or a more specific `env_tags` field at the environment config level?

**Comment by cboss24** [comment]
I found an existing issue for the general solution, so I will close the issue
[](https://github.com/cloudreach/sceptre/issues/150)

However, it seems like my use case has come up in the past.
[](https://github.com/cloudreach/sceptre/issues/119)

What do you think about having `env_tags` as a built in environment config?
