### ISSUE TITLE
Common Parameters

### ISSUE THREAD

**Issue by LoneBlueIron** [cloudreach/sceptre#191]
I am not sure if this is the appropriate forum for this (Is there a "Support" forum somewhere?).

I am new to Sceptre (love it BTW).

I have a use case whereby I have several stacks being deployed all with a common set of parameters required.  Currently, the parameters are defined in each stack config leading to a large amount of duplication.  Is it possible, or could it be possible to add the ability to place parameters in the environment config files?  This way, a common set of parameters could be supplied to all stacks in the environment (less duplication).

**Comment by JuanCanham** [comment]
Support for his has been merged into master (but isn't yet released (As of 1.2.1)), for now you can reference [user variables](https://sceptre.cloudreach.com/latest/docs/environment_config.html#var) (or do a pip install from master if you like living on the edge)

**Comment by ngfgrant** [comment]
Hey @LoneBlueIron 

Thanks so much for taking the time to comment. We'll be utilising StackOverflow for support type questions. We'll be updating GitHub with how/where to ask questions on SO in the near future. 

Till then, we are looking to implement what you have suggested in Version 2 of Sceptre. It makes a lot of sense.

Thanks!

**Comment by ianpojman** [comment]
@JuanCanham how does support for this work in newer versions? I still can't find a way to specify common parameters (e.g. a pre-existing VPC ID) across my stacks in one place, without resorting to manually-specified variables

**Comment by JuanCanham** [comment]
@ianpojman Not sure about v2 changes, but for v1.x that is the best you can do, having sceptre try and guess stacks need which parameters, doesn't seam very explicit, so i'm not sure there is a way to fix it.

 The only additional trick i use, is if you have common parameters you can store them in a `common_parameters.yaml` and then include it (however you have to fiddle your indentation a little).

stack.yaml
```
stack_name: {{ environment_path.0 }}-{{ environment_path.1 }}-NET-001-SEG-{{ self._TemplateReference__context.name[:-5] }}
parameters:
{% include 'common_parameters.yaml' %}
    Name: {{ environment_path.0 }}{{ environment_path.1 }}SG-001

stack_tags:
{% include 'common_tags.yaml' %}
```
common_parameters.yaml
```
    VPC: {{ environment_config.vpc_id }}
```

I do this in a few repos where i have very similar stacks (60% same stack.yaml)  and don't want duplication that could cause errors (pre-sceptre the project was a bit of a minefield with similar but not quite the same named parameters/stacks everywhere), but I feel like unless it's really needed, it will confuse most readers so isn't worth it.

**Comment by ngfgrant** [comment]
Same as #256 closing.

**Comment by stolendog** [comment]
if I use jinja2 include, I can include a file only from the current config path? but I would like to share a common file in more than the single environment
