### ISSUE TITLE
Add Support to Prevent Rollback

### ISSUE THREAD

**Issue by sathed** [cloudreach/sceptre#193]
Preventing a stack from rolling back is sometimes needed to debug. There's no way that I can find to do this with Sceptre.

**Comment by oazmon** [comment]
Did PR 194 for this

**Comment by b-t-g** [comment]
Closed by #194.

**Comment by JuanCanham** [comment]
As this is fairly high up the google results for `sceptre --disable-rollback`, i'll just add that #194  solved this by implementing `on_failure` in the stack config, so you can specify
```
on_failure: 'DO_NOTHING'
```
Documentation for this is here: https://sceptre.cloudreach.com/latest/docs/stack_config.html#on_failure
