### ISSUE TITLE
template_path

### ISSUE THREAD

**Issue by LoneBlueIron** [cloudreach/sceptre#195]
I am running sceptre on Windows.

Works great. I usually have the config file named the same as the template file.

I have a need to use a different name for the template than the config file but whenever I add;
template_path: templates/newname.yaml 

I get a KeyError

All works if I keep the names the same.

Any workaround for this?  Maybe I need different pathing?

**Comment by theseanything** [comment]
@LoneBlueIron so it should work with any template name. Check your template file path matches exactly the template_path you've specified in the config file - (it should be relative to the sceptre directory). If your still having issues, could you supply the exact error and tree of your directory structure?

**Comment by LoneBlueIron** [comment]
Thanks.  I figured it out It was my own fault in the way my script was calling the CLI :)
