### ISSUE TITLE
Update contributing guidlines

### ISSUE THREAD

**Issue by b-t-g** [cloudreach/sceptre#200]
The [Rubocop contributing guidelines](https://github.com/bbatsov/rubocop/blob/master/CONTRIBUTING.md) has a lot of good points that we should probably take for Sceptre.

Notably:
* Consistent commit messages.
* Require messages to start with "Fix issue #" (or at least reference the issue number) as it greatly aids with debugging.
* Maybe squash related commits? I'm flexible on this, but it works well with the above two.
* Pull request format.
* Add self to authors?
* Create a changelog.md file and have people update that? (may be helpful with releases).

**Comment by aehlke** [comment]
A note about what to do about the necessary test runs would help: [my PR](https://github.com/cloudreach/sceptre/pull/199) says circleci is pending and required, but I don't know what the intended next step is there (presumably some maintainer allowing it to be triggered for my PR).

**Comment by b-t-g** [comment]
@aehlke, funny you should mention that, I was just talking to @theseanything (the one I would call the "MAINtainer") and that has to do with us not being able to run CircleCI on forks. He just got back from holiday so your PR review is not to do with integration tests, but that he still has a lot of catching up to do!

**Comment by aehlke** [comment]
@b-t-g any update on the process/workflow for getting tests ran for my PR? I didn't see it mentioned in the referenced PR for this issue.
