### ISSUE TITLE
Add examples repo

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#21]

**Comment by theseanything** [comment]
Can you elaborate on this?

**Comment by jamesroutley** [comment]
Yep - I think a separate repository, sceptre-examples, which several different sceptre directories. 

Sceptre directories will be named after what they contain, there will be READMEs in each directory explaining concepts, and each config file will contain comments. 

- single environment, YAML templates
- single environment, Python templates (with sceptre_user_data)
- two flat environments, Python templates
- nested environments, Python templates
- single environment, stacks with every resolver
- single environment, stacks with every hook type (including custom hook)

**Comment by theseanything** [comment]
or possibly a example sub folder? like in troposphere?

**Comment by theseanything** [comment]
I've updated the reference to in the Examples.rst to point to sceptre-example (which I know doesn't exist yet) in Github instead of our old one in Bitbucket

**Comment by jamesroutley** [comment]
Cool. I think a separate repo makes a bit more sense as it's not strictly part of Sceptre itself.

**Comment by jamesroutley** [comment]
@seanrankine I've created an [examples repo](https://github.com/cloudreach/sceptre-examples) (currently private) which contains tree example projects. Could you take a look? If you're happy with the structure, we can publish it, and move this issue over to it.

**Comment by theseanything** [comment]
Yup, I spotted it. Lets move discussion over there.

**Comment by craighurley** [comment]
@jamesroutley the example repo you linked to returns 404.  Has it moved or been replaced?  I'm keen to see more examples.

**Comment by theseanything** [comment]
@craighurley - sorry for the late reply! The repo is quite outdated now and it may be a while before it gets made public.
