### ISSUE TITLE
Validating Running Against Correct Account

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#222]
In our organization credential are fetched as temporary credentials on the fly and occasionally someone forgets he fetched credentials for account B and run the sceptre for A. To solve this I would like to submit PR that:
If the config.yaml after interpolation and at the point we are apply a stack contains a value named 'aws_account' and that account does not match the account associated with the credentials as evidenced by an sts get-caller-identity, then raise a critical exception and fail the stack before it starts.
Please provide your feelings about this before I start.

**Comment by theseanything** [comment]
I feel this issue could mitigated through the use of `profile` in your config.yaml. The means Sceptre would use the correct set of credentials in your `~/.aws/config|credentials` file. 
Links to docs:
[Named profiles](http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html)
[Profile in environment config](https://sceptre.cloudreach.com/latest/docs/environment_config.html#profile)

**Comment by oazmon** [comment]
Yes! That would work. I suggest adding this fact to: https://sceptre.cloudreach.com/latest/docs/environment_config.html
With your agreement will submit PR.

**Comment by b-t-g** [comment]
@oazmon, just to clarify, what is it that you're suggesting to add to the documentation? The page you said to plan on editing is the same page that @theseanything linked to, or am I missing something?

**Comment by oazmon** [comment]
It now says it. For some reason when I wrote this I search for the keyword 'profile' on web site and did not find it on page. We can close this issue.
