### ISSUE TITLE
Importing hooks, resolvers, and templates from secondary repos

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#223]
Given that the primary sceptre config and setup for a micro service sits in its own git repo and there are MANY such repos. It makes sense to create an import feature. 
I suggest to create this as a pre-processor that fetches the content of other repos, directories in them, and or S3 bucket archives, or Nexus artifact, etc. That the import configuration sit in a yaml file at the root of sceptre tree. Exact syntax to be worked out later.
That the process copies the content of the repo into a new directory and then copies the local sceptre directory tree into the new directory. Sceptre is then run on the result.
I am looking for feed back before implementation. Work title is Orb and the file is Orbfile.yaml.

**Comment by theseanything** [comment]
Hi @oazmon,
So correct me if i'm not understanding - but you'd like to see improved reusability of templates, hooks and resolvers. There are a few discussions around this:
- To improve template reusability we are suggesting the ability to use a folder outside a Sceptre project (issue #213) - this folder could be referenced by multiple projects and managed with Git (or whatever vcs).
- Custom resolvers and hooks are now implemented via entry points - which means they can be pip installed and are applicable to all projects on your system. (#145) - Already merged into the v2.0 development branch.
- And in terms on having a top level settings file - sceptre.yaml has been suggested (#152)

Does this cover what you were suggesting? If so I'll close this issue.

**Comment by oazmon** [comment]
Sean,
- The folder outside is a GREAT start, but to preserve the excellent 'configuration as code' behavior of   Sceptre, and using the sceptre.yaml suggestion we need to add a stanza in scetre.yaml to describe the imports required in such a form that a command such as 'septre fetch-external-templates' can fetch the imports from git or wherever we decide. The stanza entry for each import should specify a subdirectory name under the external template folder to deposit the result, and the git url, optional commit id, and optional path to fetch. And if the result is an zip or tar archive, explode it into the target directory instead of write.  That way a sceptre repo will continue to fully describe a configuration without having to remember where and what to fetch.
- The custom resolvers and hook implementation looks fantastic. I would however add code to continue supporting current behavior, which I think I didn't see, for two reasons: backward compatibility, and the ability for a project to quickly create a local hook or resolver without having to create a complete new python project and build to create a wheel or something like it.
- As to specifying the list of stuff to pip import, again for completeness of the config definition, I would allow a stanza to be added to 'sceptre.yaml' and a command such as 'septre fetch-external-hooks-and-resolvers' that for each entry does:
import pip
pip.main(['install', 'packagename'])

**Comment by oazmon** [comment]
P.S. Is there a planned ETA for V2.0?

**Comment by oazmon** [comment]
P.P.S. We need to look at this not only from a code's point of view, where we add code, but from a user that is trying to add an 'appliance'. A complete set of hooks, templates, etc. that together implement some service, like bastion host, or Storm cluster.

**Comment by theseanything** [comment]
@oazmon Apologies for the delay! Agree with having some degree of backward compatibility - will look at what we can do for hooks and resolvers. The new implementation of templates still needs more discussion. Just trying to draw up a milestone for v2.0 atm... no idea yet on release date though... will probably have beta version before hand.
