### ISSUE TITLE
Not found dependencies should raise error

### ISSUE THREAD

**Issue by alexec** [cloudreach/sceptre#229]
I spent 1/2 day trying to figure out why dependencies was not working. No error was reported but stack would not build. Now I understand you must prefix the dependency with env name, e.g.

Bad (does not exist, but no error returned):
```
dependencies:
- bastion
```

Good:

```
dependencies:
- preprod/bastion
```

So that developers don't spend time debugging this, it should report an error.

**Comment by b-t-g** [comment]
Duplicate of #187.
