### ISSUE TITLE
`launch-env foo` failed, but `update-stack foo/a && create-stack foo/b` succeeds

### ISSUE THREAD

**Issue by stig** [cloudreach/sceptre#230]
I've encountered an issue where we tried to initiate creation of a EB application & environment in a VPC. The VPC already existed, but we needed to add an output of the VPC id so we could configure the EB environment with this. Initiating a `sceptre launch-env foo` failed repeatedly, with the creation of the new stack (`my-app`) being rolled back. However, doing it in two steps succeeded and running `sceptre launch-env foo` afterwards reported no errors:

    sceptre update-stack foo vpc
    sceptre launch-stack foo my-app

I was not able to get any information from CloudFormation about what caused the rollback. I'm **suspecting** a dependency issue, in that:

1.  `my-app` was added with a dependency on `vpc`
2.  `vpc` already existed, so dependency  was deemed fulfilled
3.  The **particular** output in `vpc` that `my-app` expected did not yet exist
4.  Thus `my-app` creation failed and was rolled back

I'm afraid I failed to note whether running the following two commands would have worked:

    sceptre update-stack foo vpc
    sceptre launch-env foo

**Comment by theseanything** [comment]
Ahah no worries! Glad you managed to figure it out!
