### ISSUE TITLE
--var command line option does not update yaml correct when giving value in dot notation.

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#238]
In our var file we have things grouped. For example:
```yaml
prod:
    aws_account:
    vpc_name:
pre_prod:
   aws_account:
   vpc_name:
```
we then reference these in the different environments being built. The idea being that the user of a similar project just updates the var.yaml file.

We then run a "pre-sceptre hook" to translated vpc_name to vpc_id and add to the command line `--var pre_prod.vpc_id=value` this however does not work as the `--var` command does not respect the dot notation.

I suggest a PR using the following technique:
```python
import collections
import six

def deep_update_kv(source, key, value):
    def deep_update(source, overrides):
        for k, v in six.iteritems(overrides):
            if isinstance(v, collections.Mapping):
                source[k] = deep_update(source.get(k, {}), v)
            else:
                source[k] = v
        return source
    for item in list(reversed(key.split("."))):
        value = {item: value}
    return deep_update(source, value)


def test_deep_update_kv():
    source = {'hello1': 1}
    assert deep_update_kv(source, 'hello2', 2) == {'hello1': 1, 'hello2': 2}

    source = {'hello': 'to_override'}
    deep_update_kv(source, 'hello', 'over')
    assert source == {'hello': 'over'}

    source = {'hello': {'value': 'to_override', 'no_change': 1}}
    deep_update_kv(source, 'hello.value', 'over')
    assert source == {'hello': {'value': 'over', 'no_change': 1}}

    source = {'hello': {'value': 'to_override', 'no_change': 1}}
    deep_update_kv(source, 'hello.value', {})
    assert source == {'hello': {'value': {}, 'no_change': 1}}

    source = {'hello': {'value': {}, 'no_change': 1}}
    deep_update_kv(source, 'hello.value', 2)
    assert source == {'hello': {'value': 2, 'no_change': 1}}

test_deep_update_kv()
```

**Comment by theseanything** [comment]
Hi @oazmon, could you not achieve this via using a custom resolver? [(At the bottom of these docs.)](https://sceptre.cloudreach.com/latest/docs/resolvers.html#custom_resolvers)
For example:
```yaml
template_path: /path/to/file
parameters:
  VpcId: !vpc_name_to_id {{ pre_prod.vpc_name }}
```
Jinja rendering would occur first, then the resolver at runtime would be able to fetch the VPC ID.

**Comment by oazmon** [comment]
We use it not just for vpc_id. But I have entries for aws_account, aws_profile, grouped.
While I can and have changed it to f.ex preprod_{somekey} instead of preprd: somekey: somevalue
It reads better. But your the boss. So if you no like. we live as is.

**Comment by oazmon** [comment]
We could if I could do something like this which is in another open issue from another:
template_path: /path/to/file
parameters:
  Name: !join
    - '-'
      - my name
      - !vpc_name_to_id {{ pre_prod.vpc_name }}

**Comment by theseanything** [comment]
So yup - currently there is no jinja rendering of --var arguments (hence the dot notation doesn't work).  I feel should have a discussion around how better to manage/implement "environment" (i.e. dev/prod etc) variables in v2.0 moving away from var files. (I'll open a separate issue). 

Not entirely sure what you are trying achieve in you specific example above?

**Comment by b-t-g** [comment]
Closing since it has been sitting with the won't fix label for almost 3 weeks.
