### ISSUE TITLE
Possibly Misleading error on update-stack

### ISSUE THREAD

**Issue by jeffmacdonald** [cloudreach/sceptre#239]
Hi.

If you run update-stack and no updates are needed you get this error

`An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed.`

I got confused because strictly speaking it's not a ValidateError. Everything is valid.

**Comment by theseanything** [comment]
Hi @jeffmacdonald, I see your point! Unfortunately, thats the (AWS) boto3 error thats being displayed - therefore to change the message we'd have to catch and re-raise an error, which not idiomatic python :(

**Comment by jeffmacdonald** [comment]
Sounds good to me! Well, It doesn't, but I get what you're saying :) Thanks for response.
