### ISSUE TITLE
Support uploading additional files to S3

### ISSUE THREAD

**Issue by ianburrell** [cloudreach/sceptre#242]
It would be useful if Sceptre could upload files to S3 in addition to the template. This would be useful for config files that could be pulled down by stack. It would also be useful for supporting AWS::Include (#94) and nested stacks (#95). For those, would probably need ability to template the files.

I suggest adding "files" parameter to stack config:
`
files:
  - userdata.sh
`

Maybe have "jinja_files" for files that need to be templated?

I would also suggest that the upload be changed to use directory prefix for whole stack:
`<template_key_prefix>/<region>/<environment>/<stack_name>-<timestamp>/` and then can upload generated template, and other files under the stack prefix.

Would need to add template value for the S3 bucket path.

**Comment by theseanything** [comment]
Could this be covered by a custom hook e.g. `!upload_to_s3` ? 

For the AWS::Include/nested stacks, was thinking about introducing template parsing to obtain a list of files to upload.

**Comment by ianburrell** [comment]
Custom hook would work to prove that it is possible. Will have to see if enough information is available to make work. One issue with hook is that the s3 location needs to be available to stack to use for nested stack. A custom resolver might work. Would work better if used directory prefix for stack instead.

Finding the template automatically for nested stacks and AWS::Include would be nice feature, but I think could start with explicit list of dependent files. Also, Jinja or Troposphere templates would probably need to be builtin support.

**Comment by oazmon** [comment]
I have a push to s3 hook, if you'd like
