### ISSUE TITLE
No way to access stack from hooks

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#246]
Let's say I want to create a custom hook to run a stack validation tool on my stacks before they are instantiated (say cfn-nag or https://www.npmjs.com/package/cfn-check). Current I can't do this if my stacks are written using jinja templates; these tools need a ready-to-go yaml file to run. So a sceptre hook seems to be the obvious way to do this. However, there's no way to access the rendered stack from a hook. This means I have no way of running pre-validation tools on my stack if I'm using Sceptre.

**Comment by akdor1154** [comment]
Current awful awful hack to get this information is:
```python
class CustomHook(Hook):
  def run(self):
    frame = inspect.currentframe()
    stack = frame.f_back.f_back.f_locals['self']
    rendered_template = stack.template.body
    print(rendered_template)
```

**Comment by achidlow** [comment]
Being able to access the `Stack` and `Environment` objects inside hooks and resolvers would be very useful.

I'm working around it like so:
```python
class StackTerminationProtection(Hook):
    def run(self):
        argument = yaml.load(self.argument)
        environment = Environment(self.environment_config.sceptre_dir, self.environment_config.environment_path)
        stack = environment.stacks[self.stack_config.name]
        self.connection_manager.call('cloudformation', 'update_termination_protection',
                                     kwargs={'EnableTerminationProtection': enable,
                                             'StackName': stack.external_name})
```
(can't just use !cmd aws ... because I'm using multiple accounts in different regions).

**Comment by theseanything** [comment]
Yup - currently refactoring Config class and how resolvers/hooks are constructed. Looking at giving them access directly to the associated stack object.
