### ISSUE TITLE
CLI export AWS_PROFILE not working.

### ISSUE THREAD

**Issue by rmbennett** [cloudreach/sceptre#25]
When using the AWS CLI in the getting started tutorial it doesn't mention how to set your AWS CLI details. (Whilst this isn't inherently necessary, I found the following bug)

`export AWS_PROFILE=default` doesn't seem to allow me to run `sceptre create-stack dev vpc` however, `export AWS_DEFAULT_PROFILE=default` works.

**Comment by galbinasu** [comment]
According to the [AWS CLI docs ](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment) the correct environment variable is `AWS_DEFAULT_PROFILE ` and `AWS_PROFILE` is not supported.

**Comment by theseanything** [comment]
hmm not sure why. For me export AWS_PROFILE=profile-name is working. Check your /.aws/credentials and /.aws/config files. (I know you wouldn't, but careful you don't accidentally post creds on here :P )

**Comment by theseanything** [comment]
http://boto3.readthedocs.io/en/latest/guide/configuration.html#shared-credentials-file

**Comment by rmbennett** [comment]
They both work for everything else I've done. So I was surprised, maybe it's just my setup then.

**Comment by jamesroutley** [comment]
I've just tested AWS_PROFILE and it's working for me. I'm going to close this for now - if it continues to be an issue we can reopen.

**Comment by rmbennett** [comment]
Thanks for checking. It must be something particular to my setup. I'll investigate later and log anything I find here for posterity.
