### ISSUE TITLE
Renaming the concept of "environments"

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#253]
Proposing a rename of "environments" within Sceptre. The concept of environments in Sceptre don't align well with the common concept of having different application environments - e.g. (Production, Staging, Development etc...). In Sceptre an environment is used to group stacks into units of infrastructure.

My suggestion would be to rename the concept of "environment" to "grouping" / "group".

**Comment by johnculkin** [comment]
How about Formations?

**Comment by zdhughes** [comment]
Chatted about this offline, but putting it up here for conversation: proposition to rename "stacks" to "templates" and "environments" to "template groups/groupings." This naming is descriptive and shifts the terminology towards a more platform-agnostic approach.

**Comment by JuanCanham** [comment]
>The concept of environments in Sceptre don't align well with the common concept of having different application environments - e.g. (Production, Staging, Development etc...)

How are other people using sceptre? Because that aligns perfectly with how we use it on my project (see below)

I can see how `environments` isn't perfect (as EU for example isn't an environment but a group of them), but think `groups` is weird when using groups of 1 stack 
```
.
├── config
│   ├── EU
│   │   ├── Dev
│   │   │   ├── config.yaml
│   │   │   └── spacewalk.yaml
│   │   ├── Test
│   │   │   ├── config.yaml
│   │   │   └── spacewalk.yaml
│   ├── US
│   │   ├── Dev
│   │   │   ├── config.yaml
│   │   │   └── spacewalk.yaml
│   │   ├── Test
│   │   │   ├── config.yaml
│   │   │   └── spacewalk.yaml
│   │   ├── config.yaml
│   │   └── spacewalk.yaml
│   ├── config.yaml
│   ├── spacewalk.yaml
│   └── tags.yaml
└── src
    └── spacewalk.yaml.j2
```

I also think renaming `stacks` to `templates` would end badly as in my above example the `spacewalk.yaml.j2` "template" generates multiple `stacks`

**Comment by niallgrantcloudreach** [comment]
@theseanything I agree that the name could do with being improved as there is a clear conflict with how environments are widely understood. @JuanCanham I also agree that `group` is probably not specific enough. 

@johnculkin my concern with `Formations` is that is AWS specific and inline with what @zdhughes mentioned towards the end of his comment, it would be preferable to keep names platform agnostic. This is an additional reason to consider moving away from the concept of Stacks. 
 
Looking at the larger providers, an AWS CloudFormation Template and Azure ARM Template are just files that detail collections of resources. As a middle ground I would suggest something like:
-> `resource-group`
-->`resource-template` 

-> `infrastructure-group`
-->`infrastructure-template` 

Where a `resource-group` can be made up of 1 or more `resource-templates`?

I appreciate that it doesn't resolve @JuanCanham point of being a little awkward where there is just a single item in the group.

**Comment by ngfgrant** [comment]
@theseanything I agree that the name could do with being improved as there is a clear conflict with how environments are widely understood. @JuanCanham I also agree that `group` is probably not specific enough. 

@johnculkin my concern with `Formations` is that is AWS specific and in-line with what @zdhughes mentioned towards the end of his comment, it would be preferable to keep names platform agnostic. This is an additional reason to consider moving away from the concept of Stacks. 
 
Looking at the larger providers, an AWS CloudFormation Template and Azure ARM Template are just files that detail collections of resources. As a middle ground I would suggest something like:
-> `resource-group`
-->`resource-template` 

-> `infrastructure-group`
-->`infrastructure-template` 

Where a `resource-group` can be made up of 1 or more `resource-templates`?

I appreciate that it doesn't resolve @JuanCanham point of being a little awkward where there is just a single item in the group.

**Comment by theseanything** [comment]
@JuanCanham apart of the motivation of this renaming, is to possibly re-use the word "environment" to introduce a better variable system to capture config. A very common pattern that we see in projects is the same sets of stack configs **_duplicated_** in "dev", "nonprod", "prod" etcs folders. So was envisioning use stacks and "groups" to make a blueprint of the infrastructure needed for an application. Then use to specify a set of "environment" variables to modify the infra to deploy into the respective environments. For example a sceptre command might be:
`sceptre create networking -e dev`

**Comment by JuanCanham** [comment]
ok, got it, i only have anything other than empty files + config.yaml in the bottom level if somebody has messed up the environment before moving to sceptre and we haven't refactored to use stack_outputs yet. 

Personally i don't like the micro-stacks paradigm as it means you are only using cloudformation as an API wrapper, but as long as the new terms don't affect the ability to launch 'classic environments' e.g if i want to launch `eu/dev`*, i'm happy with any change that makes micro-stackers lives easier.

 One of the strengths of how we use sceptre on my project is that sceptre describe-env '' will describe all of our environments and we don't need any flags to launch a fully configured environment (e.g the full definition is in git on the filesystem)

**Comment by johnculkin** [comment]
Just wanted to mention that GCP uses "deployments" for this concept. 

Seems pretty agnostic of a term - thoughts? Maybe it will spark some new ideas.
