### ISSUE TITLE
Improve cross region/account support

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#257]
We have limited support for multi region or account deployments. Currently you can have separate "environments" in different regions or accounts - (scoped by your aws cli profile). However, there is no support for stacks within a single "environment" to be in different regions/accounts. The currently implementation also restricts the ability to reference stacks in other account or regions for api operation such as `!stack_output`.

Proposed implementation would be to add a class attribute ConnectionManager to store and keep track of different boto sessions associated with each profile or stack_name. This would allow us to reference sessions used by other stacks and interact with that particular account/region. Also adds stack level granularity to connection_manager object rather than sharing one at an "environment" level.

This addresses #89 and #85

**Comment by theseanything** [comment]
Currently under development in branch `cross-account-region-support`. Bulk of implementation done - having issues with the integration tests passing.

Dropping support for Sceptre role assumes (`iam_role`) in favour of using profile exclusively. Betting mapping of profiles between users could be implemented as a feature after this PR.

**Comment by JohnVonNeumann** [comment]
I like how everything I think "yeah that would be useful" you are already working on.

**Comment by campanellaf** [comment]
Is this still ongoing?

**Comment by ngfgrant** [comment]
This is resolved in v2.
