### ISSUE TITLE
Reference external templates from another repository.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#26]
It would be nice to have the ability to reference a centralised repository containing Raw or Python (Troposphere) CloudFormation templates. This would allow multiple Sceptre projects to use the same templates stored in a single repository.

Something like in `template: vpc.py` in  Stack config and `template_repo: github.com/person/cloudfromation-templates`

**Comment by jamesroutley** [comment]
Could you expand on this? Sounds like Sceptre would do a network call to fetch a file stored at an arbitrary network location?

**Comment by theseanything** [comment]
So originally was thinking that sceptre could use git to clone remote template repositories, add them to subfolder within the sceptre install or oh arbitrary folder like ~/.sceptre/template_repos etc... The template repository to be cloned would be specified in the env config like `template_repository: github.com/example/cloudfromation-template`.

Then in the stack config refer to templates that are within the cloned repository by using `template: vpc.py` instead of `template_path: blah/blah`. 

However my only issue now is that its tricky to deal with versioning. Wondering whether its best to just allow users to clone their own template repository manually... Just be nice to have some linkage around sceptre projects and template repositories to make it easier to distribute common, re-usable templates.

**Comment by jamesroutley** [comment]
Yep - I think we should stay away from wrapping around something like Git. It feels out of scope and I think it would add quite a lot of work + complexity. I think we should also be version control system agnostic.

**Comment by jamesroutley** [comment]
@seanrankine Echoing what you said on #71 I'd be much more comfortable with this being implemented as a resolver rather than in 'core' Sceptre. I think this approach would be more extensible.

**Comment by jamesroutley** [comment]
If we implement this, it will be done via a resolver #71
