### ISSUE TITLE
Error in custom resolver documentation

### ISSUE THREAD

**Issue by eikenb** [cloudreach/sceptre#262]
In the resolvers.md doc, at the bottom it has this...

        # <your resolver name> is the lower camel-case version of your class name,

It states lower camel-case (eg. customResolver), when in fact it requires snake-case (custom_resolver). So it should read...

        # <your resolver name> is the lower snake-case version of your class name,

**Comment by b-t-g** [comment]
Quite right; if you'd like to make a PR, go for it, otherwise I can do it.

**Comment by eikenb** [comment]
Seems kind of a small change for a pull request. So please just go ahead.

Also, while there, this sentence seems like it should use some clarification.

    # e.g `custom_resolver` <value> will be passed to the resolver's resolve() method.

That makes it sound like the <value> will be passed to the resolve() method as an argument. Maybe this would be better...

    # e.g `custom_resolver` <value> will be available to the resolver's resolve() method as self.argument.

**Comment by theseanything** [comment]
#263

**Comment by theseanything** [comment]
So the documentation [online](https://sceptre.cloudreach.com/latest/docs/resolvers.html) has the error you mentioned, but docs are good in the repo. Anyway, I've re-jigged the wording as suggested. Changes won't be published until the next release.
