### ISSUE TITLE
Create a set of config and template files from an existing stack

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#264]
We have a need, and I am planning to write and contribute a feature that:
1. Reads AWS CFN for stack with a user specified (as parameter) prefix [or all]
2. Under templates create a subdirectory with a user specified name (as parameter) [or by default 'existing']  and for each stack that matches the prefix from 1 to dump it.
3. Create a subdirectory under config with a user specified name (as parameter) [or by default 'existing']  and for each stack that was dumped in 2 create a config file with template_path, dependencies, and parameter populated with values from AWS CFN.
4. Review the result, and see if we can auto-convert some value from CFN to resolvers such as stack_output
Any feedback?

**Comment by oazmon** [comment]
Note: the issue is easing the conversion of an existing AWS environment to be managed by Sceptre.

**Comment by theseanything** [comment]
Just be clear - the overall idea is to be able to import existing stacks within AWS and create Sceptre projects with the relevant templates and config files?

**Comment by oazmon** [comment]
Correct. The goal is to assume control with Sceptre, effectively migrating from whatever tool they were using to Sceptre.

**Comment by oazmon** [comment]
Submitted a PR for this
