### ISSUE TITLE
Reference to sceptre-tools and bitbucket repo in docs.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#27]
Under the "Configuring an IAM role for Sceptre" in the 'advance patterns" section of the documentation there are still references to the old bitbucket repository. There is also reference to sceptre-tools repository which is not publicly available.

**Comment by jamesroutley** [comment]
I'm not really sure if we need this section anymore, I don't think we have plans to open source a sceptre-tools repo (which is where the IAM role template+config would be). Since we've made using an IAM role optional I think there's less need for this.

**Comment by theseanything** [comment]
That was my feeling - lets go ahead and remove it.
