### ISSUE TITLE
Integration tests run using Hard Coded AWS account

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#272]
When I attempt to run the integration tests, after adding one I had to modify all the config files to an AWS account I actually have access to.
I don't want to break the IT automation, so did not submit a PR. 
There are two solutions without changing Sceptre:
1. Create an it-vars.yaml from which all the config files pull, so only one location to change when running locally.
2. Change the use of aws-role to profile, and have each user setup that profile with the account they have access to. (This is my preferred solution).

**Comment by theseanything** [comment]
Yup - this is the iam_role config item? This should defo be removed.
