### ISSUE TITLE
No hooks for update-stack-cs

### ISSUE THREAD

**Issue by connorwilliamscr** [cloudreach/sceptre#277]
For SAM stacks, you can only update with `update-stack-cs`, but there are no hooks that yet exist for this command. This would be super useful for writing a custom hook for running the `aws cloudformation package` command which needs to be run every time the Lambda code is updated and needs to be re-deployed.

If you try to use `update-stack`, the following error occurs: `An error occurred (ValidationError) when calling the UpdateStack operation: UpdateStack cannot be used with templates containing Transforms.`

**Comment by connorwilliamscr** [comment]
My apologies, just had a look through pull requests and someone has almost finished this feature! Can close this issue.

**Comment by connorwilliamscr** [comment]
Closed because I thought I saw a pull request that solved this but I was wrong 👎

**Comment by theseanything** [comment]
Ultimately we need to just implement SAM support - see relevant ticket #324.

**Comment by mithun** [comment]
@theseanything actually, we would like to see this feature independent of SAM support. We heavily use `update-stack-cs` instead of `update-stack` and would like to have hooks triggered when using change-sets.

**Comment by ianburrell** [comment]
Should be possible to add hook to the update_with_change_set process. "create_change_set" would probably be the best place, but would be a little confusing.
