### ISSUE TITLE
Improve CLI Documentation

### ISSUE THREAD

**Issue by rmbennett** [cloudreach/sceptre#28]
After chatting to @theseanything 

Please can you improve the documentation so it explains that awesome change set thing because that's awesome if it creates it for you. In general can you improve the CLI documentation to show off the awesome features. 

> update-stack-cs - basically creates a change-set, tells you what's different in the stack, then if you say yes will update the stack...
> it's a kind of safety net

**Comment by jamesroutley** [comment]
Yep good suggestion. I think we can do two things:

- CLI commands show helper text if you run `sceptre <command> --help`. I think in a lot of cases this helper text can be improved.
- We currently don't have a way to export the CLI docstrings into our Sphinx docs (which make up the online docs). We should fix this.

I think this GH Issue should focus on the first, as it will actually add useful information to Sceptre. I'll open a second issue about the second.

**Comment by theseanything** [comment]
Can we open another issue for your first point @jamesroutley? This keep this thread as a disscussion around improving the explanation of update-stack-cs.

**Comment by ngfgrant** [comment]
@theseanything the CLI documentation now seems to be pretty clear on what ```update-stack-cs``` does.

I think there is a wider point about a documentation review/update which I could create another ticket for, have a few ideas about docs. 

What do you think about closing this issue?

**Comment by theseanything** [comment]
I'd like to see the online documentation be more comprehensive about command, rather than just listing them [here](https://sceptre.cloudreach.com/latest/docs/cli.html)... maybe want to wait until new cli comes up to save time refactoring afterwards.

**Comment by ngfgrant** [comment]
@theseanything I am going to close this issue because the documentation as a whole needs redone with v2. We will need to create some new tickets for improved v2 docs which include more detailed user examples.
