### ISSUE TITLE
stack_output resolver does not respect the stack_name config property

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#280]
If a reference is made from one stack to another using the stack_output resolver and the target is using a stack_name property to force the cloudformation stack to a specific name, an error occurs, because the resolver calculates the stack name, instead of looking it up.
This appears non-trivial to fix in Sceptre 1 as there appears to be no way for the resolver to lookup the stack object to query for the name. 
I suggest a documentation note in Sceptre 1, and plan for a fix in Sceptre 2

**Comment by theseanything** [comment]
We have a note in the documentation [here](https://sceptre.cloudreach.com/latest/docs/stack_config.html#stack_name), however it might be worth saying something under the resolver section too. For v1 you need to use stack_output_external, and unfortunately that doesn't allow automatic dependency resolution for `env` commands.

This is something we could look into fixing V2 for sure!
