### ISSUE TITLE
Add Support for Multiple `--var-file` Options

### ISSUE THREAD

**Issue by cboss24** [cloudreach/sceptre#283]
Currently, If I supply multiple `--var-file` options:

`sceptre --var-file=a.yaml --var-file=b.yaml --var-file=c.yaml launch-env api`

Sceptre will silently ignore `a.yaml` and `b.yaml`, while reading in `c.yaml`. This seems like an unnecessary limitation, especially when you consider that Sceptre already supports specifying multiple `--var` options. 

I believe there are quite a few reasons why you would want to do this. Our specific use case is that we would like one set of var-files to represent AWS account specific configs (dev.yaml, sit.yaml, prod.yaml), while also having a set of var-files which characterize how much the sceptre env will cost (tiny.yaml, stress_test.yaml, full.yaml).

One implementation detail to consider is what to do if the same key exists in multiple files. I think an appropriate solution would use the order in which the `--var-file`s were passed in to determine precedence.

**Comment by theseanything** [comment]
Yup, we could look at using the `multiple=True` for the click argument. Need to think about how we'd do order of precedence with same keys/merging of any nested data structures.

**Comment by b-t-g** [comment]
Would it be possible to avoid that `multiple=True` bit? It seems redundant/verbose enough that I feel that it should be avoided if at all possible.

As for value merging, perhaps the default behavior should be to throw an error and then have a few different behaviors? i.e., `--accept-latest` (i.e., if there are collisions, use the last specified file with that variable), `--default=a.yaml` (if there are collisions with a.yaml and another file, accept a.yaml, if there are other collisions, error out), `--concatenate-lists` (if there are conflicting lists in files, concatenate them), `--merge-lists` (if there are conflicting lists in files, concatenate them and remove duplicates). I'm not tied to the names of any behaviors, but let me know what you think.

**Comment by theseanything** [comment]
Sorry I meant [this](http://click.pocoo.org/5/options/#multiple-options)

**Comment by b-t-g** [comment]
Ah yeah, that makes way more sense, I glanced over you saying "for the click argument".

**Comment by cboss24** [comment]
Hm, i hadn't considered merging nested data structures. Have you guys encountered a use case for this? A workaround could be to just perform this merging in the jinja?

If you guys are decided on mergin, I have a couple of questions:
- are we only merging to a certain depth? Or merging all the way to the bottom. 
- do we throw errors if there are type mismatches between overloaded keys?
- do we only want to merge lists? Or also dictionaries?

**Comment by b-t-g** [comment]
@cboss24, I may be a guilty in my "over-optimize all the things" with this issue. Maybe we should just throw an error if there are duplicates, see what the use case for having duplicates is, and then add them accordingly. What do you think, @theseanything?

**Comment by theseanything** [comment]
Hesitant about throwing an error, as its not really an error - it may be desired to "overwrite" a certain set of keys/allows you to set defaults in a lower precedence file. My gut feeling is to initially just merge top level keys. i.e.
``` 
---- var-file 1
key1: parent_value1
key2: parent_value2
```

``` 
---- var-file 2
key2: child_value2
key3: child_value3
```

``` 
---- end result
key1: parent_value1
key2: child_value2
key3: child_value3
```

And have the order of precedence set by order of the flags? (<- this i'm not so sure about)
i.e. `sceptre --var-file lowest --var-file lower --var-file higher --var-file highest  <command>`

**Comment by cboss24** [comment]
I think that order of precedence makes sense. Should I keep the overloaded key check, but instead of throwing an error just write a debug log?
