### ISSUE TITLE
config value being type converted

### ISSUE THREAD

**Issue by eikenb** [cloudreach/sceptre#284]
I have a custom/additional key:value pair in my config.yaml to specify class B network block for a VPC. The yaml is very simple...

    classB: "10.124"

But when I use this in my parameters to my template...

    ClassB: {{environment_config.classB}}

I get an error...

    Invalid type for parameter Parameters[2].ParameterValue, value: 10.124, type: <class 'float'>, valid types: <class 'str'>

I tried yaml syntax to specify the type...

    classB: !!str "10.124"

With no affect.

Is this a bug or am I missing the trick to keep this typed correctly?
Thanks.

**Comment by eikenb** [comment]
After spending a bit more time on this I figured it out. It was due to a lack of quotes in the parameters. That is that parameters line should have been...

    ClassB: "{{environment_config.classB}}"

I figured this out after I just went in and printed out the type of 'classB' from the loaded yaml temlpate and it was a string.

Sorry for the red herring.

**Comment by theseanything** [comment]
No worries!!! Glad you managed to figure it out :)
