### ISSUE TITLE
Bash completion for 2.0

### ISSUE THREAD

**Issue by b-t-g** [cloudreach/sceptre#287]
Inspired by PR #286 

PR #278 changed the format of the commands drastically and so this issue will function both as a description of what needs to be done and then discuss if this is something we want. I seem to recall some of the motivation of the commands was so that we could use "native" bash autocompletion of things that bash already knew how to complete (e.g., file/directory names) but, even with that, would they still be a gain?

@theseanything

**Comment by kifbv** [comment]
Tab completion depends on the shell you're using so I'm talking here about bash but I'm pretty sure e.g. zsh works in a very similar way if not exactly the same.

From the bash man page:
>When word completion is attempted for an argument to a command **for which a completion specification (a compspec) has  been  defined**  using  the  complete builtin (see SHELL BUILTIN COMMANDS below), the programmable completion facilities are invoked.
...
If no compspec is found for the full pathname, an attempt is made to find a compspec for the portion following the final slash. If  those  searches  do not result in a compspec, any compspec defined with the -D option to complete is used as the default.

The default it only completes commands, filenames and variables and the key thing is to define a compsec.

There's usually a package providing specialised ones:
From the Arch Linux Wiki:
>The package bash-completion extends this by adding more specialized tab completions for common commands and their options...

You can try to just source it and see if it works but some functions I'm using in the script might not be standard (i.e. they might have been provided by that bash-completion package):
`mv contrib/sceptre ~/.sceptre.completion`
`source ~/.sceptre.completion`

The compsec can then just be sourced from .bashrc or .bash_profile or etc:
`[[ -f ~/.sceptre.completion ]] && source ~/.sceptre.completion`

**Comment by scanepa** [comment]
By default every click based python program and sceptre is one, can bash complete. Just following click documentation (http://click.pocoo.org/5/bashcomplete/)  I was able to create my completion. 
I did this:```
_SCEPTRE_COMPLETE=source /home/canepas/tempvenv/.venv/bin/sceptre | sudo tee /etc/bash_completion.d/sceptre.sh```
Then I reloaded my bash.

Now I have to find an easy solution for zsh as I'm not using bash.

**Comment by ngfgrant** [comment]
As @scanepa mentioned you can do `eval "$(_SCEPTRE_COMPLETE=source sceptre)"` and click will autocomplete subcommands and parameters. I will add this to the docs. It works pretty well. Closing for now, we can decide later if we need something more sophisticated.
