### ISSUE TITLE
Unclear How to Access User Variables in Templating

### ISSUE THREAD

**Issue by cboss24** [cloudreach/sceptre#288]
Currently if i specify user variables as command line options:

`sceptre --var a=1 --var b=2 <command>`

The templating for both the environment and stack configs will receive the following dictionary: 

`{'var': {'user_variables': {'a': 1, 'b': 2}}}`

Is this expected behavior? Does this mean I can no longer access variables using `var.a`, instead now I need to write `var.user_variables.a`? If so then the documentation needs to be updated to reflect this.

**Comment by theseanything** [comment]
Nope thats a bug. Good catch - it should be `var.a`. Needs a fix and tests added.

**Comment by cboss24** [comment]
Okay PR incoming.
