### ISSUE TITLE
How can I update stack with new AMI?

### ISSUE THREAD

**Issue by bitmatix** [cloudreach/sceptre#292]
In our CI/CD we have a job which builds and pushes new AMI images if the code changes. Now we want to sceptre to launch/update the stack, which contains an "Auto Scaling Group" with the given AMI?

**Comment by theseanything** [comment]
Ideally, you'd have the a CloudFormation [parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) in your template for the AMI ID used in your [launch configuration resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html). If have a your AMI ID from your build step, you could pass it into the stack config via [the Environment Variable Resolver](https://sceptre.cloudreach.com/latest/docs/resolvers.html).
```
---- <stack_config>.yaml ----
template_path: path/to/file
parameters:
    AMI_ID: !environment_variable AMI_ID_VARIABLE
...etc...
``` 
 Or you could use a [custom Resolver](https://sceptre.cloudreach.com/latest/docs/resolvers.html) to query AWS API to get the latest AMI ID for a particular name..
```
---- <stack_config>.yaml ----
template_path: path/to/file
parameters:
    AMI_ID: !ami_id <name_of_ami>
...etc...
``` 
Hope that helps!!
