### ISSUE TITLE
Using SSM Parameters as parameter resolvers

### ISSUE THREAD

**Issue by lukeplausin** [cloudreach/sceptre#293]
I think it would be really useful to have a built-in resolver which could retrieve a parameter from SSM and use it as input for the template 👍 🤞

**Comment by theseanything** [comment]
Sure we are making it easier to share resolvers with #205 and release in v2.0. For now you can create a [custom resolver](https://sceptre.cloudreach.com/latest/docs/resolvers.html#custom_resolvers) to query the AWS API.
