### ISSUE TITLE
Explicit dependencies not honoured

### ISSUE THREAD

**Issue by DaveTaddei-CR** [cloudreach/sceptre#298]
Sceptre uses implicit dependencies between stacks (ie when a value is read from another stack a dependency on that stack is created).  It also provides a mechanism for explicit declaration of dependencies however the two mechanisms are in conflict resulting in failed stack deployments.

To reproduce:
* create configuration for stacks A and B
* read the output name from stack A as a parameter in stack B
* declare an explicit dependency on stack A
* deploy stacks

DONE WHEN:
* the explicit dependencies override the implicit dependencies

**Comment by achidlow** [comment]
Just encountered this issue as well. I've tracked it down to here: https://github.com/cloudreach/sceptre/blob/v1/sceptre/config.py#L193
Where calling `self.update(config)` doesn't merge the `dependencies` lists.

Looks like it might be present in master too (which I gather is v2 at this stage): 
https://github.com/cloudreach/sceptre/blob/master/sceptre/config_reader.py#L178

**Comment by ngfgrant** [comment]
@achidlow - if you have that patch still available could you submit it as a PR? If you need help with this just let me know and I'll be happy to help.
