### ISSUE TITLE
No warning when stack contains conflicting bucket names

### ISSUE THREAD

**Issue by DaveTaddei-CR** [cloudreach/sceptre#303]
Sceptre requires an S3 bucket to store templates as part of deploying a stack.  If the stack happens to contain a bucket of the same name sceptre will attempt and then fail to create the bucket.  The error presented to the user is "cannot create bucket as it already exists".

As part of processing the stack sceptre should ensure the template bucket name is not in conflict with anything in the stack and generate an appropriate warning.

DONE WHEN:
* The user is given a specific warning that the sceptre template bucket name is the same as buckets defined in the stack

**Comment by ngfgrant** [comment]
Thanks for the ticket. I will pick this up and look to see if we can improve the error messages.

**Comment by theseanything** [comment]
Just to clarify the error is from CloudFormation when creating the stack? 

Sceptre isn't aware of the resources within a stack i.e. doesn't parse templates, so at the moment we wouldn't be able to implement this sort of error handling. I feel the value-add of having a more specific error isn't worth the amount of work required. Also this only captures a small subset of bucket naming conflict errors - for example you could have buckets created in hooks, resolvers, other scripts which could also conflict.

**Comment by DaveTaddei-CR** [comment]
Correct the error is from cloud formation because the sceptre template bucket ended up with the same name as a bucket defined in the stack. The error however was not clear as it simply said the bucket already existed. It would be helpful if the sceptre bucket name was checked against the template although I do accept it may not cover all use cases (hooks etc)

**Comment by ngfgrant** [comment]
We should make a note about this in the documentation. The effort to resolve outweighs the benefit in this case. Will make explicit in the docs.
