### ISSUE TITLE
Explicit setting of Environment dependencies

### ISSUE THREAD

**Issue by JuanCanham** [cloudreach/sceptre#304]
I would like to be able to tell sceptre that a certain sub environment must be launched/updated before another.

The 2 use cases for this are:

* Multi-region deployment (e.g you have you IAM in one region and want to update an env containing all your regional resources (e.g lambda functions))
* Cross-Account deployments (e.g you have your cloudwatch Events Rules in one account, but need to add permissions in the target account first

**Comment by ngfgrant** [comment]
@DaveTaddei-CR might be able to give you some thoughts on how to do this?

**Comment by ngfgrant** [comment]
This will be properly dealt with as part of #422 in version 2.
