### ISSUE TITLE
How to pass a variable or resolver as an argument to a hook?

### ISSUE THREAD

**Issue by sodle** [cloudreach/sceptre#307]
I'm trying to use one of the outputs of my CloudFormation template as a parameter to a !cmd hook - e.g.

```
hooks:
  after_create:
    - !cmd "echo {{ value of cloudformation output }}"
```

Is there a way to do this?

**Comment by ngfgrant** [comment]
Hey @sodle - thanks for getting in touch. The best place to ask a question is over at StackOverflow. Could you repost your question over there? I will close this issue. 

Thanks,
Niall

**Comment by sodle** [comment]
OK, I'm asking now. Is there a tag I should use? `sceptre` doesn't seem to exist.
