### ISSUE TITLE
Investigate automatic documentation of CLI in Sphinx

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#31]
Our Python API is automatically documented in our online documentation using Sphinx. Our CLI API is currently not automatically documented. We should investigate how difficult it would be to add automatic Sphinx docs for our CLI.

**Comment by jamesroutley** [comment]
So it [isn't currently possible](https://github.com/pallets/click/issues/381) to get Click to automatically generate web documentation. A couple of hacks are suggested, but all of them are a bit gross. I wonder if the best thing to do is to list the commands and mention that more information about each can be found by running:

```
sceptre <command> --help
```

Thoughts @seanrankine

**Comment by theseanything** [comment]
I think suggesting to use `sceptre <command> --help` is good for an easy reference, but I don't think its a good substitute for in-depth documentation about a command, with examples etc... So yeah its a pain to not automatically get documentation, but we just need to make sure its update to date - making sure we check docs in PRs, improving testing so we notice changes in functionality etc...

**Comment by jamesroutley** [comment]
Is difficult
