### ISSUE TITLE
access boto session from .py templates

### ISSUE THREAD

**Issue by bgdnlp** [cloudreach/sceptre#315]
When running sceptre with a Python template, is it possible to use the boto3 session set up by sceptre to execute boto3 code inside the template?

Use case:
Got a function called split_net_across_zones() that is defined in an awslib module. It calls the ec2.describe_availability_zones() in boto3 to get a list of AZs.

Then there's a Python script that uses Troposphere to generate a template which takes a network CIDR and splits it into several (ex. 4) subnets spread across AZs. It imports awslib above and calls split_net_across_zones().

The Python script is passed to sceptre as a template. But it fails because when it gets to the part where it lists availability zones in the region it doesn't have any credentials available (no default profile, no role attached to instance, no keys in environment variables, etc.)

Would be nice if it were possible to use the same credentials (profile in my case) set in sceptre config. Maybe set boto3.setup_default_session() instead of or in addition to ConnectionManager?

**Comment by theseanything** [comment]
Hey @bgdnlp! So you could cover this functionality with a custom resolver and pass the output to your template via sceptre_user_data. 

Templates and logic around rendering templates should be focused at a resource level - e.g. making multiple subnets, making multiple instances, adding internet gateways. The properties of those resources then should be defined in Parameters or Sceptre User Data within the stack_config.

**Comment by bgdnlp** [comment]
Thank you Sean, makes sense.

It looks to me like all resolvers (and hooks) are imported, but a resolver will only be called if referenced in a stack config. Right? In which case, seeing as stack config cascading is going to be deprecated, will we be able to set up a resolver that will be called for all stacks?

Basically what I'm looking for is to have access to either the environment settings (i.e. profile/role/region) or to the boto3 Session (connection_manager) from any stack, without having to explicitly add it to every stack.

**Comment by theseanything** [comment]
Ah so at the moment, unfortunately there isn't a way to use a single resolver across multiple configs - (unless you use a cascading config). But we are hoping to bring out better common config support in v2 (and we need to make sure we support Resolvers).
