### ISSUE TITLE
Sceptre docs missing an html <title> and icon

### ISSUE THREAD

**Issue by johnrobisoncr** [cloudreach/sceptre#316]
The Sceptre docs website doesn't have any html <title> or icon, which is annoying to find the right tab when you've got a bunch of tabs open.

<img width="458" alt="screen shot 2018-02-09 at 2 34 02 pm" src="https://user-images.githubusercontent.com/28732995/36046258-4fab3622-0da6-11e8-98db-58fdc4daff99.png">

Perhaps a title and icon could be added?

**Comment by theseanything** [comment]
@johnrobisoncr Yup!

**Comment by ngfgrant** [comment]
@johnrobisoncr 

This should be pretty straightforward. probably some "FrontMatter" (https://jekyllrb.com/docs/frontmatter/) and I have attached the Sceptre icon here. Would you be willing to sort this?

![sceptre-icon](https://user-images.githubusercontent.com/6362273/36435714-5249d2e6-165a-11e8-9e3e-41a9b4b0eaf1.png)

**Comment by johnrobisoncr** [comment]
@ngfgrant Sure. What is the desired html title? "Sceptre"?

**Comment by ngfgrant** [comment]
Yep let's use the format: `Page Title  | Sceptre`
