### ISSUE TITLE
Boto version restriction is getting restrictive

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#322]
The  restriction on Boto < 1.5.0 is starting to get really annoying due  to Python's lack of isolated dependencies between versions. We want to  use new versions of botocore in other projects as they have support for  profile better role assumption (source_profile in ~/.aws/config stuff), but we can't make other projects require new boto versions as their installation then conflicts with Sceptre.

**Comment by ngfgrant** [comment]
Hi @akdor1154 are you using virtual environments?

**Comment by akdor1154** [comment]
Nope! I will often set them up for when I'm writing my own python projects and don't want to disturb my system packages, but the way I use sceptre on my local machine is more like a system package. If I were using sceptre from git master it'd be reasonable to expect me to set up a virtual env, but I don't think it should be necessary to just install the latest stable version from pypi.


I don't just want sceptre to limit what system packages I use, I also in particular want sceptre to work with newer botocores as they often transparently update the credential methods supported (i.e. the recent assume role stuff) and it's frustrating to see (e.g.) awscli gain these methods automatically and sceptre lack them because of an a version restriction.
