### ISSUE TITLE
launch-env - 'no such command'

### ISSUE THREAD

**Issue by avatarworf** [cloudreach/sceptre#327]
Since the new release of v1.3.3, the launch-env command isn't found

+ sceptre --var-file=variables.yaml launch-env governance/eu-west-1
Usage: sceptre [OPTIONS] COMMAND [ARGS]...

Error: No such command "launch-env".

**Comment by stig** [comment]
# Table of Contents



Yeah, I found the same. I'm a bit disappointed to have CLI compatibility broken in a patch release. I have a subset of config like this (showing only files):

    config/dev/config.yaml
    config/dev/eu/eu-central-1/foo.yaml
    config/dev/eu/eu-central-1/bar.yaml
    config/dev/eu/eu-central-1/quux.yaml
    config/dev/us/us-east-2/foo.yaml
    config/dev/us/us-east-2/bar.yaml
    config/dev/us/us-east-2/quux.yaml

I used to do \`sceptre launch-env dev\` to launch both us and eu stacks at the same time, and \`sceptre launch-stack dev/eu/eu-central-1 foo\` if I wanted to launch just a single stack.  How do I do the equivalent of these commands now? It doesn't seem to be as easy as `s/launch-(env|stack)/launch/`, and the error messages aren't incredibly helpful:

    > sceptre launch dev
    list object has no element 2
    > sceptre launch dev/eu
    list object has no element 2
    > sceptre launch dev/eu/eu-central-1
    list object has no element 2
    > sceptre launch config/dev/eu/eu-central-1/
    Environment not found for 'config/dev/eu/eu-central-1/'
    > sceptre launch config/dev/eu/eu-central-1/bar.yaml 
    Config file not found for 'config/dev/eu/eu-central-1/bar.yaml'
    > sceptre launch config/dev/eu/eu-central-1/bar
    Environment not found for 'config/dev/eu/eu-central-1/bar'
    > sceptre launch config/dev/config.yaml 
    Config file not found for 'config/dev/config.yaml'

**Comment by ngfgrant** [comment]
Hi folks - apologies this was an error on our part. This has been resolved and everything should work as normal in version 1.3.4 which is now live on PyPi.

**Comment by Kumar1325** [comment]
Hi ngffrant, the `sceptre launch-dev` is not working in version 2.3.0

**Comment by ngfgrant** [comment]
Hey the cli changed between v1 and v2. This issue was relating to v1

**Comment by campanellaf** [comment]
> Hey the cli changed between v1 and v2. This issue was relating to v1

What is the equivalent command for "launch-env" in v2?

**Comment by craighurley** [comment]
drum roll... `launch`

https://sceptre.cloudreach.com/2.3.0/docs/cli.html#sceptre-launch

:)

**Comment by campanellaf** [comment]
> drum roll... `launch`
> 
> https://sceptre.cloudreach.com/2.3.0/docs/cli.html#sceptre-launch
> 
> :)

Ye well not that funny.. The entire concept of environment has been removed and replaced with this stack group thing. Also, just saying "launch", or pointing to that docs is pretty much useless as they are rubbish - no examples and no reference on how to replace a launch-env command from V1 (not even in the V1 to V2 migration guide!

**Comment by craighurley** [comment]
@campanellaf , I'm not a maintainer of this project and IMO the docs are fine in this case:

> Launch a Stack or StackGroup for a given config PATH.

`sceptre launch [OPTIONS] PATH`

The command does exactly what it says it does and what I expect it to do.

`sceptre launch path/to/topleveldir`

... will launch all the stacks in the `topleveldir` (stackgroup) or alternatively, if I want to launch a specific stack, run:

`sceptre launch path/to/topleveldir/specificstack`

If you are looking for help, next time please explain what you tried, what error you got or provide any other useful information.  Random strangers on the internet are here to spoon feed you.

If you have strong feelings about the quality of an open-source tool or it's documentation, feel free to spend some of your time helping improve it.
