### ISSUE TITLE
diff command still in API docs

### ISSUE THREAD

**Issue by JGjorgji** [cloudreach/sceptre#328]
I see it was removed recently, i looking at the API docs trying to make it work when i noticed that in the changelog.

https://sceptre.cloudreach.com/latest/docs/api/sceptre.html?highlight=diff#sceptre.stack.Stack.diff

**Comment by ngfgrant** [comment]
Thanks @JGjorgji

**Comment by JGjorgji** [comment]
Can i ask by the way why was this removed? I'm trying to find out when a stack has changed and generated a change set and without this i don't see a way to easily check.

**Comment by niallgrantcloudreach** [comment]
Looks like https://github.com/cloudreach/sceptre/pull/225 gives some insight to this. Hope that the explanation given makes sense?

**Comment by ngfgrant** [comment]
Looks like #225 gives some insight to this. Hope that the explanation given makes sense?

**Comment by JGjorgji** [comment]
Yeah, that explains it. I'm using a workaround now so it's fine.

**Comment by ngfgrant** [comment]
@JGjorgji would you like to pick this up and remove the diff reference from the docs?

**Comment by jjm** [comment]
@ngfgrant I'm happy to do a PR for this, I need to understand both Sceptre and CloudFormation.

**Comment by ngfgrant** [comment]
@jjm I think this is just a docs update.

**Comment by medwig** [comment]
N.B. `sceptre diff` is still listed in the docs: https://sceptre.cloudreach.com/latest/docs/cli.html

**Comment by ngfgrant** [comment]
Closing as the update docs have now been deployed successfully.
