### ISSUE TITLE
stack.py fails to pass the aws-profile to the connection manager

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#330]
As part of the update somehow the ConnectionManager is not getting from the stack.py during creation the aws_profile from the config object used by the stack.

Submitting PR to fix.

**Comment by nmyster** [comment]
@oazmon How's that PR coming along? 😄  Are you able to provide steps to reproduce the issue?

**Comment by oazmon** [comment]
@nmyster ^^^^^
