### ISSUE TITLE
Question about using Environment underscore methods, e.g. _get_available_stacks()

### ISSUE THREAD

**Issue by samkeen** [cloudreach/sceptre#34]
Sorry, not necessarily an *issue*, but I didn't see another medium to ask questions (IRC, Slack, ...)

When using Sceptre as a Python Module, the [docs](http://sceptre.cloudreach.com/docs/python_module.html) state there should be an attribute such as:

```python
env.available_stacks
```
If I attempt that I get:
```
Traceback (most recent call last):
  File "/Users/sam/Projects/sceptre-example/test.py", line 11, in <module>
    env.available_stacks
AttributeError: 'Environment' object has no attribute 'available_stacks'
```

I do see underscore methods and one of those being `_get_available_stacks()`.  If I use that (`env._get_available_stacks()`), I get the expected results.

The question is, **should I be using the underscore method of Environment directly?**  Due to the underscore, I was presuming you are indicating they are private methods.

thanks in advance,
Sam

**Comment by theseanything** [comment]
Hi Sam! No worries, feel free to ask questions. You have actually pointed out an issue - the docs need to be updated. Sorry about that, but thanks for pointing that out!  

`available_stacks` is no longer a attribute of for Environment. You can now access stacks via a dictionary stored as the `stacks` attribute`.

So for example:
```
env.stacks["vpc"]
```
or to see all available stacks
```
env.stacks.keys() 
```

Note this attribute is only available for "leaf" levels stacks.
Hope that helps :)

**Comment by samkeen** [comment]
that makes total sense,
thanks for the clarification.
