### ISSUE TITLE
before/after hooks run regardless of stack results

### ISSUE THREAD

**Issue by JohnVonNeumann** [cloudreach/sceptre#358]
Hey there, so atm I'm trying to use the hooks pretty extensively to automate some non-aws related tasks that are required for the AWS stuff. And I've noticed that regardless of the results of the CF actions, the hooks run, for example:

If I run a delete-stack operation with hooks setup that specify some after-delete actions, even if the delete-stack operation fails, the after-delete actions still run, which can be pretty problematic. I guess really the thing is shooting for idempotency.

**Comment by ngfgrant** [comment]
Hey @JohnVonNeumann 

Would you be able to share some code examples of what you are trying to achieve. Could you wrap your post delete operations in a conditional statement that checks against output from `delete-stack`?

**Comment by nmyster** [comment]
Looks like working with the returned status would be good here but looking at the code (if this is the correct place)... 

```try:
            status = self._wait_for_completion()
        except StackDoesNotExistError:
            status = StackStatus.COMPLETE
        except botocore.exceptions.ClientError as error:
            if error.response["Error"]["Message"].endswith("does not exist"):
                status = StackStatus.COMPLETE
            else:
                raise
        self.logger.info("%s - delete %s", self.name, status)
        return status```

If the stack doesn't exist, the delete is considered complete - this could maybe be a specific error. Also, the final `raise` does not seem to provide a specific exception type so this could be improved.

Finally, looking at the `return status` line - In the current state of things, this will only ever return successful or nothing at all as the value of status is either set to StackStatus.COMPLETE or the response of the stack delete if there was no errors.

**Comment by ngfgrant** [comment]
@JohnVonNeumann did @nmyster suggestion work for you?

**Comment by ngfgrant** [comment]
@JohnVonNeumann any luck with this or can I close it out?
