### ISSUE TITLE
launch-env with order

### ISSUE THREAD

**Issue by ismFerDev** [cloudreach/sceptre#36]
Hi,

We have some templates that dependes to others, example:
config
      dev
         config.yaml
         instance.yml
         eni.yaml

We need launch eni before instance, how can I guarantee that?

**Comment by jamesroutley** [comment]
Hello - there are two ways of doing this:

1. If `instance` contains a [`stack_output`](http://sceptre.cloudreach.com/docs/stack_config.html#stack-output) resolver which points to an output from `eni`, `eni` will automatically be launched first.
2. You can add an [explicit dependency](http://sceptre.cloudreach.com/docs/stack_config.html#dependencies), which specifies that `instance` depends on `eni`, and `eni` should be launched first:

```
# instance.yaml
---
dependencies:
  - eni
...
```

**Comment by ismFerDev** [comment]
👍 great
