### ISSUE TITLE
Is the projet still maintained?

### ISSUE THREAD

**Issue by jerep6** [cloudreach/sceptre#361]
Hi,

Given the number of pull requests and issues unanswered, I wonder if the project is still maintained.
Moreover, there is no commit since 2 months.

Do you have more information?

**Comment by ngfgrant** [comment]
Hi @jerep6 

In short yes, the project is still maintained. 

Like most projects there can be times where maintainers are able to put a lot of time into a project and times where they cannot. More recently work has focused me elsewhere. We've just come to the end of a busy period and it looks like I will be able to focus again on Sceptre. 

I would actively encourage you to pick up a issue and contribute. Hopefully, the contributor guide is a good start to help you If you need help with this; and of course I am here to support if you have any questions. 

Thanks for the question and I look forward to getting you involved with the community! 

Cheers,
Niall
