### ISSUE TITLE
Managing values with KMS

### ISSUE THREAD

**Issue by zaro0508** [cloudreach/sceptre#368]
It would be nice to be able to retrieve values, especially secrets, from AWS KMS and be able to reference it as sceptre variables.  I'm not sure of the best way to implement this but it looks like it might be possible by adding a sceptre resolver?

**Comment by et304383** [comment]
I accomplished this by adding a custom SSM resolver.

resolvers/ssm_resolver.py:

```
from sceptre.resolvers import Resolver
import boto3


class SSMResolver(Resolver):

    def __init__(self, *args, **kwargs):
        super(SSMResolver, self).__init__(*args, **kwargs)

    def resolve(self):
        """
        resolve is the method called by Sceptre. It should carry out the work
        intended by this resolver. It should return a string to become the
        final value.

        self.argument is available from the base class and contains the
        argument defined in the sceptre config file (see below)

        The following attributes may be available from the base class:
        self.stack_config  (A dict of data from <stack_name>.yaml)
        self.environment_config  (A dict of data from config.yaml)
        self.connection_manager (A connection_manager)
        """
        ssm_client = boto3.client('ssm')

        return ssm_client.get_parameter(
            Name=self.argument, WithDecryption=True
        )['Parameter']['Value']
```

Then in your stack config:

```
parameters:                                                                                                                                                          
  MasterUserPassword: !ssm_resolver <SSM parameter name goes here>
```

**Comment by zaro0508** [comment]
Thanks.  How does boto establishes a connection to aws in this resolver?  I mean does it use the profile and region that you would pass into scepter?  I think it would make sense to make something like this one of the included resolvers with sceptre.

**Comment by et304383** [comment]
I don't rely on profiles.  I use aws-runas to set temporary credentials in my shell given I use MFA and don't want to be prompted each time:

https://github.com/vancluever/aws-runas

**Comment by zaro0508** [comment]
Ahh, this won't work for us.  We want to run in our CI system but thanks for sharing.

**Comment by et304383** [comment]
Your CI system can easily get temporary credentials via an assume role call.  Look into the command

```
aws sts assume-role
```

If you need to use the role of your CI system, just export AWS_PROFILE=<role name>

There are plenty of ways to use profiles without passing in arguments when using boto3.

http://boto3.readthedocs.io/en/latest/guide/configuration.html

**Comment by cboss24** [comment]
Just a note, resolvers/hooks have access to `self.connection_manager`. This is a boto3 client that has been wrapped to be threadsafe. It is initialized with the values from `iam_role`, `profile`, and `region` from your config.yaml

So if you want a boto3 client identical to the one launching/deleting your stacks, use self.connection_manager. 

Example usage:
```
self.connection_manager.call(
    "ec2", 
    "detach_network_interface", 
    kwargs={
        "AttachmentId": attachment_id,
        "Force": True
    })
```
