### ISSUE TITLE
The flag --var-file can't be used multiple times

### ISSUE THREAD

**Issue by edubxb** [cloudreach/sceptre#369]
The flag `--var-file`, according to the documentation, can be used multiple times, but in the [current version available in pip 1.3.4](https://pypi.org/project/sceptre/1.3.4/) doesn't possible.

Seems that exists a regression for the fix that closed this issue https://github.com/cloudreach/sceptre/issues/283.

Also, the current pip version is 1.3.4, but this version "doesn't exists" in the repo master branch:

https://github.com/cloudreach/sceptre/blob/master/sceptre/__init__.py#L8

Seems that the code version in the repo is not the same available in pip, after looking at the existing code I found that the `--var-file` option has the click attribute `multiple=True`:

https://github.com/cloudreach/sceptre/blob/master/sceptre/cli/__init__.py#L44

**Comment by edubxb** [comment]
Thanks for taking care of this.

Any estimation of when will be fixed?

**Comment by niallgrantcloudreach** [comment]
I’ll aim to get this merged into v1 branch tomorrow. Release might be a little while yet but nothing stopping you from using latest v1 branch.

**Comment by edubxb** [comment]
Thanks a lot!

**Comment by edubxb** [comment]
Hi, any updates about the status of this issue?

Thanks!

**Comment by niallgrantcloudreach** [comment]
Hi working on “picking” this across. although it looks like the implementation of this relied on v2 chanages. Might take a little longer to modify for v1.

**Comment by edubxb** [comment]
Ok, thanks for the update!

**Comment by edubxb** [comment]
Will be this issue finally addressed to get it solved in the v1? Thanks!

**Comment by ngfgrant** [comment]
Hi all,

So the original commit was made for v2 and multiple var files will work in v2, although the timing and docs were confusing. I'd be happy to accept a PR for this for a v1 release, however, I will not be putting effort into this for v1 myself. 

Closing for now.

**Comment by edubxb** [comment]
We will probably migrate to v2.
