### ISSUE TITLE
Sceptre init template

### ISSUE THREAD

**Issue by alytle** [cloudreach/sceptre#376]
I find myself often needing to create new templates, then the configuration files for those templates within each of my environments. I though it would save time to add a `template` sub-command to the `sceptre init` group.

I've cut a PR with the suggestion, and it seems to work pretty well in my testing. To use, you run:

`sceptre init template my_template.yaml --env dev --env prod` - this will create a new (empty) YAML file called my_template.yaml in `templates/` and also add an appropriate config file in the specified envrionments.

The --env flag is optional, but if you forget it you can just run the command again:

`sceptre init template my_template.yaml`  # forgot my env 
`sceptre init template my_template.yaml --env dev` # sees the template already exists and just adds the env config

In terms of improvements, I thought it might be neat to allow the auto-generated template file to also come from some boilerplate file (template of a template?), just to save a bit more time (AWSTemplateFormatVersion: '2010-09-09'\nDescription: ""..., etc)

With respect to the v1 or v2 question, this was built on top of the 1.3.3 code base. I hadn't realized you were working on a v2 branch at the time, so I'm not sure if this is redundant on that branch yet.

Thoughts?

PR: https://github.com/cloudreach/sceptre/pull/367

**Comment by ngfgrant** [comment]
Hi @alytle 

Thanks for the PR. This sort of thing might fit in further down the line with an idea we have for creating a `sceptre solution gallery`. As it stands, this sort of thing can be achieved using the built in `touch` command (http://www.linfo.org/touch.html) and so I am going to close this issue for now and also close the PR.

We can review this in the (hopefully) near future.
