### ISSUE TITLE
Run multiple stacks in one go?

### ISSUE THREAD

**Issue by jeshan** [cloudreach/sceptre#392]
Is it possible to run multiple stacks in one go?
I'm looking for something like:
`sceptre launch-stack dev stack1 stack2`

It would be nice to have this or something that launches the first stack in the background and I can launch the second just after. Can this be done at all with the CLI/api?

**Comment by jeshan** [comment]
I know about "sub-environments" like:

* `staging/config.yaml`
* `staging/group1/stack.yaml`
* `staging/group2/another-stack.yaml`

Is that the only way to go?

**Comment by JuanCanham** [comment]
environments is the recommended way to go, currently you cant provide multiple stacks. can you describe the setup that wouldn't work with

* `staging/group1/stack.yaml`
* `staging/group1/stack2.yaml`

`sceptre launch-env staging/group1`

It might be possible to work into 2.0, but it might also break any command that requires 4 arguments, so the more detail you can provide the better.

**Comment by jeshan** [comment]
understood. No it will work as you describe. It's just that "environment" seems like a misnomer for this use case.
