### ISSUE TITLE
Allow passing of AWS profile

### ISSUE THREAD

**Issue by geeknam** [cloudreach/sceptre#40]
At the moment, sceptre assumes that the profile is `default` if `iam_role` is not provided:

https://github.com/cloudreach/sceptre/blob/master/sceptre/connection_manager.py#L98

It would be good to be able to provide `profile` key in `config.yaml` in each env which then gets passed on to ` boto3.session.Session` as an argument:

http://boto3.readthedocs.io/en/latest/reference/core/session.html

**Comment by geeknam** [comment]
Totally unrelated: how does `sceptre` deal with nested stacks (AWS::CloudFormation::Stack)?

**Comment by jamesroutley** [comment]
Hey - we've purposefully not added a profile key to config.yaml. Sceptre was designed to be easy to use by multiple people working on the same Sceptre repo. As profile names tend to be personal, we think they shouldn't be stored in version control. If you'd like to use a particular profile, you can set the AWS_PROFILE environment variable.

**Comment by jamesroutley** [comment]
Re: nested stacks, sceptre doesn't recurse through them when reporting events, as you mention. We tend not to use them - we like to keep our stacks independent from one another where possible, and Sceptre's `stack_output` resolver allows us to easily create lots of resources in one go without having to worry about a change to a stack affecting unrelated stacks.

**Comment by jamesroutley** [comment]
Hope this helps - I'm writing on my phone so apologies for typos. Let me know if you have further questions

**Comment by geeknam** [comment]
@jamesroutley thanks for the answers and env var tip. I do understand the use case of keeping the stacks independent from one another.
