### ISSUE TITLE
Question - ETA for the latest release?

### ISSUE THREAD

**Issue by chhibber** [cloudreach/sceptre#407]
I am looking to pull in a number of fixes,  is there an ETA to release the next version of sceptre?

Thanks
Sono

**Comment by niallgrantcloudreach** [comment]
Hey @chhibber - there are two streams of work going on right now. One stream is for v1.3.5 and one is for v2. 

I am hoping that we will be in a position to get v2 out within the next 2 weeks. This is the main focus. 

For version 1 depending on how things for v2 are going we could also get a release out in the next couple of weeks. 

Which features are you needing to use and I could help with instructions about how you could use those features now, without waiting for a release?
