### ISSUE TITLE
Is cascading environment config being deprecated?

### ISSUE THREAD

**Issue by zaro0508** [cloudreach/sceptre#416]
I noticed the docs says "Cascading stack config is being deprecated, and should not be used".  I also noticed discussion in issue #256 around general redesign of configs.  It wasn't clear to me whether the redesign includes environment configs so I'm wondering if cascading environment configs will be deprecated as well?

**Comment by ngfgrant** [comment]
Hi @zaro0508 

I think the previous maintainers had wanted to deprecate cascading stack config. However, after discussion, it seems like the consensus is to keep cascading config for both environments and stacks. Hope this helps to clear things up. I will be updating the docs for the upcoming v2 release.
