### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by 1oglop1** [cloudreach/sceptre#417]
This issue will serve as an aggregator for what's missing in documentation.
Once #389 and #412  is resolved, it will be good to split this into separate issues.

**Issue:** Sceptre documentation silently assumes prior `CloudFormation` knowledge. 
**Issue:** Command description is somewhat vague - it's very unclear what `execute` does.
```
$ sceptre execute-change-set --help
Usage: sceptre execute-change-set [OPTIONS] ENVIRONMENT STACK CHANGE_SET_NAME

  Executes the change set.

  Executes ENVIRONMENT/STACK's change set with name CHANGE_SET_NAME.
```

Action points:

- [ ] Write down information about configuration lifecycle
- [ ] Provide necessary knowledge and links with CF commands in documentation but also CLI

**Comment by ngfgrant** [comment]
Hey @1oglop1 

There are a couple of issues (#306, #372) that already exist to collate and track feedback relating to documentation/user guides, so I am reluctant to start another. 

More than happy to have issues that deal with specific shortcomings such as #262. 

Regarding the `execute-change-set` command. Sceptre effectively acts as a wrapper around boto3. As such, `execute-change-set` is an AWS command and more information can be found here: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/execute-change-set.html

**Comment by 1oglop1** [comment]
@ngfgrant 
I somehow missed #306, I guess that's more than appropriate place for this. Feel free to move the content from this one there.

I also found nice example how we should provide the necessary link when we wrap original commands without change.
Look at this example:
https://elasticsearch-py.readthedocs.io/en/master/api.html#snapshot

Explanation is pretty brief (though effortless) and contains hyperlink to original API documentation.
This should provide necessary biding between sceptre and it's dependencies.

![image](https://user-images.githubusercontent.com/7480694/41896021-d374cb1a-7923-11e8-829e-a179e032b533.png)

**Comment by ngfgrant** [comment]
Closing as #306 deals with the aggregation of documentation tasks for v2.
