### ISSUE TITLE
Refactor Stack Dependency Handling

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#422]
# CONTEXT

There are a number of issues open regarding dependencies:

- #298 
- #304
- #360 
- #159
- #302 
- #38 

There are a few legitimate limitations with stack dependency handling which this refactor will deal with but more importantly this refactor will ensure that regardless of launch order, explicit and implicit dependenies will be resolved or a useful error thrown. 

Whilst I don't expect there to be an negative consequences for existing stack configurations, there maybe edge cases that break with a more robust dependency handler in place. As such, I would like to get this out as part of 2.0 so that there are no nasty surpises later in 2.x. 

## Benefits:

- More robust stack dependency handling, regardless of depth of heirarchy or across environments 
- Improved error messages to assist with debugging. 
- Easier to add convenience methods for end-user e.g. print fully resolved dependency graph to get full visibility of dependency graph.
- Cleaner codebase. 
- No changes to the way end-users define their dependencies 
- Once stack dependency handling is modularised it should be easier to write extensive tests against.

# DONE WHEN 

The tasks involved include: 

- move current code that deals with stack dependencies to it's own Python module 
- create a sensible API for that module 
- swap out previous implementations with more robust graphing library, where appropriate.
- offer a way to create and manage stack dependency graphs. 
- implement a way to "build" a full dependency graph and a way to "execute" the reverse grah. 
- A directed graph would be able to identify circular references durng the "build" part of the graph and provide meaningful error messages to end-user. 

# Discussion

Please give any feedback and thoughts below about anything you'd like to see addressed when we are improving stack dependency handling.

**Comment by pilgrim2go** [comment]
really really need this feature
+1

**Comment by ngfgrant** [comment]
Closed as https://github.com/cloudreach/sceptre/pull/509 resolved this issue and the associated issues.
