### ISSUE TITLE
Feature Request: unconditional "after" hook

### ISSUE THREAD

**Issue by mattvonrocketstein** [cloudreach/sceptre#423]
For sceptre version 1.3.4, `after_update` hooks do not fire if stack changes were not performed and execution simply halts with

`[2018-07-03 21:31:15] - sceptre.stack - env/stack_name - No updates to perform.`

As long as there is no actual error, there are many cases when a hook is useful to fire off even if the stack itself is not updated. (Examples of this might include say a slack notifier saying changes were attempted, or a command hook that calls server-provisioning automation that uses `!stack_output` stuff as input)

I don't necessarily think the situation with `after_update` should be considered a bug though, because differentiating between generic "afterwards" vs "after changes" is also potentially useful.  How do people feel about a new hook just named `after` to cover this?

**Comment by cboss24** [comment]
Potential copy of 358.

**Comment by ngfgrant** [comment]
Yep agreed that this is the same as #219. Something we will do. Closing this issue for now in favour of the discussion that has already happened in #219.
