### ISSUE TITLE
Sceptre Update & Feedback

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#435]
Hi all, 

I thought I would give an update about the status of Version 2, as of 17th July
2018; for an up to date view of V2 [see the roadmap](https://github.com/cloudreach/sceptre/wiki/Roadmap). 

As it stands, Version 2 (in `master`), can be used for experimentation
purposes. There are two outstanding items that are still to be completed but
shouldn't have a negative impact once introduced. The outstanding items are:

1. Documentation update (#306)
2. Improve how cascading config is handled by utilising directed graphs (#422).

The first item is self-explanatory. The second aims to keep cascading config as
part of this project but makes the implementation robust. By addressing the
cascading configuration implementation shortcomings we will: make it easier to
debug applications, provide clearer error messages and give the ability to
quickly see how your stacks influence each other.

Whilst I am keen to get V2 released, I hope many of you will see the benefit of
waiting a bit longer in order to get better cascading config behaviour. The
reason that we are not just releasing V2 now and then improving cascading
config implementation in 2.1, is that the change _may_ introduce breaking
changes.

If you do decide to experiment with V2, please give feedback. If you do see an
opportunity to update the documentation can you either comment on '#306'
highlighting the issue; even better, please submit a PR to update the docs.
I intend to write a Migration Guide to help the transition between V1 and V2 as
part of the Documentation Update. 
 

As many of you will be aware there is a parallel work-stream on at the moment
to bring some fixes and improvements for V1. The immediate priority is to get
1.3.5 as defined on the roadmap released then get V2 out closely after. Once V2
is out and has "bedded in", I will issue a maintenance notice for V1 and our
full development effort will be spent on V2. 

The approximate timescales that I am aiming for are as follows:

- Release v1.3.5 week commencing July 31st 2018 

- Release v2.0.0 week commencing 13th August 2018

Any questions or comments about the roadmap please leave below.

**Comment by stolendog** [comment]
Hello @ngfgrant 
when can we expect the v2 release?

**Comment by ngfgrant** [comment]
Hey @stolendog - I was hoping to get it out last week. Unfortunately, the final task I am working on is taking a bit longer than hoped; really hoping to get (at least) a release candidate out in the next couple of days. As it stands you can experiment with v2 and there shouldn't be any major changes from now and the released version.  

There are still some documentation update in #306 that need work and would really appreciate any help with them 🙏

**Comment by ryanpagel** [comment]
Any update on a v2 release date?

**Comment by ngfgrant** [comment]
@ryanpagel there is now a release candidate out for version 2 and we are targeting the end of the month for the full v2 release.

**Comment by ryanpagel** [comment]
Just upgraded and got `environment_config is undefined` when running `sceptre update [path/to/stack]`
