### ISSUE TITLE
InvalidClientTokenId error after commit bf70aec9f88e095d295c93a40d091d4d45f57b3e

### ISSUE THREAD

**Issue by alytle** [cloudreach/sceptre#439]
When I upgrade past this commit, my environment variable based credentials stop working: https://github.com/cloudreach/sceptre/commit/bf70aec9f88e095d295c93a40d091d4d45f57b3e

Old Build:
```
=> pip install git+https://github.com/cloudreach/sceptre.git@4674616caf05978843e560e01b7dd91f0137a9ed --upgrade
Collecting git+https://github.com/cloudreach/sceptre.git@4674616caf05978843e560e01b7dd91f0137a9ed
  Cloning https://github.com/cloudreach/sceptre.git (to revision 4674616caf05978843e560e01b7dd91f0137a9ed) to 
...
Installing collected packages: sceptre
  Found existing installation: sceptre 1.3.3
    Uninstalling sceptre-1.3.3:
      Successfully uninstalled sceptre-1.3.3
  Running setup.py install for sceptre ... done
Successfully installed sceptre-1.3.3

$ => sceptre status dev
dev/stack1: PENDING
dev/stack2: CREATE_COMPLETE
dev/stack3: UPDATE_ROLLBACK_COMPLETE
dev/stack4: CREATE_COMPLETE
dev/stack5: UPDATE_COMPLETE
```

New Build:
```
=> pip install git+https://github.com/cloudreach/sceptre.git@bf70aec9f88e095d295c93a40d091d4d45f57b3e --upgrade
Collecting git+https://github.com/cloudreach/sceptre.git@bf70aec9f88e095d295c93a40d091d4d45f57b3e
  Cloning https://github.com/cloudreach/sceptre.git (to revision bf70aec9f88e095d295c93a40d091d4d45f57b3e) to 
...
  Running setup.py install for sceptre ... done
Successfully installed sceptre-1.3.3

$ => sceptre status dev
An error occurred (InvalidClientTokenId) when calling the DescribeStacks operation: The security token included in the request is invalid.
```

My AWS CLI still works with the same credentials, and so does boto3 if I instantiate it with defaults (boto3.client('cloudformation')). I expect this relates to a change in this build in how we create the boto cfn client?

I do not have any ~/.aws/credentials files, I'm just using aws-vault to generate environment variables.

**Comment by nabeelamjad** [comment]
I think I have an idea what could be causing this, could you try installing the following Sceptre version: https://github.com/nabeelamjad/sceptre/tree/session-token-fix

Let me know if that works.

**Comment by alytle** [comment]
I tested it with the same environment/templates and it seems to work correctly. Anything specific you need me to test other than the command which failed previously?

**Comment by nabeelamjad** [comment]
Nope, no need. I'll get this fix in PR soon and hopefully merged not too long. I just need to run some tests to ensure everything is good with or without AWS security tokens.
