### ISSUE TITLE
Please release 1.x update to address dependency issues

### ISSUE THREAD

**Issue by et304383** [cloudreach/sceptre#441]
Jinja2 version issue was fixed, but no new version was pushed.

Click is stuck at version 6.6 but 6.7+ is available.  Can't install aws sam cli as a result.

**Comment by ngfgrant** [comment]
@et304383 sure no problem. Assuming that click 6.7 doesn't break things and require further work, I will get this into our next release which will be this week.

**Comment by ngfgrant** [comment]
I am going to close this issue but it will make it into next v1 release as part of #448
