### ISSUE TITLE
An official Docker image?

### ISSUE THREAD

**Issue by rgitzel** [cloudreach/sceptre#445]
I have just started using `sceptre` _(sweet! no more hand-rolling a bash script for every project's set of stacks)_ and run it as a Docker container. Since there's no official image, either I can use out-dated third-party images from Dockerhub, or roll my own.

It would be much nicer (and quicker) to be able to pull official images, particularly when a new version of `sceptre` comes out.

This seems to do the trick:  https://github.com/cloudreach/sceptre/compare/v1...rgitzel:docker-v1  

A few `docker` commands on each release would be enough to deploy a new image:
```
docker build -t sceptre-local .

docker tag sceptre-local cloudreach/sceptre:1.3.4
docker push cloudreach/sceptre:1.3.4

docker tag sceptre-local cloudreach/sceptre:latest
docker push cloudreach/sceptre:latest
```

**Comment by ngfgrant** [comment]
Hey @rgitzel 

Good suggestion. Currently, we have https://hub.docker.com/r/cloudreach/sceptre-circleci/ which is built from https://github.com/cloudreach/sceptre/blob/master/.circleci/Dockerfile and is used in our CircleCI builds. Is this the sort of thing you mean? 

Cheers,
Niall

**Comment by rgitzel** [comment]
Hey @ngfgrant, 

That Docker image has a much different purpose.  As I understand it, it gives CircleCI a command-line environment that's able to run the build.  It's not used to run Sceptre, itself.

In this case, the Docker image already has Sceptre installed, ready to run.

Thus you can run Sceptre without ever even having Python installed.

**Comment by rgitzel** [comment]
Apologies for not following up with this sooner.

I forked the repo to implement this feature, and have deployed an image to Docker Hub. 

Instructions are here:  https://github.com/rgitzel/sceptre/tree/docker#docker

I've tested it with common commands on a simple stack, and it seems to work fine (except for `init` which hampered by https://github.com/cloudreach/sceptre/issues/467).

I'm going to ask some folks at work to test it out, but if anyone else wants to try it, please do!

And if it's deemed a good idea, I'll create a PR against this project, and delete the image in Docker Hub.

**Comment by rgitzel** [comment]
I've created a pull request:  https://github.com/cloudreach/sceptre/pull/479

It's contains the `Dockerfile` and a bit of documentation.

I've also created a Dockerhub page for the image, which contains detailed documentation:  https://hub.docker.com/r/rgitzel/sceptre/

It's not under source control, per se, but if/when the PR is accepted and the image published, I can provide the source to be pasted into the official Dockerhub page.
