### ISSUE TITLE
Support CloudFormation built-in functions (!Join, !Sub etc.)

### ISSUE THREAD

**Issue by seddarj** [cloudreach/sceptre#447]
Are there any plans to support built-in CloudFormation functions like `!Join` or `!Sub`?

It is often necessary to grab the output of a stack using a `!stack_output` and append something to it etc. which cannot be **generically** defined using the current Troposphere + Yaml paradigm alone.

From an implementation standpoint it would mean to have the Yaml parser ignore those tags or something similar.

**Comment by akdor1154** [comment]
Can't you still just do it in the second stack with !Join in its template?

**Comment by seddarj** [comment]
That's the question 😃 @akdor1154 

I don't think you can from the `.yaml` file because sceptre tries to interpret `!Join` when it parses the yaml but doesn't know how.

**Comment by akdor1154** [comment]
You should be able to do it from the template file, just not from the stack config file.

**Comment by seddarj** [comment]
FYI, I ended up adding a functionality in the base class which all my templates inherit to parse the sceptre_user_data object and look for certain keywords and convert those to CloudFormation intrinsic functions.

This issue can be closed ;-)
