### ISSUE TITLE
How can I modify a var from the same file

### ISSUE THREAD

**Issue by ismaelfernandezscmspain** [cloudreach/sceptre#45]
I Have this var:
BrokersInstance: !stack_output_external security::InstanceProfile

An now I have to do:
BrokersInstanceProfile: "{{ BrokersInstance.split('/')[-1] }}"

How I can?

**Comment by ismaelfernandezscmspain** [comment]
Done it! 
I changed it in the output CF.

**Comment by theseanything** [comment]
Hi @ismaelfernandezscmspain,

Not entirely sure how your project is structured, but I assume you want the CloudFormation parameter `BrokersInstanceProfile` to be set as an output from another existing stack?

Are you able to just simply use ?:
```
BrokersInstanceProfile: !stack_output_external security::InstanceProfile
```

Anyways happy to help if you have any other questions :)

**Comment by theseanything** [comment]
But to respond to your original question - sceptre_user_data or other parameters with the template are not available via the Jinja templating functionality, only those passed in via `--var` or `--var-file` when using the CLI

**Comment by ismaelfernandezscmspain** [comment]
yeah! 
Solved it!
