### ISSUE TITLE
stack_group_path doesn't contain the whole path at every stage

### ISSUE THREAD

**Issue by seddarj** [cloudreach/sceptre#456]
In v1, the `environment_path` variable used to contain the whole path to the stack being deployed.

In v2, the `stack_group_path` variable only contains the path up to the file being considered at a given point. For example, in the following case, this is what happens:
```
config
  |_ level1
    |_ config.yaml    => stack_group_path = [level1] (in v1, environment_path=[level1, level2, level3])
    |_ level2
      |_ config.yaml   => stack_group_path = [level1, level2] (in v1, environment_path=[level1, level2, level3])
      |_ level3
        |_ config.yaml   => stack_group_path = [level1, level2, level3] (in v1, environment_path=[level1, level2, level3])
        |_ stack.yaml
```

Was the new behavior designed like this for some reason or was it changed inadvertently?

I have use cases where the old behavior is required.

I can submit a PR to have the `stack_group_path` behave like the old `environment_path` if need be.

**Comment by ngfgrant** [comment]
Hi @seddarj - not had a chance to look at this yet. Will get to it when I can.

**Comment by ngfgrant** [comment]
@seddarj I have spent quite a bit of time around this issue in v2 whilst working on a refactor of a bunch of stuff. Getting the full or any part of the path will become trivial with: https://github.com/cloudreach/sceptre/pull/493

I am going to close this as it will now be resolved in v2.

**Comment by seddarj** [comment]
Got it, thanks @ngfgrant !
