### ISSUE TITLE
Vacation Notice

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#465]
Hi folks, 

Just wanted to let you know that I will be away from the 23rd August to the 10th September. I will have no cell coverage or internet access for almost the entire duration.

Despite best efforts, I've been unable to get V2 to a point where it can be released but will resume work when I am back; it's not far off. Given v2 in `master` is ready to experiment with if anyone can help update the docs whilst I am away that would be a big big help.

See you all soon,
Niall

**Comment by akdor1154** [comment]
Have a great trip! Help with the docs is a bit of a bootstrapping problem I think - I'd happily contribute but I have no idea how to use v2 because there are no docs or example projects for it, so I can't write docs or example projects for it... :)

**Comment by ngfgrant** [comment]
Thanks all -  I am back now. Getting caught up and will get more communication out in the coming days about next steps.
