### ISSUE TITLE
Address 'profile'  in the documents

### ISSUE THREAD

**Issue by jeffmacdonald** [cloudreach/sceptre#47]
I'd like to play with sceptre, but currently I'm unsure if which of my AWS profiles it is going to use from .aws/credentials

The only mention I see of profile is that it has been removed from CLI options, so I am unsure of what to do.

Thanks!

**Comment by johnculkin** [comment]
You can set your AWS_DEFAULT_PROFILE environment variable. Sceptre will pick that profile from your ~/.aws/config file. 

The source_profile attribute for the profile should correspond to an entry in your ~.aws/credentials file.

**Comment by jeffmacdonald** [comment]
Thanks!
