### ISSUE TITLE
Custom Resolvers return Yaml constructor errors

### ISSUE THREAD

**Issue by fibonascii** [cloudreach/sceptre#478]
I seem to be getting YAML Constructor errors when trying to implement a custom resolver. This happens as well with the example custom resolver in the documentation

    from sceptre.resolvers import Resolver
    import json
    import os

    class PackerImageResolver(Resolver):

        def __init__(self, *args, **kwargs):
            super(PackerImageResolver, self).__init__(*args, **kwargs)

        def resolve(self):
        """
	    Load Packer Manifest File and return the AMI ID	
        """
           
            artifact_path = os.path('../../../jenkins-pipeline/validatebuild')
	        build_artifact = json.loads(os.path.join(artifact_path, self.argument))
	        ami = build_artifact['builds']['artifact_id'].split(':')[1]
		
	        return ami	

And then the stack config

    template_path: templates/rest_api.py
    parameters:
        RestApiImageId: !packer_image_resolver "manifest.json" 

And the output

    yaml.constructor.ConstructorError: could not determine a constructor for the tag 
    '!packer_image_resolver'
      in "<unicode string>", line 10, column 21:
            RestApiImageId: !packer_image_resolver "manifest ...`

  
I'm wondering if there might be some kind of encoding issue on my system that would cause this?

**Comment by akdor1154** [comment]
Where are you putting the resolver .py? Also just to check, sceptre v1.x?

**Comment by nabeelamjad** [comment]
Make sure you install the custom sceptre package as well (`pip install .`) as it wouldn't find the entry points otherwise. and you _may_ need to update https://github.com/cloudreach/sceptre/blob/master/setup.py#L70 (unsure)

**Comment by ngfgrant** [comment]
#542 Should resolve this issue.

**Comment by anh072** [comment]
@fibonascii how did you resolve this?

**Comment by TeemuKoivisto** [comment]
@anh072 I don't know about you, but because I used on my macOS my brew installed Sceptre it couldn't resolve the installed pip packages for some reason. So when I changed to using `virtualenvwrapper` with totally separate environment and then installed my custom package I was able to get to the next error. Yey.
