### ISSUE TITLE
Feature request - "launch stack and its dependencies"

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#486]
Sometimes I want to launch not just a whole environment, but instead just a stack and whatever its dependencies are. The canonical example is for doing DB schema updates, where I would like to do - 
`sceptre launch-stack --with-deps prod db`
`./update-db-schema.sh`
`sceptre launch-env prod`

Would a PR to add this be accepted? I think it will be quite a minimal amount of code.

**Comment by ngfgrant** [comment]
Hey @akdor1154 I am working on a PR for v2 at the moment that should manage this behaviour by default. If you want to add something for v1 please feel free and I will have a look, although it might be a bit more coding than first appears.

**Comment by ngfgrant** [comment]
@akdor1154 I am going to close this for now as it should be handled by default in version 2 and a fix for v1 would actually be quite tricky and error prone without changing quite a bit of behaviour.
