### ISSUE TITLE
template bucket encryption

### ISSUE THREAD

**Issue by craighurley** [cloudreach/sceptre#491]
```
$ sceptre --version
Sceptre, version 1.4.2
```

When using `template_bucket_name` (https://sceptre.cloudreach.com/latest/docs/environment_config.html#template_bucket_name), the bucket is automatically created by sceptre if it does not already exist:

> If the bucket does not exist, Sceptre creates one using the given name, in the AWS region specified by region.

... it would be nice if server side encryption was enabled by default; got to keep ticking those encryption boxes to keep security folks happy :)

**Comment by ngfgrant** [comment]
Hi @craighurley yeh I agree happy to look over a PR for this.

**Comment by ngfgrant** [comment]
Closing as #730 gives a more broad template bucket config option including encryption.

**Comment by jfalkenstein** [comment]
The spirit of this ticket has been acomplished now that the template_bucket_name is resolvable, from #1153 .
