### ISSUE TITLE
[v1] Inconsistent launch-env behaviour

### ISSUE THREAD

**Issue by seddarj** [cloudreach/sceptre#492]
Hi,

Observed using v1.4.2 on Mac, Linux and Windows

I've noticed some inconsistencies when using `launch-env` on folders containing around 80 files in multiple subfolders.

In those circumstances, I sometimes get errors on some stacks that don't happen if I run `launch-env` again or if I run `launch-stack` on that particular stack. Running `launch-env` again might sometimes lead to the same error even though everything was deployed in a previous run.

Here's a sample output from a failed `launch-env`:
```
[2018-10-25 15:53:15] - sceptre.environment - Stack gabi/eu-west-1/dev/core/cloudwatch/subscriber/event-rule failed to launch
Traceback (most recent call last):
  File "c:\program files\python27\lib\site-packages\sceptre\environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "c:\program files\python27\lib\site-packages\sceptre\stack.py", line 281, in launch
    status = self.create()
  File "c:\program files\python27\lib\site-packages\sceptre\hooks\__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "c:\program files\python27\lib\site-packages\sceptre\stack.py", line 207, in create
    create_stack_kwargs.update(self._get_template_details())
  File "c:\program files\python27\lib\site-packages\sceptre\stack.py", line 697, in _get_template_details
    return {"TemplateBody": self.template.body}
  File "c:\program files\python27\lib\site-packages\sceptre\template.py", line 75, in body
    self._body = self._call_sceptre_handler()
  File "c:\program files\python27\lib\site-packages\sceptre\template.py", line 127, in _call_sceptre_handler
    sys.path.remove(os.path.join(os.getcwd(), directory))
ValueError: list.remove(x): x not in list
```
This ran on Windows but the same behaviour was observed on Linux.

Another odd behaviour I've noticed only when running `launch-env` on big folders, is that some hooks and resolvers that use relative paths will not find the files in question. Doing a `launch-stack` that uses the same hooks and resolvers will work but not a `launch-env`. I had to replace all my relative file references to convert them to absolute paths which shouldn't be required.

**Comment by ngfgrant** [comment]
@seddarj 

Not sure where to start with this 🤦‍♂️  - good effort in finding this. You've also hit on a number of things a few of my recent PRs should fix in v2. I want to keep this open for now - I don't think it will be fixed in v1 in the near future. Once v2 is out would you be willing to test using that and report back?

**Comment by seddarj** [comment]
Thanks for looking into this!

I'll report back once v2 is out to see if the aforementioned errors still exist.

**Comment by ngfgrant** [comment]
@seddarj - would you be able to test this with our v2 release candidate? You should be able to install it with `pip install sceptre --pre` in a fresh virtualenv and the Migration Guide is here: https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2

**Comment by seddarj** [comment]
Hi @ngfgrant, sorry for the delayed response but I just got back from vacation and could look into this before. Do you still need help with this?

**Comment by ngfgrant** [comment]
Hey @seddarj it would be awesome if you could test this out with v2. We ran some tests when developing v2 with around 20 nested folders and 200+ stacks and didn't run into any issues but always good to see how things will perform with real-world projects.
