### ISSUE TITLE
deploy to china aws using sceptre

### ISSUE THREAD

**Issue by fitchxlin** [cloudreach/sceptre#494]
Does sceptre support deploying to AWS China (Beijing and Ningxia)?

**Comment by nbjcn1** [comment]
There isn't anything partition specific in our code, so if you have the aws cli correctly configured it should just work. If you have any specific issues let us know though, as it hasn't been tested in Bejing or Govcloud.

**Comment by ngfgrant** [comment]
Might be related to https://github.com/cloudreach/sceptre/pull/455

**Comment by fitchxlin** [comment]
Was deploying to ningxia and beijing yesterday and had issues with s3 bucket.  It seems sceptre or cloudformation is default to us-east-1.  I had to comment out the template_bucket_name in config.yml and was able to launch with no issues.
