### ISSUE TITLE
Creating stacks in multiple regions.

### ISSUE THREAD

**Issue by chaitand28** [cloudreach/sceptre#495]
Use case: I need to deploy multiple CFN templates in ALL the aws Regions
Can the field 'region' in the config file be a LIST of regions or it has to be a single region per config file?

**Comment by akdor1154** [comment]
As a workaround, you could do
```
region: {{ var.region }}
```
and then launch Sceptre like 
```
sceptre --var region=ap-southeast-2 launch-env ...
sceptre --var region=us-east-2 launch-env ...
```
If parallelism is required you could use bash job control or GNU parallel for a fancier option.

**Comment by akilleen** [comment]
I'm doing some brainstorming on this issue and wonder if utilizing [Stack Sets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-concepts.html) may be a good way to implement multi-region configs? It would have the added benefit of multi-account configuration.

**Comment by craighurley** [comment]
Using native stack sets is the way to go.  You can watch this issue and hope stack set support comes to sceptre: https://github.com/cloudreach/sceptre/issues/177

**Comment by ngfgrant** [comment]
So this should be possible in both v1 and in v2. The logic to pass in region as variable would sit outside of Sceptre. Definitely think we will support StackSets and so we will have more "native" support for this use case there. Closing as this will be handled by #177

**Comment by m1keil** [comment]
I know this is closed but I do wonder, maybe one day it will be possible to provide same variable a couple of times which will trigger a parallel deploy?

example:

    sceptre --var region=ap-southeast-2 --var region=ap-southeast-1 create ...

or at least make the region a special kind of variable.
