### ISSUE TITLE
sceptre requirements "incompatible" with awscli 

### ISSUE THREAD

**Issue by 1oglop1** [cloudreach/sceptre#499]
Sceptre has older requirements than awscli

when `pip install awscli`
then `pip install sceptre`

```
click==6.7, but you'll have click 7.0 which is incompatible.
sceptre 1.4.2 has requirement colorama==0.3.7, but you'll have colorama 0.3.9 which is incompatible.
sceptre 1.4.2 has requirement packaging==16.8, but you'll have packaging 18.0 which is incompatible.

```
the reason is pinned versions in `setup.py` [L19](https://github.com/cloudreach/sceptre/blob/master/setup.py#L19)

`pipdepttree` requirements comparison 

```
awscli==1.16.53
  - botocore [required: ==1.12.43, installed: 1.12.43]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.7.3]
      - six [required: >=1.5, installed: 1.11.0]
    - urllib3 [required: >=1.20,<1.25, installed: 1.23]
  - colorama [required: >=0.2.5,<=0.3.9, installed: 0.3.7]
  - docutils [required: >=0.10, installed: 0.14]
  - PyYAML [required: >=3.10,<=3.13, installed: 3.13]
  - rsa [required: >=3.1.2,<=3.5.0, installed: 3.4.2]
    - pyasn1 [required: >=0.1.3, installed: 0.4.4]
  - s3transfer [required: >=0.1.12,<0.2.0, installed: 0.1.13]
    - botocore [required: >=1.3.0,<2.0.0, installed: 1.12.43]
      - docutils [required: >=0.10, installed: 0.14]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.7.3]
        - six [required: >=1.5, installed: 1.11.0]
      - urllib3 [required: >=1.20,<1.25, installed: 1.23]
sceptre==1.4.2
  - boto3 [required: >=1.3,<2.0, installed: 1.9.43]
    - botocore [required: >=1.12.43,<1.13.0, installed: 1.12.43]
      - docutils [required: >=0.10, installed: 0.14]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.7.3]
        - six [required: >=1.5, installed: 1.11.0]
      - urllib3 [required: >=1.20,<1.25, installed: 1.23]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
    - s3transfer [required: >=0.1.10,<0.2.0, installed: 0.1.13]
      - botocore [required: >=1.3.0,<2.0.0, installed: 1.12.43]
        - docutils [required: >=0.10, installed: 0.14]
        - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
        - python-dateutil [required: >=2.1,<3.0.0, installed: 2.7.3]
          - six [required: >=1.5, installed: 1.11.0]
        - urllib3 [required: >=1.20,<1.25, installed: 1.23]
  - click [required: ==6.7, installed: 6.7]
  - colorama [required: ==0.3.7, installed: 0.3.7]
  - Jinja2 [required: >=2.8,<3, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - packaging [required: ==16.8, installed: 16.8]
    - pyparsing [required: Any, installed: 2.2.2]
    - six [required: Any, installed: 1.11.0]
  - PyYaml [required: ==3.13, installed: 3.13]
  - six [required: ==1.11.0, installed: 1.11.0]
```

**Comment by akdor1154** [comment]
This is because install_requirements in setup.py lists exact version constraints. This is in direct conflict with advice at https://packaging.python.org/discussions/install-requires-vs-requirements:

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

Going by this advice, deps in sceptre's setup.py should have unlocked versions unless there is a known incompatibility.

**Comment by ngfgrant** [comment]
Thanks for raising this issue - happy to receive a PR for this. I am not aware of any restrictions but there might have been reasons for this from previous maintainers.

If the packages that are pinned to a specific version are semantically versioned then I am happy for the next major version to be set as an upper bound and what ever the current version is as the lower bound. i.e. `click >=6.7, <=7.0`

That is not to say that we won't bump up the packages to their next major release - it will just require a bit more care. 

Regarding `click` `6.x` vs `7.x` - I don't see a requirement for `awscli` to have `7.x` so within your virtualenv for sceptre please use click <7.0. Same with the `packaging` case.

**Comment by 1oglop1** [comment]
Agains which branch shall I make the PR?
Cuz master is V2 and `setup.py` in master is missing `networks` in `install_requires`

**Comment by ngfgrant** [comment]
Put into v1 branch and I will sort out the rest for the v2 release on master.

**Comment by ngfgrant** [comment]
`click 7.0` removes support for Python 2.6, which according to our `setup.cfg` we still support. I am very open to dropping Python2 support but not during v2. Also, I can't see any requirement in `awscli` that points to `click`. Closing for now.

**Comment by jghaines** [comment]
I'm getting similar version conflicts between pytest-cov (which has a packaging (Any version) dependency) and sceptre 2.2.1 (which pins packaging==16.8).

I worked around it by explicitly installing packaging: `pip3 install packaging=16.8`

The other comments in this thread about "not pinning versions" (or at least upgrading some) still seem to be relevant.

**Comment by ngfgrant** [comment]
pytest-cov isn't required for install. Are you working in a virtualenv?

**Comment by jghaines** [comment]
You are correct, I'm using virtualenv (in pipenv) and pytest-cov is my dependency, not a sceptre dependency:

I just wanted to:
* Point out that this issue still causes problem, and in other contexts than the above
* Agree with the earlier comments on version pinning
* Offer a possible workaround for others hitting this issue

**Comment by ngfgrant** [comment]
@jghaines thanks. Sceptre v2 will support Python2 but drops py2 support in v3 when it eventually is released.

Will look at unpinning and putting in a PR for some latest packages.
