### ISSUE TITLE
Remove dev docs

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#50]
@seanrankine am I correct in thinking that the dev docs are no longer used? We don't have a develop branch any more. If so, we should remove them.

**Comment by theseanything** [comment]
hmm.... we could have latest commit docs and release docs? But happy to just remove them, not sure we need both...

**Comment by jamesroutley** [comment]
Yeah that makes sense actually. If we add a new feature the related documentation shouldn't be added to the main docs until we release the feature. We can update circle-ci to do this.

So if that's the case, do a release when we update documentation so the changes are pushed out to the main docs.

**Comment by theseanything** [comment]
So just to be clear - have `/dev/docs/` the latest commit and `/docs/` the latest release? Or do you wanna just stick to `/docs/` and remove `/dev/docs/`

**Comment by jamesroutley** [comment]
yep option 1 - `/dev/docs/` and `/docs/`

**Comment by jamesroutley** [comment]
I'll close this and open another issue to update circle to route the docs to the relevant places.
