### ISSUE TITLE
Sceptre v2-rc missin internal sub packages during installation.

### ISSUE THREAD

**Issue by 1oglop1** [cloudreach/sceptre#503]
In Sceptre v2-rc `setup.py` packages are updated manually and does not support newly created/refactored sub-packages.

https://github.com/cloudreach/sceptre/blob/v2-rc/setup.py#L45

For example sub-package `sceptre.config` is not installed now.

**Comment by nabeelamjad** [comment]
We've fixed this under the [use_stack_graph_for_dependencies](https://github.com/cloudreach/sceptre/tree/use_stack_graph_for_dependencies) branch, it'll be out _shortly_.

**Comment by 1oglop1** [comment]
@nabeelamjad so PR can be closed?

**Comment by nabeelamjad** [comment]
I think so, I'll check with @ngfgrant because we may want to update some dependencies that are interfering with awscli perhaps.

**Comment by 1oglop1** [comment]
Fine with me as long as it's fixed :)
