### ISSUE TITLE
Sceptre 2.0 Release Candidate 1

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#513]
We are delighted to announce Release Candidate 1 of Sceptre 2.0! :tada:

Version 2 has been a long time in the making and today we get a big step closer to our final release.

We'd love it if you could try out Release Candidate 1 and give us feedback. You can pip install it:

```shell
pip install sceptre --pre
```

Just remember to setup a fresh virtualenv to do so 😉

# Improvements

We'd say the main improvements of Sceptre 2.0.0rc1 are:

- Simplified CLI
- Simplified API with `SceptreContext` & `SceptrePlan`
- Robust Stack Dependency Handling
- Improved Cross Region/Account support
- Reusable Hooks and Resolvers (pip installable)
- Better/accurate API docs

# Migration Guide 

We've endeavoured to make as few breaking changes as possible but in order to simplify the CLI we have made quite a few changes there. We think most of them should be intuitive for example, `sceptre launch-stack ...` and `sceptre launch-env ...` just become `sceptre launch ...`.

A full Migration Guide can be found [here on our GitHub wiki](https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2).

# Documentation 

At this stage we have updated our README and API reference documentation. 

The API documentation is up to date and can be found at (https://sceptre.cloudreach.com/dev/docs/api/sceptre.html)

# What's to come

We don't anticipate introducing any new features before the final release of 2.0.0. We will, however, be working on improving our documentation; specifically user guides and tutorials, and fixing any issues that arise.

# Giving Feedback 

To give feedback just create an issue as normal, please use `RC` somewhere in the issue title. 

Thanks!
Niall

**Comment by ryanpagel** [comment]
I'm getting "environment_config is undefined" even for stacks that don't use any environment_config.  I can provide more details on our setup if needed.  But I will say that we're not doing anything complicated, we have a pretty basic setup.

**Comment by ngfgrant** [comment]
Hey @ryanpagel could you open up an issue and we can continue the conversation there?

**Comment by ngfgrant** [comment]
Actually, @ryanpagel I think we have fixed this with `rc2`, released today. 

I have also updated the migration guide. In this case you will need to update some project files.  So that where you have `stack.environment_config` you access the attributes you want directly from the stack, i.e. `stack.project_code`. 

If you do `pip install sceptre --pre` again in your v2-testing virtualenv you will get rc2 with this fix in it.

**Comment by ryanpagel** [comment]
When I try this I now get a "stack is undefined" error message.  Any thoughts?

**Comment by ngfgrant** [comment]
Hey @ryanpagel 

Ok so I have found what the issue is here. 

Basically there was a divergence between the docs (https://github.com/cloudreach/sceptre/blob/v1/docs/docs/environment_config.md) and what seems to be happening in reality. The intention of `v1` environment_config was to only allow the following keys:

```iam_role (optional)
profile optional
project_code (required)
region (required)
template_bucket_name (optional)
template_key_prefix (optional)
require_version (optional)```
