### ISSUE TITLE
Version 2.0.0 Released!

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#530]
# Sceptre 2.0.0

We are delighted to announce Sceptre 2.0.0 :tada: 🎈 🍾 

Version 2 has been a long time in the making and we are very grateful for those
who have contributed along the way; thank you.

You can pip install Sceptre 2.0.0:

```shell 
pip install sceptre
```

We recommend that you use a fresh virtualenv and git branch to do the migration.

# Improvements

The main improvements of Sceptre 2.0.0 are:

- Simplified CLI with more generic commands (`sceptre launch` vs 
`sceptre launch-env`&`sceptre launch-stack`) 
- Simplified API with `SceptreContext`& `SceptrePlan` 
- Robust Stack Dependency Handling using `StackGraph` Improved
- Cross Region/Account support 
- Reusable Hooks and Resolvers (pip installable)
- Better/accurate API docs

# Migration Guide

We've endeavoured to make as few breaking changes as possible but in order to
simplify the CLI we have made quite a few changes there. We think most of them
should be intuitive for example, `sceptre launch-stack ...` and `sceptre launch-env ...` become `sceptre launch ...`.

A full Migration Guide can be found [here on our GitHub
wiki](https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2).

# Documentation

Our project docs (README etc), API reference documentation and examples on our
documentation site are all up to date.

The Migration Guide: [here on our GitHub
wiki](https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2).

The API documentation:
(https://sceptre.cloudreach.com/latest/docs/api/sceptre.html)

Examples and Tutorials:
(https://sceptre.cloudreach.com/latest/docs/)

# Giving Feedback

To give feedback, create an issue as normal and please use `V2` somewhere in
the issue title.

Thank you and I hope you enjoy v2,

Niall

**Comment by christierney-cr** [comment]
Well done to everyone involved!
