### ISSUE TITLE
Update Docs on Resolver Attributes

### ISSUE THREAD

**Issue by jmwyson** [cloudreach/sceptre#543]
Hi,

I was trying to write a resolver and access `connection_manager` using the `self.connection_manager` but got `AttributeError: 'MyResolver' object has no attribute 'connection_manager'`. Is the correct way to access connection manager `self.stack.template.connection_manager`?

Docs indicate :

Resolvers may have access to `argument`, `stack_config`, `stack_group_config` and `connection_manager` as an attribute of `self`. For example `self.stack_config`. 

This is valid for the base class in v1 but not in v2. The properties that are available in v2 seem to be `logger`, `argument`, and `stack`. 

Example resolver custom_resolver.py shown in docs may also be misleading for v2 since it describes attributes which are not available in the base class of v2.

The following attributes may be available from the base class:
        self.stack_config  (A dict of data from <stack_name>.yaml)
        self.stack.stack_group_config  (A dict of data from config.yaml)
        self.connection_manager (A connection_manager)
        """
        return self.argument

**Comment by ngfgrant** [comment]
Hey @jmwyson 

So you can access connection manager from stack like you suggested:

```
connection_manager = self.stack.template.connection_manager

        try:
            response = connection_manager.call(
                service="cloudformation",
                command="describe_stacks",
                kwargs={"StackName": stack_name},
                profile=profile,
                region=region,
                stack_name=stack_name
            )
```

Looks like we need to update the docs. Thanks for point that out. we have a patch release coming out this week, will aim to get it in with that. 

Best Wishes,
Niall

**Comment by et304383** [comment]
Have these changes not been published?  I just ran into the same issue.

https://sceptre.cloudreach.com/latest/docs/resolvers.html

This still states that connection_manager is an attribute of self.

**Comment by luismy** [comment]
Same for me! 😞
