### ISSUE TITLE
V2: Improve confirmation message when deleting Change Set

### ISSUE THREAD

**Issue by nvengal** [cloudreach/sceptre#551]
When running the `sceptre delete env change-set-name` command, the confirmation message is displayed in the following format:
```
The following stacks in the following order will be deleted:
<stack 1>
<stack 2>
<stack 3>
...

Do you want to delete_change_set change set 'change-set-name' for 'env' [y/N]: 
```

After recently migrating to v2 from v1, this is an alarming message (since the delete-stack and delete-change-set operations have been combined under the delete command). It is not readily clear that the delete command will not delete the entire stack along with the change-set. The message: `The following stacks in the following order will be deleted` should be avoided for the delete operation when it refers to a change-set.

**Comment by ngfgrant** [comment]
Agreed - that is a little bit alarming. Will get that amended in 2.0.1.
