### ISSUE TITLE
V2 stack_output vs stack_output_external clarification

### ISSUE THREAD

**Issue by et304383** [cloudreach/sceptre#556]
`stack_output` now seems to be able to reference stacks from a different environment.  Is this true?

`stack_output_external` seems to have been changed to require a stack controlled by sceptre as indiciated by requiring the .yaml extension. Is this true?

Also, slightly unrelated, why is the .yaml extension required now?

**Comment by nabeelamjad** [comment]
stacks can reference any stack group stacks in the same project now

```
root
  config
    group_1 (stack group)
      vpc.yaml
    group_2 (stack group)
      subnet.yaml
```

`stack_output_external` doesn't need the `.yaml` extension, this is only applicable to `stack_output`

**Comment by et304383** [comment]
https://sceptre.cloudreach.com/latest/docs/resolvers.html

Documentation issue then?

**Comment by nabeelamjad** [comment]
Looks like it, that's definitely wrong yeah.

**Comment by ngfgrant** [comment]
Yeh the docs are wrong - there is already a fix in 2.0.1

**Comment by ngfgrant** [comment]
Added clarification note into docs and will be available in v2.0.1

**Comment by adifelice-godaddy** [comment]
Documentation keeps showing this as example, which I believe is misleading:
```yaml
VpcID: !stack_output_external <custom-named-vpc-stack>.yaml::VpcID
```

**Comment by craighurley** [comment]
> Documentation keeps showing this as example, which I believe is misleading:
> 
> ```yaml
> 
> VpcID: !stack_output_external <custom-named-vpc-stack>.yaml::VpcID
> 
> ```

Which version of the docs?  Can you provide a link @adifelice-godaddy ?

**Comment by craighurley** [comment]
nm, I found it: https://sceptre.cloudreach.com/2.6.3/docs/stack_config.html?highlight=stack_output_external#parameters
