### ISSUE TITLE
stack_group_path.index broken in 2.0.1

### ISSUE THREAD

**Issue by m1keil** [cloudreach/sceptre#561]
When templating path sections via **{{ stack_group_path.0 }}**
instead of getting the first item of the path, I get the first char of the path.

i.e if I use **stack_group_path.0** and my path is **dev/ap-southeast-1,** I get back **d** instead of **dev**.

Tested on 2.0.1 with py3.6 & py3.7

**Comment by nabeelamjad** [comment]
Seems this has changed indeed to be a string rather than a list (split by `/`), I don't think it was intentional but I'll check with @ngfgrant

**Comment by m1keil** [comment]
cheers. it's not reflected in the docs so I assumed the behaviour was the same as 1.x.

**Comment by ngfgrant** [comment]
Hi @m1keil 

Apologies this should have been updated in the docs and migration guide to say use ‘command_path’ rather than ‘stack_group_path’. I’ll update any docs that are wrong. Can you see if using command_path gets you your desired result?

**Comment by ngfgrant** [comment]
@m1keil - turns out the docs site needed published and the CloudFront cache invalidated. The docs should now reflect what is required for this to work. Let me know how you get on :)

**Comment by m1keil** [comment]
@ngfgrant @nabeelamjad thanks for the quick response. Yep, that did the trick.

Just have one more quick question regarding 1.x vs 2.x changes: migration guide says **stack_tags** are now **tags** but documentation still showing [stack_tags](https://sceptre.cloudreach.com/latest/docs/stack_config.html#stack_tags) as the correct option. Is this an error in the migration guide?

Regardless, going to close this one.

**Comment by nabeelamjad** [comment]
This was unfortunately an oversight, it was meant to be `tags` but didn't. You can safely stick with `stack_tags` and that'll stay for this version of Sceptre. We'll update the documentation after we make a decision on how to handle this (i.e. use just `stack_tags` or both `tags` and `stack_tags` for the same thing)
