### ISSUE TITLE
set-policy for single stack sets policy for related stacks

### ISSUE THREAD

**Issue by jmwyson** [cloudreach/sceptre#569]
I am using sceptre v2.0.1 and have the following config:

config/env1/s1.yaml
```
template_path: mytemplate.template.yaml
parameters:
  Name: 's1'
  Value: 'v1'
```

config/env1/s2.yaml
```
template_path: mytemplate.template.yaml
parameters:
  Name: 's2'
  Value: !stack_output env1/s1.yaml::Value
```

I would like to set a policy for s2.yaml stack so I run below command:
`sceptre set-policy env1/s2.yaml stack-policy/mypolicy.json`

The command completes successfully but the command applies the stack policy to both s1 and s2 stacks.
```
[2018-12-26 13:48:35] - env1/s1 - Successfully set Stack Policy
[2018-12-26 13:48:35] - env1/s2 - Successfully set Stack Policy
```

How do I set a policy for a specific/single stack?

**Comment by ngfgrant** [comment]
Can you try use `--ignore_dependencies` option to see if that gets you the desired behaviour? 

```shell
sceptre --ignore-dependencies set-policy env1/s2.yaml stack-policy/mypolicy.json
```

**Comment by jmwyson** [comment]
Thank you. The suggestion works @ngfgrant.

Should the default usage description for `sceptre set-policy` command and other commands then have another [OPTIONS] specified prior to set-policy? Typing the command shows options available after the set-policy command.  

`sceptre set-policy [OPTIONS] PATH [POLICY_FILE]`

Or would be redundant as typing `sceptre` command on its own shows the options after and also differentiates between options and arguments.

`Usage: sceptre [OPTIONS] COMMAND [ARGS]...`
