### ISSUE TITLE
V1: update-stack fails with "No updates are to be performed."

### ISSUE THREAD

**Issue by zaro0508** [cloudreach/sceptre#579]
running an update-stack command will fail when there are no updates to perform which doesn't not help with setting up sceptre in a CI scenario. This should work similar to launch-stack command where it will NOT fail in situations where there are no updates to perform.

(py36-sceptredev-v1) ~/w/scpester-infra ❯❯❯ sceptre --var "profile=sandbox.cfservice" --var "region=us-east-1" update-stack test noop
[2019-01-02 11:20:20] - sceptre.stack - test/noop - Updating stack
An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed.
(py36-sceptredev-v1) ~/w/scpester-infra ❯❯❯ echo $?
1

**Comment by akdor1154** [comment]
Is there any reason to not just use launch-stack?

**Comment by zaro0508** [comment]
@akdor1154 no, launch-stack would work for me but regardless IMO this is still a bug.  Also I found this issue after finding issue #568 which is the only command for deploying change set (or SAM) templates.  I looked at fixing #568 but fixed this first since it seemed like an easier fix.  Once this is merged I'll look into #568.   

@ngfgrant does that mean you one fix for both commands?  My idea of the fixes do not seem like it would take the same code path.  This issue also occurs in V2.

**Comment by akdor1154** [comment]
@zaro0508 reason I ask is that I think update-stack is meant to be a loose wrapper on top of the aws api, which also returns an error in this situation. (so does the cli, `aws cloudformation update-stack`).
`launch-stack` seems to exist to hide away this weirdness in the API (e.g. it implements the semantic operation "make cloudformation the same as my filesystem").

IMO you are more being bitten by the fact that no `launch-stack-cs` exists.

**Comment by zaro0508** [comment]
thanks for the explanation @akdor1154 I guess SAM support is unlikely for V1.  On the bright side it looks like SAM is going to be a thing for V2 when PR #586 merges.
