### ISSUE TITLE
Pinned requirement six==1.11.0 collides with other packages

### ISSUE THREAD

**Issue by 1oglop1** [cloudreach/sceptre#598]
I installed `sceptre` and `aws-google-auth` then received
`sceptre 2.0.2 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.`
I cannot run the sceptre now

**Comment by ngfgrant** [comment]
It looks like every package in `aws-google-auth` is unpinned. It is also pre-v1. Can I suggest you install sceptre first, then the next package. You will get a version of six that will meet the requirements from `aws-google-auth`.
