### ISSUE TITLE
Show CloudFormation Events for a stack.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#6]
Could there be a function to describe all the previous CloudFormation Events for a given stack?
It's sometimes useful to see this before making any changes to a stack to see whether someone else has made changes to the stack since you last interacted with it. Not having to go to the console to see this would be great!

**Comment by geeknam** [comment]
I believe you can grab those events from here: http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.describe_stack_events

**Comment by theseanything** [comment]
#128
