### ISSUE TITLE
Make sceptre help pretty again

### ISSUE THREAD

**Issue by m1keil** [cloudreach/sceptre#607]
```
$ sceptre list outputs --help
Usage: sceptre list outputs [OPTIONS] PATH

  List outputs for stack.

  :param path: Path to execute the command on. :type path: str :param
  export: Specify the export formatting. :type export: str

Options:
  -e, --export [envvar]  Specify the export formatting.
  --help                 Show this message and exit.
```

seems like click just uses the docstring as documentation which makes the --help rather ugly. If you like, I can go over the docstrings and make these doc worthy? [Click 7.x support truncating the help text from docstrings](http://click.palletsprojects.com/en/7.x/documentation/#truncating-help-texts).

**Comment by ngfgrant** [comment]
That would be awesome! Thanks

**Comment by m1keil** [comment]
submitted PR.
