### ISSUE TITLE
Add confirmation step when deleting

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#61]
Sceptre should ask for user confirmation when deleting stacks or environments. A CLI flag `--yes/-y` will be added, allowing scriptable deletion of resources. This confirmation will only happen on the CLI, not when delete commands are run from 

## Implementation

- Add a [confirmation prompt](http://click.pocoo.org/5/prompts/#confirmation-prompts) with Click to the function `sceptre.cli.delete_stack`.
- Add a [Click option](http://click.pocoo.org/5/options/) `-y`, which skips the confirmation prompt and runs `env.stacks[stack].delete()`.

## Pros
- Syntax is in keeping with Unix standards (e.g. `yum install`)

## Cons

**Comment by joharohl** [comment]
As was discussed in #62, I think adding the same confirmation for updates would make this a much more operator friendly tool. 

It would be really cool for the update command to give a summary of changes before the update is applied too. But one thing at a time.

**Comment by jamesroutley** [comment]
@joharohl There's a command `update-stack-cs` which prints a summary changes before prompting you to update or not.

**Comment by joharohl** [comment]
@jamesroutley Ah, awesome, didn't know that. Thanks!

**Comment by rmbennett** [comment]
@jamesroutley - The click package offers "Yes Parameters" which is 99% of what you want, except you have to add --yes rather than -y. (3rd line below). Would this be acceptable?
http://click.pocoo.org/5/options/ <- search Yes Parameters.

```
@cli.command(name="delete-stack")
@stack_options
@click.confirmation_option(help='Are you sure you want to delete the stack?')
@click.pass_context
@catch_exceptions
def delete_stack(ctx, environment, stack):
    """Deletes the stack.

    Deletes ENVIRONMENT/STACK."""
    env = get_env(ctx.obj["sceptre_dir"], environment, ctx.obj["options"])
    response = env.stacks[stack].delete()
    if response != StackStatus.COMPLETE:
        exit(1)

```

**Comment by rmbennett** [comment]
If we have this for delete-stack, we should definitely do this for delete-env!

**Comment by theseanything** [comment]
Apart of #60

**Comment by theseanything** [comment]
#278
