### ISSUE TITLE
More interactive channel for Sceptre discussion

### ISSUE THREAD

**Issue by zaro0508** [cloudreach/sceptre#611]
I was wondering if people in this community would be interested in an IRC or Slack channel to have more interactive discussion and support than raising github issues?

**Comment by ngfgrant** [comment]
@zaro0508 I looking into this based on #469 I think there was a bit of a split opinion. 60% felt GitHub was enough 30% wanted IM/Slack. Most people wanted a better way to subscribe to announcements blog/newsletter.

**Comment by 1oglop1** [comment]
I was actually thinking about suggesting some common StackOverflow tag

**Comment by zaro0508** [comment]
@ngfgrant Hmm,  30% seems significant.  Would you consider an announcement and publishing to the Sceptre docs if there were another communications channel?  That could either be IRC/Slack or mailing list?

**Comment by ngfgrant** [comment]
this will be resolved in #615

**Comment by zaro0508** [comment]
I've gone ahead and created a #sceptre channel on [freenode](https://webchat.freenode.net/) if anybody wants to join.
