### ISSUE TITLE
Create or update stack

### ISSUE THREAD

**Issue by prantaaho** [cloudreach/sceptre#612]
I'm trying to build Bitbucket pipeline around sceptre. I have in my repo multiple stacks and correspondingly I have multiple lines like:
```bash
sceptre create dev/stack1.yaml
sceptre create dev/stack2.yaml
...
```
Except that would fail after initial pass, as the create will complain that stack already exists. Hence I actually have something like:
```bash
sceptre create -y dev/docker-registry.yaml || sceptre update -y dev/docker-registry.yaml
```
which is not nice as a) it is ugly b) if create fails due to some other error stack update is still tried. Is there some better way to do this?

Related issue is something similar to #239. How should I handle situations where only some of the stacks are actually updated? Now update will fail with validation error for non updated stacks.

**Comment by seddarj** [comment]
@prantaaho I think `launch` is what you are looking for.

If the stack already exists, it will update it otherwise it will create it.

**Comment by prantaaho** [comment]
Thanks @seddarj! That was it.
