### ISSUE TITLE
adding template_bucket_name to the config throws error

### ISSUE THREAD

**Issue by mMeijden** [cloudreach/sceptre#628]
Im currently running into an issue that when i provide the **template_bucket_name** param the stack creation fails:

`An error occurred (ValidationError) when calling the CreateStack operation: TemplateURL must be an Amazon S3 URL.`

Result is that it won't trigger cloudformation to deploy the stack. However, when i look inside the bucket the cloudformation template has been stored there.

If I do not provide the **template_bucket_name** the stack will be created successfully.

I've followed these docs: https://sceptre.cloudreach.com/latest/docs/stack_group_config.html#template_bucket_name

I've provided the following params:
**template_bucket_name :** just-a-bucket-name
**region:** eu-west-1
**project_code:** apipoc

**Comment by ngfgrant** [comment]
Ok might be an AWS thing.

Could you check the name is valid (no spaces or anything at the end): https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html

and that the name is globally unique (i.e. not just your account).

It is probably the latter that is the issue. Could you try add a bunch of random numbers and letters to your custom name?

**Comment by mMeijden** [comment]
The bucket name is globally unique and it's a valid one. 
The bucket already exists and i'm able to upload files to it through the cli

I've added 123 to the end of the bucket name and ran the script again.

Result is still the validation error but sceptre created the bucket and also uploaded the file into the bucket

**Comment by ngfgrant** [comment]
What sceptre command are you running? Just thinking if you are running `sceptre create` then it might be worth trying `sceptre launch`

**Comment by mMeijden** [comment]
@ngfgrant Sorry for the late reply.
But i'm running sceptre create. I've tried your suggestion but without any luck, I still get the Validation error

**Comment by mMeijden** [comment]
I've ran the same commands on a MacBook. I do not have the issue here. So it's probably a Windows issue.

I think it's related to the forward and backward slashes but I cannot confirm. This slashes problem is related to #575 and should be fixed in 2.0.3 right?

**Comment by ngfgrant** [comment]
Yep @mMeijden almost certainly related to #535

**Comment by ngfgrant** [comment]
Going to close this as it is related to #535
