### ISSUE TITLE
Migration guide V1 to V2 is unclear on how to access stack [group] config

### ISSUE THREAD

**Issue by et304383** [cloudreach/sceptre#633]
https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2#stackgroup-config

I don't even know where to begin.  This section is so poorly worded and back and forth that I cannot figure out how to correctly reference these variables in stack config files or templates.

How does one reference project_code in a jinja2 template?  None of these work:
* {{ project_code }}
* {{ stack.project_code }}
* {{ stack_config.project_code }}
* {{ stack_group_config.project_code }}

What is with the changing between stack, stack_config, and stack_group_config?  What does any of this mean?

**Comment by davidtaddei** [comment]
@et304383 I don't believe you are meant to reference them in a jinja2 template, rather you can use them in the stack definition (which works) for example:

```
template_path: iam.yaml
parameters:
  EnvironmentId: {{project_code}}
```
We can certainly update the docs around template types etc to try and make it clearer, if you have any specific suggestions for what would make it clearer for you I'm sure it would be well received. 👍

**Comment by et304383** [comment]
The docs literally say:

"In version 2 you would access these in a Template like:"

Keyword: **Template**

Still looking for clarity on stack, stack_config, stack_group_config.  Where are these exposed/used?  What is referenced in a template?  Is it still just sceptre_user_data ?

**Comment by ngfgrant** [comment]
I've updated the Migration Guide to be clearer on this. As you said the word "Template" is confusing so that has been change to "stack config".

You can still reference `sceptre_user_data` in template.
