### ISSUE TITLE
variables are processed at the project level

### ISSUE THREAD

**Issue by SaMnCo** [cloudreach/sceptre#638]
Good morning all! First of all thanks for building this tool, it's been very good to us and made my life much much easier. 

I am now working on the migration from v1 to v2, and there is a change that is due to the global "graph" approach taken in v2 that impacts us negatively, and I am not sure if it is intended or not. 

Basically, I have a number of stacks in my Stack Group, and some of them have different variables than others. I am passing these variables to the stacks via sceptre_user_data: 

In a stack called local.yaml, I would have 
```(yaml)
sceptre_user_data:
  Environment: {{ var.stage }}-local
``` 

and other stacks won't use the variable, but rather something else

```(yaml)
sceptre_user_data:
  Environment: foobar
``` 

In the past, I was able to run

* for local:  `sceptre --var stage=MyStage generate-template local` 
* for others: `sceptre --var generate-template other-stack` 

But now, if I ommit `--var stage=MyStage` for other stacks, I get: 

```
$ sceptre generate other-stack
'dict object' has no attribute 'stage'
```

Now I understand why it happens, and the easy mitigation is to run it with a dummy stage variable. Nevertheless if feels wrong, since it basically means all stacks in a given group must share the same list of parameters (if shared via a var or var-file). 
I'd rather see these to be scoped to the context of the stack.

**Comment by ngfgrant** [comment]
Hey @SaMnCo really glad to hear that you are getting value for the project. Thanks for highlighting this and explaining well. I will look into see if there is a way we can scope vars scoped to the stack. 👍

**Comment by SaMnCo** [comment]
Morning! As I am moving further into v2, this issue is actually a big struggle. I got into another issue that seems related. 

Figure a config folder structured as: 

```bash
.
├── config.yaml
└── np
    ├── config.yaml
    └── eu-west-1
        ├── common
        │   └── waf.yaml
        ├── config.yaml
        ├── development
        │   ├── app.yaml
        │   └── sqs.yaml
        └── hotfix
            ├── app.yaml
            └── sqs.yaml
...
``` 

Now the app.yaml depends on queues.yaml, which I indicate in the config yaml via 

```
dependencies:
- {{ command_path.0 }}/{{ command_path.1 }}/{{ command_path.2 }}/queues.yaml
```

When I try to deploy the WAF via 

```
$ sceptre --debug launch np/eu-west-1/common/waf.yaml
```

I get 

```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sceptre/cli/helpers.py", line 37, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sceptre/cli/launch.py", line 35, in launch_command
    plan = SceptrePlan(context)
  File "/usr/local/lib/python2.7/dist-packages/sceptre/plan/plan.py", line 33, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/usr/local/lib/python2.7/dist-packages/sceptre/config/reader.py", line 212, in construct_stacks
    stack.dependencies = [stack_map[dep] for dep in stack.dependencies]
KeyError: 'np/eu-west-1/common/queues.yaml'
```

As you can see in the KeyError, Sceptre is trying to locate the queues.yaml in the common folder, which, if you look a the command passed, is logical. If you think about the renaming of variables (environment_path to command_path) it also does make sense. 
Except this change between v1 and v2 converts something that depended on the stack_group into something that is dynamically generated from the command passed. 

Of course I can work around this by setting the dependencies to the full "expanded" path, and it seems to be the expected logic. But I think it would then make sense to expand a bit in the docs to explain that command_path is effectively something that depends on the command, no more on the stack_group, and the potential consequences when dependencies are addressed with dynamic path like I used to. 

On a side note, this degrades error-proofing, since I am explicitely writing in the app.yaml parameters that were previously implicit.

**Comment by ngfgrant** [comment]
@SaMnCo thank you - again - for writing this up in a way that is easy to follow. I am now getting time to look at this in detail.

As you pointed out above, when you run a command with Sceptre v2 we generate a graph with the dependencies based on the original stack/stack group passed in. 

For example

```
SG_1/StackA -> SG_1/StackB
SG_1/StackB -> SG_2/StackC
SG_1/StackA -> SG_2/StackC  (note that StackC is in a different stack_group)
```

When we do `sceptre generate SG_1/StackA` sceptre will first aim to resolve the values from SG_1/StackB and SG_2/StackC before resolving SG_1/StackA. In order to resolve the values in StackB and StackC they need to have the variables either passed appropriately. 

We made a conscious decision to ensure dependency correctness in v2 and as a result of this it means, as you noted, that variables need to be passed if you expect this to resolve properly.

The way around this is to use `--ignore-dependencies`:

`sceptre --ignore-dependencies  generate SG_1/StackA` and you will only need to pass vars that relate to `SG_1/StackA` (if any).

A way support the v1 type of stack/stack-group level variables is to add support for a default `variables.yaml` file that would sit at the stack_group level. E.g.

```
.
├── SG_1
│   ├── StackA.yaml
│   ├── StackB.yaml
│   └── variables.yaml
└── SG_2
    ├── StackC.yaml
    └── variables.yaml
```

Sceptre would then read in the `variables.yaml` file when loading the stack and use the key:values to resolve the Stacks in a given StackGroup. This would be useful for having default static variable values. 

We could have the default behaviour read from `variables.yaml` (if there is one) otherwise could have the option `--use-var-file` which would work like: `sceptre --use-var-file=prod-variables.yaml generate SG_1/StackA`, so for the project structure below it would read in `prod-variables.yaml` rather than `variables.yaml` for SG1 and since `prod-variables.yaml` does not exist in `SG2` it will revert to using `SG_2/variables.yaml` instead.

 ```
.
├── SG_1
│   ├── StackA.yaml
│   ├── StackB.yaml
│   ├── prod-variables.yaml
│   └── variables.yaml
└── SG_2
    ├── StackC.yaml
    └── variables.yaml

```

What do you think?

**Comment by SaMnCo** [comment]
@ngfgrant thanks for looking into this, much appreciated. I wish I had a bit more time atm to give you a hand on this. 

Going back to the root cause of the issue, my understanding is that Sceptre v2 wants a holistic view of the application in order to generate any of its (sub)components, something that was not true in v1. 
This is made complex when the configuration tree itself is used to parametrize dependencies or other elements for obvious reasons. 
It's also made complex when all stacks do not share the same set of variables, in which case they must all be addressed with the combination of all possible variables. 

So what is needed is a way for Sceptre v2 to understand when a config parameter is local to the stack, or global to the app. 

The solution to add a `variables.yaml` file to the tree solves the issue of variables declared as --var foo=bar. This is due to the fact it's read from the Stack Group level (basically the file system location) and not the context. 

However, I don't think it addresses the graph generation issue where we now deploy only on the execution context (command_path). 
For this, one option could be to distinguish `command_path`, which should rightfully refer to the context of Sceptre when it's executed and the previous `stack_path` / `stack_group_path` which would refer to a location on the file system. 

This way if I do 

```
dependencies:
- {{ command_path.0 }}/waf.yaml
- {{ stack_path.0 }}/sqs.yaml
```

I am able to describe a dependency to the SQS stack located in the same stack_group as I am at "graph build time". This maps well to config trees that depend on AWS objects such as AZs and regions because SQS is a regional resource, and there is a good chance you locate it in the same region as your app.
While `waf.yaml` is loaded from the execution context at build time. This bodes well with global or account level resources that can be accessed cross-regions. 

From my perspective, this approach would sort of bring backward compatibility, and let users play with the new graph approach that brings better orchestration. 

Said otherwise, when I operate a structure based on account/region/az/stack.yaml, I always end up having a "common" stack_group for shared resources. 
Having the ability to have stack_path and command_path removes that requirement by letting me put by stack.yaml files directly in the folder where that resource is "global" and use command_path, while I can create local dependencies with stack_path. 

I hope this makes sense, and it does not feel too much like a step back. My understanding of this is really based on usage, I might miss a point somewhere. 

Happy to join a call or hangout to discuss since this might not be the most optimal way to share complex thoughts, and apologies I didn't have more time to dig into the code and make myself more relevant.

**Comment by ngfgrant** [comment]
@SaMnCo super no apologies needed that all makes sense. Let me dig back into the codebase, it may be trivial to allow users to reference `stack_path` as you've suggested.

**Comment by SaMnCo** [comment]
You know the more I think about this the more I think there might be a trivial way to work around all the problems I am having. This is actually something I thought about a while ago and it slipped away. 

When using templates, I have actually always been frustrated by the fact I can only access sceptre_user_data. 
Then in configuration, it's not possible to refer to other values of the config. 

But in fact, if you look at what Sceptre extracts for each stack it manipulates, we have a very verbose object. Below is an example from a quick and dirty template I am working on for AWS SFTP Transfer management: 

```
{   
	"profile": "development", 
	"template_bucket_name": "TemplateBucket", 
	"template_key_prefix": "sftp", 
	"stack_group_path": "development/eu-west-1", 
	"stack_name": "sftp-user", 
	"hooks": {
		"before_create": [<sceptre.hooks.cmd.Cmd object at 0x7f562d7805d0>]
	}, 
	"region": "eu-west-1", 
	"project_path": "/home/scozannet/Documents/src/foobar", 
	"parameters": {
		"UserName": "scozannet", 
		"S3Bucket": "sftpRoot", 
		"ReadOnly": "True", 
		"HomeDirectory": "/myHome", 
		"SshPublicKey": "ssh-rsa stuff", 
		"ServerId": <sceptre.resolvers.stack_output.StackOutputExternal object at 0x7f562d780b10>
	}, 
	"sceptre_user_data": {
		"Environment": "development", 
		"HostedZoneName": "not.used.com", 
		"Account": "development", 
		"Stage": "unused"
	}, 
	"project_code": "sc",
	"template_path": "sftp-user.yaml.j2"
}
``` 

Now if we had access to `this.config` everywhere (config and templates), we'd be the kings of the world. 

It's a breaking change for `sceptre_user_data`, that would become `this.config.sceptre_user_data`, but then I could also use `this.config.stack_group_path` and manipulate that string. 

Now if it was possible to use these within a config file (obviously a potential source of circular references but well, I didn't say it would be trivial :D ), then all problems would be solved since we'd have access to both file system data and execution context data.

This would be formidable imho. 

While I am at it, it might cause issues in Jinja2 templating, which this project https://github.com/jpscaletti/copier/ handles nicely by changing the default Jinja identifier to `[[ ]]` instead of `{{ }}`
This allows me to create cookie cutters for CF by combining Sceptre and Copier but personal story aside it might be useful to separate templating of config and templating of actual CF files. 

Anyway, random stream of consciousness in the morning...

**Comment by SaMnCo** [comment]
Aaaaand my bad... Some of these can already be used... 

It seems there is a subset of the config items that can be used in the config.yaml. So far the valid items I found are (in addition to sceptre_user_data) : 

```
{{ profile }} -> profile to use for this stack
{{ region }} -> deploy region for this stack
{{ template_bucket_name }} -> where the template will go
{{ template_key_prefix }} -> prefix
{{ project_path }} -> full path of the project (same as $(pwd) from where sceptre runs)
{{ stack_group_path }} -> path of the stack group relative to the project_path
{{ project_code }} -> code set in the config.yaml
{{ stack_group_config }} -> return a JSON object with all the previous elements (this is documented in templating) but also potential custom_keys
```

Now compared to command_path that returns as a list everything here returns as strings. So to use an element of the `project_path` in the config file you'd need a little jinja trick like: 

``` 
stack_name: SuperTest
parameters:
  Profile: {{ profile }}
  TemplateBucket: {{ template_bucket_name }}
  Region: {{ region }}
  FirstElementOfProjectPath: '{% set p = project_path.split('/') %}{{ p[1] }}'
  FirstElementOfStackGroupPath: '{% set p = stack_group_path.split('/') %}{{ p[0] }}'
  ProjectCode: {{ project_code }}
  TemplateKeyPredix: {{ template_key_prefix }}
template_path: sftp-user.yaml.j2
``` 

Note that the `project_path`, in this case, seems to be a full path, so starts with `/` which offset the first "real" element by 1, whereas `stack_group_path` is a relative, so no offset. 

So thank you for following up on this, it gave me an opportunity to do a bit more digging and this might help others with the same questions while a more robust solution is implemented.

**Comment by ngfgrant** [comment]
@SaMnCo cool thanks.

Also have a read of https://github.com/cloudreach/sceptre/issues/256. We've discussed in the past how to improve variables handling.

**Comment by ngfgrant** [comment]
Going to close this issue as I think the variables discussion is better had in #256
