### ISSUE TITLE
Variable precedence is not respected if using dicts

### ISSUE THREAD

**Issue by dmegyesi** [cloudreach/sceptre#641]
First of all, many thanks for your work on this project, it's an amazing tool!

I encountered an issue regarding variable precedence and I would like to clarify it. If this is a 'works as designed' case, I think it would be nice to highlight it in the documentation because it was not very clear.

My use-case: 
- I'm using a `--var-file` + additionally override some variables with `--var` in the CLI

Turns out, if you have nested variables (dict), you cannot override them in CLI:

my-varfile:
```
aws:
  accounts:
    id: 1
  something-else: foo
  another:
    thing: bar
```

`sceptre --varfile my-varfile --var aws.accounts.id=2 …`

This will completely ignore your `--var` command, even though it is [supposed](https://sceptre.cloudreach.com/latest/docs/stack_group_config.html) to have the highest precedence:

> Both the --var and --var-file flags can be used multiple times. If multiple --var-file options are supplied, the variables from these files will be merged, with a higher precedence given to options specified later in the command. Values supplied using --var take the highest precedence and will overwrite any value defined in the variable files.

It only works if the variable is at the root level (the entire `aws` block for example).

The `--debug` output lets you know this: `Duplicate variables encountered: aws. Using values from: variables/vars.yaml.`

Would it be possible to evaluate these custom `--var` calls and merge them with the already parsed dict of the `--varfile`? I think it could be a nice to have default feature.

Many thanks for your help in advance!

**Comment by ngfgrant** [comment]
@dmegyesi I am working on this at the moment and fortunately it won't introduce breaking changes as users won't be able to have `.`'s in their variable names as they wouldn't be processed properly by jinja. This should be out in `2.1.4`
