### ISSUE TITLE
Is there a reason to pin colorama?

### ISSUE THREAD

**Issue by h1f1x** [cloudreach/sceptre#644]
After upgrading my python env (3.6) with pip (pip3 install --upgrade boto3 awscli), sceptre don't run anymore (see below).
Is there a reason why to pin the colorama version to exactly one (old) version? 

sceptre --dir cfn/ launch -y dev

> Traceback (most recent call last):
>   File "/usr/bin/sceptre", line 11, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 37, in decorated
>     return func(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/sceptre/cli/launch.py", line 35, in launch_command
>     plan = SceptrePlan(context)
>   File "/usr/lib/python3.6/site-packages/sceptre/plan/plan.py", line 32, in __init__
>     config_reader = ConfigReader(context)
>   File "/usr/lib/python3.6/site-packages/sceptre/config/reader.py", line 106, in __init__
>     ["sceptre.hooks", "sceptre.resolvers"]
>   File "/usr/lib/python3.6/site-packages/sceptre/config/reader.py", line 150, in _add_yaml_constructors
>     node_class = entry_point.load()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2290, in load
>     self.require(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2307, in require
>     items = working_set.resolve(reqs, env, installer)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (colorama 0.3.9 (/usr/lib/python3.6/site-packages), Requirement.parse('colorama==0.3.7'))

**Comment by ngfgrant** [comment]
Hey @h1f1x - generally the reason to pin an exact pre 1.0.0 version of a package is that there is no guarantee of backward compatible changes between versions. In this case I think we should be ok to update to 0.3.9 but would need to test etc.

**Comment by h1f1x** [comment]
Tahnks @ngfgrant. Isn't this covered by tests in tests/ ;)

**Comment by ngfgrant** [comment]
Parts of the output from the library are covered in some tests but it still doesn't negate the better practice of pinned unstable APIs. I'll pop in a PR to update this to 0.3.9.

**Comment by h1f1x** [comment]
Thanks! :)
