### ISSUE TITLE
update-env-cs

### ISSUE THREAD

**Issue by johnculkin** [cloudreach/sceptre#65]
It would be nice to have a way to update an environment from the CLI. Ideally this would step me through Change Sets for the stacks in that env that had changes. 

I realize that launch-env can update an environment but there would never be a need for a change set when creating a stack so I think we need update-env - thoughts?

**Comment by theseanything** [comment]
Good idea! Probably something easier to implement once we do the cli refactor - #60

**Comment by ryanpagel** [comment]
I'd really like to see something like this as well.  launch-env is very useful but also nerve-wracking because it may make a lot of unintentional changes without giving the benefit of a changeset diff.

**Comment by ngfgrant** [comment]
Closing #520 will deal with this in v2.
