### ISSUE TITLE
Generate Command

### ISSUE THREAD

**Issue by luketn** [cloudreach/sceptre#658]
Tried to run:
```
sceptre --output yaml generate ap-southeast-1/waf.yml
```

Fails to write the generated template (no error message).

Without the output statement it writes a strange array of resources which are escaped.

**Comment by maheshbisl** [comment]
$ sceptre --output yaml generate ap-southeast-1/waf.yaml
/usr/local/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):
An error occured whilst writing the YAML object.
An error occured whilst writing the YAML object.

**Comment by ngfgrant** [comment]
Hey @luketn and @maheshbisl 

I can't seem to reproduce this. @luketn could you try using `.yaml` instead of `.yml`?

@maheshbisl could you try copy and paste `ap-southeast-1/waf.yaml` into an online yaml validator or use a library to check that your file contains valid yaml?

If possible could you share the `ap-southeast-1/waf.yaml` file (assuming it doesn't contain anything sensitive)?

**Comment by maheshbisl** [comment]
Maheshs-MacBook-Pro:bentobox mbisl$ sceptre --output yaml generate ap-southeast-1/cloudtrail.yaml 
/usr/local/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 
'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):
An error occured whilst writing the YAML object.
An error occured whilst writing the YAML object.
--- []

**Comment by maheshbisl** [comment]
Maheshs-MacBook-Pro:bentobox mbisl$ cat config/ap-southeast-1/cloudtrail.yaml 
dependencies:
- ap-southeast-1/circleci-user.yaml
sceptre_user_data:
  Dependencies:
  - circleci-user
  HostedZoneName: meteorscout.org
  Subnets: 2
  fileName: /tmp/bentobox/templates/cloudtrail_ap-southeast-1_realised.yaml
  region: ap-southeast-1
  sceptre_stack_group_dir: /tmp/bentobox/config/ap-southeast-1
  stack: cloudtrail
  stackName: cloudtrail
stack_name: cloudtrail
template_path: /tmp/bentobox/templates/cloudtrail_ap-southeast-1_realised.yaml
Maheshs-MacBook-Pro:bentobox mbisl$

**Comment by maheshbisl** [comment]
Maheshs-MacBook-Pro:bentobox mbisl$ cat templates/cloudtrail_ap-southeast-1_realised.yaml

AWSTemplateFormatVersion: 2010-09-09
Description: Cloudtrail by Bentobox

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Trail Configuration
        Parameters:
          - EnableLogFileValidation
          - IncludeGlobalEvents
          - MultiRegion
      - Label:
          default: Delivery Notifications
        Parameters:
          - PublishToTopic
          - NotificationEmail
    ParameterLabels:
      EnableLogFileValidation:
        default: Enable log file validation
      IncludeGlobalEvents:
        default: Include global service events
      MultiRegion:
        default: Is this a multi-region trail
      PublishToTopic:
        default: Send notifications to SNS
      NotificationEmail:
        default: Notification Email (optional)

Parameters:
  EnableLogFileValidation:
    Type: String
    Default: False
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - True
      - False

  IncludeGlobalEvents:
    Type: String
    Default: False
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - True
      - False

  MultiRegion:
    Type: String
    Default: True
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    AllowedValues:
      - True
      - False

  PublishToTopic:
    Type: String
    Default: False
    Description: Indicates whether notifications are published to SNS.
    AllowedValues:
      - True
      - False

  NotificationEmail:
    Type: String
    Default: infrastructure@infomedia.com.au
    Description: Email address for notifications (for new topics).

Conditions:
  IsMultiRegion: !Equals
    - !Ref MultiRegion
    - True
  Publish: !Equals
    - !Ref PublishToTopic
    - True
  CreateSubscription: !And
    - !Condition Publish
    - !Not
      - !Equals
        - !Ref NotificationEmail
        - ''

Resources:
  TrailBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSTrailBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${TrailBucket}"
          - Sid: AWSTrailBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*"

  TrailTopic:
    Condition: Publish
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS CloudTrail Notification Topic

  TrailTopicPolicy:
    Condition: Publish
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref TrailTopic
      PolicyDocument:
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Action:
              - sns:Publish
            Effect: Allow
            Resource: !Ref TrailTopic
            Principal:
              Service:
                - cloudtrail.amazonaws.com

  EmailNotification:
    Condition: CreateSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref NotificationEmail
      Protocol: email
      TopicArn: !Ref TrailTopic

  Trail:
    DependsOn:
      - TrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref TrailBucket
      SnsTopicName: !If
        - Publish
        - !GetAtt TrailTopic.TopicName
        - !Ref AWS::NoValue
      IsLogging: true
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !If
        - IsMultiRegion
        - true
        - !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion

Outputs:
      bucket:
          Value: !Ref TrailBucket
          Export:
              Name: CloudtrailBucket

**Comment by maheshbisl** [comment]
@ngfgrant , please check the above three comments.

**Comment by stolendog** [comment]
the same here

**Comment by akamel001** [comment]
Getting the same issue here.

**Comment by cristiangauma** [comment]
Same here. We have not been able to create Yaml or Json outputs for a while. Text output works properly. 

We have created a script that converts text output to Yaml (using only sed), and it results with a well-formed yaml file. 

Cloudformation validation works too, as all our templates are Yaml, so I guess it is the "sceptre --output" part the one that is creating a bad Yaml.

> An error occured whilst writing the YAML object.
> --- []

**Comment by ngfgrant** [comment]
I'll have a look at this - we are using PyYaml behind the scenes so there might be an issue there.

**Comment by zaro0508** [comment]
This might be related to issue #710
