### ISSUE TITLE
Check return code for hooks

### ISSUE THREAD

**Issue by winjer** [cloudreach/sceptre#66]
When a hook is run on `before_create` or `before_update`, sceptre should check for a return code and abort the stack create or update and abort if the result is non-zero.

Currently even if a hook fails the stack operation proceeds.

**Comment by jamesroutley** [comment]
Hi @winjer good point. We do actually have [code](https://github.com/cloudreach/sceptre/blob/master/sceptre/hooks/bash.py#L28) in Sceptre to do this, but I don't think there's a way for users to enable the feature (!). @seanrankine do you want to take this one?

**Comment by theseanything** [comment]
Sorry for the delay @winjer! So assuming you are talking about `bash` hooks, stopping a stack action on a non zero return code is partially implemented. We'd need to discuss how we enable this behaviour - do we want this by default? How do we toggle this behaviour - in the config, environment variable etc...? 

Btw - if your talking about custom hooks, you can raise an exception to interrupt a stack action. But not this won't stop a whole environment action - just the specific stack.

**Comment by jamesroutley** [comment]
What about two different resolvers? It's explicit, doesn't require any extra config parsing, doesn't require environment variables which are easy to forget to set. Almost all of the code could be pulled into a base class.

**Comment by theseanything** [comment]
Ah sorry @jamesroutley you mean two different hooks? But yeah for Bash it would be a easy way to implement it!

**Comment by jamesroutley** [comment]
Sorry yeah - two different hooks. Something like `bash` and `bash-ignore-nonzero`?

**Comment by jamesroutley** [comment]
Quick update on this:

We agree that the default behaviour should be to throw an error if a command returns non-zero. Currently, Sceptre just [`subprocess.call()`s](https://docs.python.org/2/library/subprocess.html#subprocess.call) the command. Despite the resolver being called `bash`, there's no guarantee that the shell used will be `bash`, and the resolver should also work for PowerShell.

We will therefore deprecate this resolver (so as to not introduce a breaking change), and introduce a new resolver named `cmd` which subprocesses the command, and checks the return code.

**Comment by jamesroutley** [comment]
v1.2.0 Adds a new `cmd` hook, which checks the return code of the command run.
