### ISSUE TITLE
Caching in CI for Docs 2.0 

### ISSUE THREAD

**Issue by 1oglop1** [cloudreach/sceptre#660]
At the moment Docs are always built from fresh clone.
Which might impact performance at some point.

Let's measure current implementation to see if we need to implement caching.

Details for implementation:

- require changes in `.circleci/github-pages.sh`
specifically `git` operations which would need to adapt based on the information whether it's fresh clone or update and handle corner cases to merge differences between cached docs and actual repository state.

**Comment by ngfgrant** [comment]
Looking at the last couple of builds the build took ~30s and deploying docs takes around 50s. I think we can live with these times for now given the integration tests take 15 mins :P. Closing for now.
