### ISSUE TITLE
Use non-prerelease version of Pyyaml

### ISSUE THREAD

**Issue by myoung34** [cloudreach/sceptre#665]
Currently the pyyaml version in setup.py specifies `PyYaml>=4.2b1,<5.0` which are all set as pre-release.

This causes problems with things that care about pre-release (like Pipenv etc).

Is it possible to pin to non-pre version 5.1 of PyYaml?

**Comment by cczimskey** [comment]
We see similar behavior, as we also use pipenv to help segregate different projects.  Would be nice to have this updatd as above so pipenv install doesn't always fail on the required pyyaml version.

**Comment by ngfgrant** [comment]
Thanks for your patience on this everyone. 

The background to this is that a vulnerability was discovered in PyYaml (https://github.com/yaml/pyyaml/issues/243)

There was a plan in the PyYaml community to do a 4.2 release (https://github.com/yaml/pyyaml/issues/193) although it appears they've needed to release a major version with some backward incompatible changes (https://github.com/yaml/pyyaml/issues/265).

It looks like 5.1 is out and I've added the appropriate changes into 2.1.1 release plan.

Longer term I would be open to moving to rumel or something else. PyYaml for now seems to be all over the place.
