### ISSUE TITLE
'sceptre delete' does not take the dependencies into account 

### ISSUE THREAD

**Issue by maheshbisl** [cloudreach/sceptre#670]
Thanks for the great product.

I would expect 'sceptre delete --yes <stack group>' to delete the stacks in the order of dependency.

Otherwise, the deletion fails because if we have used "Export" and "ImportValue".

Please look into fixing this.

Thanks again

**Comment by ngfgrant** [comment]
Hey @maheshbisl 

Thanks for your kind feedback.

If I recall correctly we did implement delete to delete in order of dependency (implicit or explicit). Could you share an example of your setup? For me the deletion ordering works.

Cheers,
Niall

**Comment by maheshbisl** [comment]
No worries. Thanks.
