### ISSUE TITLE
Set output format at config.yaml Level

### ISSUE THREAD

**Issue by nmyster** [cloudreach/sceptre#672]
Coming from using Sceptre v1 a lot to 2.0 I have noticed the move towards favouring text output as the default output_format rather than JSON as it was before. 

It took me a little while to figure out that a lot of my commands looked broken as I was not setting an `--ouput` flag on my commands to JSON (or YAML) and since getting used to it, It has occurred to me that at a project level and even at a Stack level, it would be really useful to be able to set this once and not have to worry about setting a flag each time.

I would like to be able to set this using something like `output` or `output_format` at my `config.yaml` files and then utilise this as my preferred option over setting --output.

Cascading config should still work and maybe if --ouput is set, it overrides any value in the config.

**Comment by nmyster** [comment]
PR Raised to get this implemented. #673

**Comment by ngfgrant** [comment]
relates to https://github.com/cloudreach/sceptre/issues/152
