### ISSUE TITLE
Is Sceptre 'smart enough' to know when changes have been made?

### ISSUE THREAD

**Issue by thomas-ncino** [cloudreach/sceptre#676]
Hello! My team and I are evaluating Sceptre, and we wanted to know if using the `sceptre create` command would evaluate the current templates for changes. In the documentation, it states `Creates a stack or a change set.` -> does this imply that sceptre will automatically know if there has been changes?

**Comment by 1oglop1** [comment]
I don't think it's an automatic process.
However when you a `change set` Sceptre will prompt you the same way Cloudformation does about changes sets. 
And you can evaluate whether you want to proceed with the execution of change set or not.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html

**Comment by ngfgrant** [comment]
Hey @thomas-ncino the create command is as follows:

`sceptre create [OPTIONS] PATH [CHANGE_SET_NAME]`


which means if you specify a change set name as part of the command then it will create a change-set which you can then later execute with the `execute` command. 

Hope that helps?

**Comment by thomas-ncino** [comment]
Thanks @1oglop1 and @ngfgrant for your help!
