### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#68]
Support to launch ARM Templates. Provide multi-cloud support for projects. 

Initially looking to add support for:
create-stack
update-stack
delete-stack

With templates being uploaded to Azure Blob storage.

**Comment by jamesroutley** [comment]
Agreed. Wanna add this to 2.0?

**Comment by jamesroutley** [comment]
Let's define a subset of our commands to add support for?
```
create-stack
update-stack
delete-stack
```
to start with?

**Comment by theseanything** [comment]
I'm hesitant to add to 2.0 - purely due to the time commitment required to implement this. I'd say its a stretch goal

**Comment by theseanything** [comment]
Because this be a lot pull requests to get the overall functionality working - shall we do a separate azure milestone?

**Comment by jamesroutley** [comment]
Yep.

**Comment by theseanything** [comment]
Along with the milestone - can have a separate azure-support branch to run along side and ultimately will get merged into master? But we can merge all the bits and pieces for azure support into that that?

**Comment by jamesroutley** [comment]
More info [here](https://trunkbaseddevelopment.com/feature-flags/)

**Comment by theseanything** [comment]
Yeah - I was thinking how we go about managing the code and the PRs. As we are trying to go the smaller PR route - to even start to get the base functionality working it's going to take quite a few PRs.

I just want to somewhat maintain the integrity of the master branch - as we'll do minor releases alongside. Yeah there will be a bigger merge at the end - but can avoid issues if keep the azure-branch is kept up to sync with master.

**Comment by b-t-g** [comment]
Just to add a note from a conversation earlier.

Whatever we do should be done with an eye towards multi-cloud provider deployments as that is a principle gaining traction as a best practice in some circles. Locking ourselves to 1 cloud provider per stack or environment could be limiting for that use case. The first release of it needn't necessarily have multi provider deployments, but the core abstractions shouldn't prohibit the possibility.

**Comment by ngfgrant** [comment]
Closing because it is a significant move away from the current project's goals. Maybe something that could be considered in the future or a separate tool.

**Comment by JuanCanham** [comment]
I know sceptre is not a direct competitor to terraform, but supporting multiple clouds is a strong reason to use it over sceptre.
