### ISSUE TITLE
Documentation for Custom Hooks is incorrect

### ISSUE THREAD

**Issue by cczimskey** [cloudreach/sceptre#684]
The current custom hook documentation in these locations is not valid for Sceptre v2:
https://github.com/cloudreach/sceptre/blob/master/docs/docs/hooks.md
https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2

Still shown in the code example:
```
class CustomHook(Hook):

    def __init__(self, *args, **kwargs):
        super(CustomHook, self).__init__(*args, **kwargs)

    def run(self):
        """
        run is the method called by Sceptre. It should carry out the work
        intended by this hook.

        self.argument is available from the base class and contains the
        argument defined in the Sceptre config file (see below)

        The following attributes may be available from the base class:
        self.stack_config  (A dict of data from <stack_name>.yaml)
        self.stack.stack_group_config  (A dict of data from config.yaml)
        self.connection_manager (A connection_manager)
        """
        print(self.argument)
```

We are migrating from v1 -> 2 and having to redo all of our hooks and resolvers.  Trying to call:
`self.stack_config['parameter']['<value>']`
Failed with the error:
`AttributeError: '<customHook>' object has no attribute 'stack_config'`

The fix for me was to use: 
`self.stack.parameters['<value>']`

I found the options in:  `sceptre/sceptre/stack.py`

Can we please have the documentation updated to look in that file for options?  Something like:
```
    def run(self):
        """
        run is the method called by Sceptre. It should carry out the work
        intended by this hook.

        self.argument is available from the base class and contains the
        argument defined in the Sceptre config file (see below)

        For a full list of additional attributes, please see the file: sceptre/sceptre/stack.py
        Attributes will be called by using:
        self.stack.<parameter>
        """
```

Appreciate all of your hard work, thanks!

**Comment by tabuchid** [comment]
@cczimskey I put up a PR awhile back for this. Does https://github.com/cloudreach/sceptre/pull/664 handle this for you?

**Comment by cczimskey** [comment]
That would probably work, thanks!

**Comment by 1oglop1** [comment]
Thanks,
 I'll look into it once we merge #655
