### ISSUE TITLE
sceptre create returns code 1 and fails Jenkins pipelines

### ISSUE THREAD

**Issue by grasum** [cloudreach/sceptre#688]
Using sceptre 2.1.0 all create stack operations return the code 1 even though they are successfull and all resources are created. 

This seems to be the case only with create. Update and delete work fine.

This is problematic when using Jenkins pipelines. Creating a resource in one pipeline stage will exit with code 1, failing the pipeline, before it can be finished. We implemented a workaround but is really tedious. Is it possible to be fixed?

![image](https://user-images.githubusercontent.com/29518068/56734142-bdcc7c00-676a-11e9-8c01-16f73003fa8f.png)

**Comment by ngfgrant** [comment]
Hey @grasum 

Could you check to see if this problem still exists with `launch` command - which acts as an "upsert" type of command. Our `create` command mimics aws and will fail if the resource already exists which might explain the issue you are describing?

I will look into this in the meantime to see if there is something more sinister at play ;)

**Comment by grasum** [comment]
Hey
No, the problem does not exist when running with ''launch''. Thanks for the suggestion!

Although we'd prefer sometimes to launch stacks using 'create', because we had a lot of dependency issues (since upgrading to sceptre 2.x from 1.4.2 ) when running with ''launch''. We are still trying to sort those error out, but for the time being we mostly use 'create'. It would be great if that pesky return code can be fixed

**Comment by ngfgrant** [comment]
@grasum I think we will keep the code as it is for now otherwise the `create` command will behave a bit like launch. 

you could do `sceptre --ignore-dependencies launch <stack/stack_group>` and that will only launch a single stack or stack group.

**Comment by grasum** [comment]
I understand. Thank you for your suggestions !
