### ISSUE TITLE
launche sceptre template from s3

### ISSUE THREAD

**Issue by laur1s** [cloudreach/sceptre#690]
I use sceptre to launch multiple stacks for dev/prod environments. However, one of the stacks is too long: ` templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200 ` How can I use sceptre from s3 to solve this issue? 

The template I have is a jinja file where I populate the permissions policy with a for loop. That's why it's quite long

**Comment by laur1s** [comment]
I also tried to run `sceptre generate EC/TEST/elasticsearch.yaml | aws s3 cp - s3://my-bucket/template.yaml` However, Sceptre generate produces malformed YAML file `['AWSTemplateFormatVersion: \'2010-09-09\'\nDescription: ElasticSearch dev service stack\n\nPara`

**Comment by ngfgrant** [comment]
Hey @laur1s - sceptre should upload the template to s3 for you for this reason. What is the command you are using?

**Comment by laur1s** [comment]
I use `sceptre launch`

**Comment by ngfgrant** [comment]
Strange... Can you run `sceptre validate EC`?

**Comment by laur1s** [comment]
It only produces error that the template is too long ` at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200` If I make my template shorter by removing some arguments from elasticsearch policy it works

**Comment by craighurley** [comment]
@laur1s have you defined `template_bucket_name` in your [sceptre group config](https://sceptre.cloudreach.com/latest/docs/stack_group_config.html#template_bucket_name)?

**Comment by ngfgrant** [comment]
@laur1s yes sorry got ahead of myself @craighurley is correct you will need to specify `template_bucket_name` - in this case it is probably the case it hasn't been specified.

**Comment by laur1s** [comment]
Thanks  @craighurley and @ngfgrant . That's the issue I had
