### ISSUE TITLE
Sceptre cannot upload templates to S3 if running on Windows

### ISSUE THREAD

**Issue by lukeplausin** [cloudreach/sceptre#703]
I'm using sceptre to launch some templates via an S3 bucket from a windows machine. I'm using git bash for windows. Sceptre fails to upload the template as it tries to put the windows path separator into the URL.

`sceptre --debug launch dev/mystack.yaml -y`

The output looks like this:

```
[2019-05-13 11:04:02] - Uploading template to: 's3://mybucket/myprefix/dev\mystack/2019-05-13-10-04-01-977892Z.json'
[2019-05-13 11:04:02] - s3-deployment - Template URL: 'https://mybucket/myprefix/dev\mystack/2019-05-13-10-04-01-977892Z.json'
An error occurred (ValidationError) when calling the UpdateStack operation: TemplateURL must be an Amazon S3 URL.
```

I'd guess that it's a simple case of replacing the path separator but I'm not sure where to make the change.

**Comment by ngfgrant** [comment]
@lukeplausin what is the `template_path` key in your config?

**Comment by lukeplausin** [comment]
`template_path: mystack.yaml`

**Comment by lukeplausin** [comment]
ie. no path separators in the `template_path` variable

**Comment by ngfgrant** [comment]
Which version of sceptre are you using?

**Comment by lukeplausin** [comment]
2.1.2

**Comment by ngfgrant** [comment]
ok I will have a look - looks like a cheeky windows separator is making it into the upload path. Should be a quick fix.
