### ISSUE TITLE
Ability to use resolvers in template_path

### ISSUE THREAD

**Issue by emiliogarcia** [cloudreach/sceptre#71]
Ability to generate the values for the template_path dynamically using a resolver. And in general to use resolvers for more configuration elements.

**Comment by theseanything** [comment]
@emiliogarcia could you give a few example for this use case?

**Comment by emiliogarcia** [comment]
For example if I want to find a template location based in parameters. Think this way in natural language: "I want the template to create VPCs, approved by InfoSec, version 1.3."

!template_locator: "VPC, Infosec, 1.3"

And now think your templates in real life are split across many locations, that they are not fully standardised, etc.

**Comment by theseanything** [comment]
Yeah, this is interesting. I think we need to look at ultimately what we want to achieve. It could be a way to implement the remote template idea #26. Could you give more details of what your resolver does/where is fetching the template from (s3, locally etc...)?

**Comment by emiliogarcia** [comment]
You have a good point. I think ultimately the objective here would be to provide with the user with the freedom to implement their own custom remote template engine/logic/repository. This being a particular use case where you add some abstraction between the filesystem and your template "repository".

**Comment by ngfgrant** [comment]
Closing because it is not clear that this adds the value compared to the effort required. However, there is likely a more elegant solution to address this issue (as well as other similar issues).
