### ISSUE TITLE
Overwritten project_code in stack_output dependencies

### ISSUE THREAD

**Issue by cornerman** [cloudreach/sceptre#725]
When defining an implicit dependency via `!stack_output` from another another stack-group, the `project_code` of the current stack-group seems to be overwriting the `project_code` of the dependency - yielding a stack cannot be found error when deploying.

I have the following project structure
```
config/
  stage/
    config.yaml # project_code: {{ var.Stage }}
    stack.yaml # !stack_output: environment/stack.yaml::Output 
  environment/
     config.yaml # project_code: "Global"
     stack.yaml
```

My example is a bit more complex, but generally I have a stage stack-group of which we have multiple deployments (named after the Stage var). And we have an environment, which is deployed only once, so the project_code is static. Stage depends on some global resources and expects them to be only created once even when used by multiple stages.

But somehow, sceptre does not use `project_code` defined in `environment/` when resolving `stack_output` in `stage/stack.yaml`. I have made a workaround with `dependencies` and `stack_output_external` to make it work. So the problem seems to be in the `stack_output` resolver itself, because `dependencies` are properly namespaced.

*Reproduction:* I have added failing test-cases to my sceptre fork to make the issue visible: https://github.com/cornerman/sceptre/commit/8a390eb29324a50090bccdb0ab399e3af3d7b99d

*Version:* Sceptre, version 2.1.3

Am I overlooking something?

**Comment by ngfgrant** [comment]
Will be released in 2.1.4
