### ISSUE TITLE
Access stack_group_config in stack group config

### ISSUE THREAD

**Issue by cornerman** [cloudreach/sceptre#729]
Can we somehow access other stack-group-config values within a config.yaml?

Example `config.yaml`:
```yaml
project_code: "Bla" # may be overwritten in a stack-group-config beneath this one
template_bucket_name: {{ stack_group_config.project_code }}-cloudformation-templates
```

**Comment by ngfgrant** [comment]
I think this is the same request in https://github.com/cloudreach/sceptre/issues/624 and https://github.com/cloudreach/sceptre/issues/355 will close for now.
