### ISSUE TITLE
Select multiple stack-groups with CLI

### ISSUE THREAD

**Issue by cornerman** [cloudreach/sceptre#737]
I would like to launch multiple stack-groups together by providing multiple arguments to sceptre:
```
sceptre target1/A.yaml target2
```

It would come pretty handy in some settings. I know I could group things under one folder, but it is not that flexible and also leads to large folder hierarchies and therefore long stack-names.

**Comment by ngfgrant** [comment]
Hey @cornerman probably not going to support this anytime soon. Could easily run with `sceptre launch target1/A.yaml` then `sceptre launch target2`. there is then issues with things like output and adding variables. just going to be messy...
