### ISSUE TITLE
Sceptre version 2.1.1 breaks backward compatibility with paths ending in trailing slash

### ISSUE THREAD

**Issue by jfarr** [cloudreach/sceptre#740]
I started getting the following error after upgrading to version 2.1.1:

```
'dev/' is an invalid path string. Paths should not have trailing slashes.
```

This worked fine in 2.1.0. Removing the trailing slash is not a workaround due to the way sceptre resolves paths by prefix matching. If I have a stack group named `dev` and a stack group named `dev-private` then running `sceptre launch dev` will launch *both* stack groups. The trailing slash in `sceptre launch dev/` is necessary to disambiguate. (See https://github.com/cloudreach/sceptre/issues/546) This completely breaks all of our sceptre-based deployment automation.

**Comment by ngfgrant** [comment]
https://github.com/cloudreach/sceptre/pull/731 Fixes the issue regarding exact stack names. Allowing the forward slash was a bug. Fix above due out soon.

**Comment by jfarr** [comment]
Thanks for the quick response @ngfgrant, I'll wait for that fix to come out then. I wasn't sure what the right fix was so I figured I'd log an issue before attempting a PR myself, glad it's already being taken care of. Really great tool so far BTW, please keep up the good work!

**Comment by ngfgrant** [comment]
Thank you for raising it @jfarr please point out anything else you come across that doesn't look right!
