### ISSUE TITLE
Split code for CLI and core functionality into separate repositories.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#76]
Sceptre officially supports use via the CLI and as a Python module. This leads difficulty with versioning as we are versioning two APIs with one version number. A breaking change to the Python API would require a major version bump, even though the CLI API (which is the only thing users care about if they don't use Sceptre as a Python module) remains the same. 

Splitting Sceptre into two packages, `sceptre` (cli code) and `sceptre-core` (Python module code) would solve this issue.

# Implementation

A new repo, `sceptre-core` would be created. All of the code, except `cli.py` would be moved to this repo. `sceptre-core` would be added to PyPI as a separate package, named `sceptre-core`. `sceptre` would contain the CLI code, which is already contained in its own module, `cli.py`. `cli.py` would have a dependency on `sceptre-core`.

This doesn't change how CLI users install Sceptre - `pip install sceptre` will do the same thing.

# Pros
- Corrects versioning issue

# Cons
- Adds complexity
- Project management split over two repos - do we have two Issues pages? I imagine we'll get a lot of Issues on `sceptre` which really belong in `sceptre-core`. Maybe we should have a single Issues page?

**Comment by jamesroutley** [comment]
Sceptre officially supports use via the CLI and as a Python module. This leads difficulty with versioning as we are versioning two APIs with one version number. A breaking change to the Python API would require a major version bump, even though the CLI API (which is the only thing users care about if they don't use Sceptre as a Python module) remains the same. 

Splitting Sceptre into two packages, `sceptre` (cli code) and `sceptre-core` (Python module code) would solve this issue.

# Implementation

A new repo, `sceptre-core` would be created. All of the code, except `cli.py` would be moved to this repo. `sceptre-core` would be added to PyPI as a separate package, named `sceptre-core`. `sceptre` would contain the CLI code, which is already contained in its own module, `cli.py`. `cli.py` would have a dependency on `sceptre-core`.

This doesn't change how CLI users install Sceptre - `pip install sceptre` will do the same thing.

# Pros
- Corrects versioning issue

# Cons
- Adds complexity
- Project management split over two repos - do we have two Issues pages? I imagine we'll get a lot of Issues on `sceptre` which really belong in `sceptre-core`. Maybe we should have a single Issues page?

**Comment by jamesroutley** [comment]
Documentation will be split between the two packages. The CLI package will contain most of the current docs: 
- intro
- install
- get started
- terminology
- cli api
- environment config
- stack config
- templates
- advanced patterns
- faq
- contributing

This documentation will be written without Sphinx. Sphinx isn't suitable for our Click CLI documentation ( #28 , #31  ). 

Core documentation will contain:

- using Sceptre as a python module
- Python API

These docs will use Sphinx, for the automatic API generation.

Each set of documentation will like to the other.

**Comment by geeknam** [comment]
This makes a lots sense. It's probably a similar approach to how docker-py and docker-compose are split. Maybe have a look how the docker community manages two repos.

**Comment by jamesroutley** [comment]
Thanks @geeknam! User feedback like this is super useful for us.
