### ISSUE TITLE
CLI Helper missing !Split Intrinsic Function

### ISSUE THREAD

**Issue by henkler** [cloudreach/sceptre#767]
sceptre/cli/helpers.py

The CFN_FNS array that lists the allowed functions does not include the 'Split' intrinsic function.

When generating template output from code that utilizes this intrinsic function, an Exception is raised instead of the template being output.

The CFN_FNS array should probably be updated to:
`
CFN_FNS = [
    'And',
    'Base64',
    'Cidr',
    'Equals',
    'FindInMap',
    'GetAtt',
    'GetAZs',
    'If',
    'ImportValue',
    'Join',
    'Not',
    'Or',
    'Select',
    'Split',
    'Sub',
    'Transform',
]
`

**Comment by ngfgrant** [comment]
@worr would you be able to check this out, should be a reasonably simple fix?

**Comment by worr** [comment]
Done, see #768
