### ISSUE TITLE
Nest stack statuses to enhance `describe-env` console output

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#8]
Console output is currently returned as a flat dictionary of stack_name: status. Instead return a nested dict which would indicate each stack's relationship to the others with less text.

**Comment by jamesroutley** [comment]
I'm no longer convinced this is a good idea - I had a look at the implementation and it would require a lot of changes - this doesn't neatly marry with the way we currently recurse down environments. Also I think there's a benefit to having full stack names printed so users can e.g. copy and paste them easily.

**Comment by jamesroutley** [comment]
I say "I'm no longer" because I originally opened this Issue on BitBucket.

**Comment by theseanything** [comment]
We can close this and reopen if need be.
