### ISSUE TITLE
Support for all autoscaling suspend and resume processes

### ISSUE THREAD

**Issue by pinkieee** [cloudreach/sceptre#87]
The built-in sceptre hook asg_scheduled_actions supports only suspending and resuming scheduled actions of an autoscaling group. There are more scaling processes that can be suspended/resumed as listed on the following page:

http://docs.aws.amazon.com/autoscaling/latest/userguide/as-suspend-resume-processes.html

It would be nice to have support for all the processes in a sceptre hook.

**Comment by johnculkin** [comment]
That is a great idea!

**Comment by theseanything** [comment]
#88

**Comment by jamesroutley** [comment]
@seanrankine #88 has been merged - can we close this issue?

**Comment by theseanything** [comment]
PR Merged
