### ISSUE TITLE
Allow the referencing of Cloudformation outputs from a separate AWS Account

### ISSUE THREAD

**Issue by chad-cook** [cloudreach/sceptre#89]
**Description of Improvement**
Allow the referencing of cloudformation outputs from a separate AWS Account.

**Situation for Improvement**
- Consider we have two AWS accounts both are controlled 100% by a CICD pipeline.
- Account-A deploys Cfn-Stack-A with SecurityGroup-A.
- Account-B deploys Cfn-Stack-B with SecurityGroup-B. Security-Group-B wants to add Security-Group-A inbound on port 80.

**Suggested Solution**
- This could be solved in two ways.
-- Use IAM cross account access to enable the account running sceptre to assume the role while fetching the output.
-- Enable the passing of a AWS profile for the other account to retrieve the other output.

**Comment by theseanything** [comment]
Hey @chad-cook, thanks for the input! Yup, better support for multiple AWS account would be great! For now, a quick fix could be to implement this as [custom resolver](http://sceptre.cloudreach.com/docs/advanced_patterns.html#custom-resolvers)... which basically let you run whatever python code to get a value. 

Improved core functionality would be something definitely worth looking at longer term. We'd need to think about how to handle the credentials for multiple accounts and how the syntax should look for this functionality. I'd lean towards using different AWS profiles for each account to keep management creds  simple.

**Comment by chad-cook** [comment]
Yep 100% agree. I'll try and organise something using the custom resolver. I might report back if i have any success. 
As for core functionality. I would agree in handling credentials with profiles. I found the decision to remove the idea stipulating a aws profile on deployment interesting as it would be more important give the above situation. 
Thank you for the quick reply.

**Comment by jamesroutley** [comment]
This looks related to #85

**Comment by theseanything** [comment]
@jamesroutley  - true, but that wouldn't work for creating a single stack that needs to pull another stacks output.

**Comment by chad-cook** [comment]
A solution could be to stipulate a different profile and region for the stack_output_external command. If left blank it would default to the profile used to execute sceptre. From this you would have to create a new boto session with the appropriate details. 

`parameters:
  <name>: !stack_output_external::<account_profile>::<region> <full_stack_name>::<output_name>
`
As far as I'm aware there isn't a application that allows for cross-account and cross-region referencing of stacks. This application is closest to the solution i've seen.

**Comment by ngfgrant** [comment]
this will be resolved in #257
