### ISSUE TITLE
Change function name of `_get_stack_statuses` in Environment class

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#9]
The function name does not accurately describe the purpose.

**Comment by jamesroutley** [comment]
How about `_get_initial_statuses`? `_get_intial_stack_statuses`?

**Comment by theseanything** [comment]
_get_initial_statuses() or _initalise_pending_statuses() or _get_pending_statuses()

**Comment by jamesroutley** [comment]
_get_initial_statuses
